### ISSUE TITLE
Data use: Tag links

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#10]
The data use page has tags for categories which should link to a search result.

**Comment by timrobertson100** [comment]
2 things need to happen:

1) The CMS API needs to expose a endpoint to search for any content type that has a tag of e.g. invasive

2) We need to consider what section of the web app should show those results.  One idea is just an omni search, another idea is an omnisearch with "tag: invasive"

**Comment by MortenHofft** [comment]
Links created to cms search with the relevant tags. Not all tags could be linked as they seem not to be present in the search ui.
If we do not deem them worth having in the ui we could consider if they are worth showing as tags anywhere at all.

Country isn't linked either. That is a shame. The reason it isn't added is that the Drupal API returns ids for countries that do not match the ISO code that is used in search.
Example 
```
"researcherLocation": [
{
"name": "United States",
"id": 0
}
]
```
vs `http://internal.gbif-dev.org/cms/search?category_country=US`

For now I have removed tags that are not linkable by id to the search UI. including country.

**Comment by kcopas** [comment]
After we create Drupal literature pages/nodes from the the Mendeley API, could we bulk edit the country tags? Or should we consider converting or adding ISO compliant country codes to Mendeley library prior to import?

**Comment by MortenHofft** [comment]
Given that the majority of the tags work I have changed the impact of this issue. It would be nice that the tags were linkable though. I will continue to let country tags be hidden

**Comment by MortenHofft** [comment]
Not applicable after we reimplemented search API
