### ISSUE TITLE
Drafting: Newsletter and lists page

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#100]
Page content should include:
- [x] Newsletter sign-up (GBits/news, BID regional lists per [current webform](https://madmimi.com/signups/194104/join)) 
- [x] [Mailman mailing lists](http://lists.gbif.org/mailman/listinfo): thumbnail description of each (excluding BID mentors)
- [x] RSS feeds for news and events: @burkeker **do others exist?**

**Comment by kcopas** [comment]
@dnoesgaard can you help me move this one along, too? 

No cause for alarm, just looking for the loose ends (and found one).

**Comment by dnoesgaard** [comment]
@kcopas absolutely, I actually think I started working on this one already...

**Comment by dnoesgaard** [comment]
Note: RSS feeds on current portal are definitely being accessed.

After filtering raw logs (Slack is hitting the site hard, responsible for 50% of rss traffic), there are a few hundreds hits to http://www.gbif.org/newsroom/news/rss every day.

Now, how many visits to the site are then referred from RSS readers...

**Comment by dnoesgaard** [comment]
Opened #153 to make sure RSS feeds are enabled...

**Comment by dnoesgaard** [comment]
@burkeker or @MortenHofft: on https://demo.gbif-dev.org/generic/newsletters I've tried embedding a Madmimi sign-up form using an iframe:

`<iframe src="https://madmimi.com/signups/302099/iframe" scrolling="no" frameborder="0" height="735" style="max-width: 738px; width: 100%;"></iframe>`

It almost works, but it seems some of the styling is stripped. Can you help? Or if it's not the preferred way, let me know how you want me to proceed :)

**Comment by MortenHofft** [comment]
We have no control over the styling within an iframe - but we do strip the width. We could not do that. 
It will never look similar to the remainder of the site. At some point we should do as on [BID](http://bid.gbif.org/) so we have proper control over styling and possibly fill in country based on geoIp. Notice that the BID version is a select box for country

For now this is fine - in the sense that it works - we can later go to MadMimi and get the form and required js to use without iframe.

**Comment by dnoesgaard** [comment]
Ok, I'm going to park this with you for now, @MortenHofft, as the remainder of the content is pretty much done. All it needs now is

- [ ] a working form from Madmimi
- [ ] a little styling on the table

Feel free to push it back, if anything else needs touching up.

**Comment by kcopas** [comment]
@MortenHofft @timrobertson100 this page is a strong candidate for some customization. The list-y nature of it makes it seem sprawling, but on a desktop viewport it could probably all be contained on one screen. Probably not a top priority with other things to do, but it could definitely benefit from some quick care and feeding…

Also another page where the date display doesn't add value (see #163 )

**Comment by kcopas** [comment]
I've removed the 'release blocker' from this, thinking that improvements are (very) nice to have but not required for launch—please prioritize additional styling and refinement (or not) as you see fit, @MortenHofft @timrobertson100 @thomasstjerne.
