### ISSUE TITLE
Style all omnisearch results, and provide featured items

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#101]
All omni search results need a review in style (e.g. thumnails etc). 
When no search terms are present, suitable featured results should appear.
- [ ] species "list" result
- [ ] publisher search result
- [ ] news search result, adding features to simulate newsroom when no search
- [ ] featured data use, adding features to simulate newsroom when no search
- [ ] events should show as a chronological list showing upcoming events, with ability to view all past events (sortable table perhaps?)
- [ ] program search result
- [ ] project search result
- [ ] documents, featuring those indicated by the drupal content
- [ ] presentations, featuring those indicated by the drupal content
- [ ] tools, featuring those indicated by the drupal content

**Comment by dnoesgaard** [comment]
@MortenHofft, just noticed that in search results from GBIF network, titles with descending letters are slightly truncated, e.g.

![search](https://cloud.githubusercontent.com/assets/21358085/20662791/31a101ac-b555-11e6-85b6-584b9ef72a74.png)

both on gbif.org and  gbif-dev.org,

**Comment by MortenHofft** [comment]
Hi Daniel. Yeah I've noticed. And I like that you do to. Thanks for reporting it 👍

**Comment by MortenHofft** [comment]
all results have been restyled :)
