### ISSUE TITLE
case-sensitive URLs?

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1012]
Not necessarily a bug, but i noticed that while this works:

https://www.gbif.org/occurrence/1269537010

this doesn't:

HTTPS://WWW.GBIF.ORG/OCCURRENCE/1269537010

it doesn't even produce a 404, it just keeps "loading"...

**Comment by MattBlissett** [comment]
It's a bug that it doesn't show 404.  A feature could be to redirect to the lower-case one.

(URLs generally are case-sensitive.)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/ab121c3ee073c5c29e3a1b49d989e766ac22d2ee
