### ISSUE TITLE
Customize landing page: News summary

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#1016]
This [Google Analytics report](https://github.com/gbif/portal16/files/2433391/Analytics.All.Web.Site.Data.Quarterly.bounces.20180701-20180930.20180401-20180630.pdf) gave me a fresh reminder on another important facet of our search-result-as-landing-page approach. I can't quite dope out the reasons, but our news summary page has a 99.7% bounce rate—people who arrive there almost always check out, immediately.

I can't find any anomalies by adding dimensions and think that this shows no one is finding what they want when they land there. Can we put this enhancement on the docket sometime soon? We've discussed several other landing pages, but thus far I think I've only documented ideas for publishers (see #600 ).  

We should work through some treatments / guiding concepts / UX stories. My initial thought is that we should leverage the card approach with the features, but we should also allow search and sorting by date or relevance, with the former the default. I don't think the sorting is by date now—look at the out-of-sequence results five pages into the search.

Perhaps @MortenHofft @dnoesgaard @timhirsch and I can take this up in earnest after GB25?

**Comment by MortenHofft** [comment]
The link to the report shows data from https://www.gbif.org/newsroom/summary a page that is a 404. So that makes sense.
We should probably redirect them to https://www.gbif.org/resource/search?contentType=news

**Comment by kcopas** [comment]
Closing as an instance of #600
