### ISSUE TITLE
New duplicate version of dataset published?

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#1019]
There's a dataset that's ostensibly new, but there's an older one that still exists, thanks to the one recorded DOI citation: https://www.gbif.org/dataset/search?publishing_org=e2b19af8-fecd-4636-bb66-61e0d430d308

Presume that the dataset was meant to be updated but was instead published a second time.

**Comment by MortenHofft** [comment]
Looks like a data issue and not an issue with the portal.

**Comment by kcopas** [comment]
Sorry, but I don't have the rights to label this or reassign it if it needs to go somewhere else.

**Comment by MattBlissett** [comment]
You probably do now.

**Comment by MattBlissett** [comment]
Ah, but this is the portal16 repository. It would belong better in portal-feedback, so it's seen with all other similar data feedback.

**Comment by kcopas** [comment]
Probably what I intended...sorry for the confusion…
