### ISSUE TITLE
Suggest a dataset that's not online

### ISSUE THREAD

**Issue by siro1** [gbif/portal16#102]
**https://github.com/gbif/portal16/issues/74** follow up
There is need for a form that can also capture datasets that are offline or not digitized so as to serve both data rescue and general data mobilization. The suggested dataset catcher is very restrictive when the requirement for an "internet link to data" is a mandatory field.  I think that if we remove the mandatory requirement for an internet link, the form can also serve as an opportunity to mobilize datasets that are not online.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/ce59cb3ad26384bf0b6ecc43020b40e213d24a5b

I must admit that a link to where to find the data seems essential to me. Doesn't have to be online, could just be to the data holders website or such.
Either way - it has been removed. Notice that it is now possible to suggest a dataset without any contact info or reference to where the search for the data could start. This of course makes it easier to suggest a dataset and more difficult to locate it.
