### ISSUE TITLE
"Quick fixes" for demo.gbif.org

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#103]
This is a catch-all issue of things we should try and fix on demo.gbif.org before Tuesday evening.  
They should all be "quick fixes" but would make for a better first impression.  If not quick fixes they should be transformed into issues that we address later.  Please check any off that are complete and announce any underway so folk don't work on the same thing.

As we find more, issues will be added below:
- [x] GBIF Logo in menu does not appear on Firefox on windows machine (observed on Melianie)
- [x] Homepage image needs to say "Photo by Scott Buckel, CC-BY-NC" not just "CC" in the link*
- [x] News page header image needs to have attribution\* (use current site format)
- [x] Data use page header image needs to have attribution\* (use current site format)
- [x] _Italicize_ the scientific name in the featured search box of species in omni search (species page italicize the name already - http://demo.gbif.org/search?q=gadus%20morhua) 
- [x] _Italicize_ the scientific name in the header of the occurrence detail page (species page italicize the name already - http://demo.gbif.org/occurrence/1265893023) - perhaps italicize the classification underneath as well (no need to parse, each can just be italicized)?  
- [x] ...more links on mobile do nothing (perhaps remove them as I always click and try and do stuff there?)
- [x] http://demo.gbif.org/dataset/32ab1d81-9131-45e3-ae74-69dd696341ea the explore button is cropped on the lower edge
- [x] Create an IPT page - minimum with the important text from gbif.org/ipt but ideally with a map and the counts.  No need to redo all the quotes, release etc.  That can just be links to github page. **(Content written, now Morten adding the page)**
- [x] http://demo.gbif.org/occurrence/gallery?taxon_key=2292251 hovers on the `table``map`and `gallery`loose pointers 
- [x] Use CartoDB token for base map in the occurrence search - some tiles are missing.  See http://api.gbif-dev.org/v2/map/demo-cartodb.html as an example
- [x] Show something sensible on http://demo.gbif.org/search?q= (perhaps feature the latest news item plus Plantae, Animalia and then just show the first records of each entity. Or suchlike...)  You arrive at that page quite a lot in playing around
- [x] **(Morten looking)** Try and show some indication to users when image in gallery search are not found.  Either an `<img onerror...` or a "24 are offline" which accumulates in the header.  Or something.
- [x] The magnifier icon on the front page doesn't capture the search term. Only "Enter" does. 
- [x] The load more images button on the occurrence gallery says "test".  It should say something like "Load more" or "More" or whatever is consistent with the rest of the site
- [x] issues facet on occurrence search isn't translated. And maybe we should show them all instead of just the facets. The downside of showing the facets is that they are often loaded very slow and appears empty the first 10 seconds or so
- [x] Species pagination not working
- [x] in classifications do not show the rank of the match. e.g. if species then show classification from kingdom to genus, but not species.
- [x] terms of use as we are using GA
- [x] ipt map control needs z-index
- [x] no index no follow so we do not get the demo site indexed. should still work with GA
- A big message this year is all the work on licensing - please be vigilant on this as it undermines all the effort behind what we're promoting.

**Comment by MortenHofft** [comment]
cannot say for sure what the reason could be for the missing logo. My best guess is caching as the font wasn't versioned. I have added that (param not filename). I will test windows Firefox when I get the chance.

**Comment by MortenHofft** [comment]
" http://demo.gbif.org/occurrence/gallery?taxon_key=2292251 hovers on the table map and gallery loose pointers " - do you mean to remove the cursor pointer on hover? In that case I will say no unless you say it twice. Pointer on interaction elements and tabs in particular is standard. Just try writing a comment on github and toggle the preview.

**Comment by MortenHofft** [comment]
"perhaps italicize the classification underneath as well (no need to parse, each can just be italicized)?" It isn't something we do on the current site. but if it is the correct thing to do then yes. But others know that better than I. What say ye?

**Comment by MortenHofft** [comment]
IPT page is created, but maps and counts is still missing

**Comment by mdoering** [comment]
Only latin names of rank genus or below should be italicized, so the classification should remain as it is. See https://en.wikipedia.org/wiki/Binomial_nomenclature#Other_ranks and https://projects.ncsu.edu/cals/course/zo150/mozley/nomencla.html

IPNI examples for family name in regular letters:
http://www.ipni.org/ipni/idPlantNameSearch.do?id=30000468-2

And an italicized genus name:
http://www.ipni.org/ipni/idPlantNameSearch.do?id=325655-2

**Comment by kcopas** [comment]
Small tweaks from me, all navigation-related. Reading from left to right…

- [ ] Share > Dataset Classes: change to lowercase 'c' '..classes' for consistency
- [ ] Tools > Users: move 'Web application' up to second in the list, below 'GBIF API'
- [ ] Same item: change name to 'GBIF web application'
- [ ] For now, move 'Tools catalogue' from 'Tools > GBIF Labs ' to last position under 'Tools > Users'
**Question**: if we improved the curation and content for the current tools items, should we add a 'Data publishing tools' under Publishers? The search result could be 'content type=Tools' + 'purpose=data publishing' under Publishers. All 'content type=Tools' could appear under Tools > Users > Tools catalogue
- [ ] Add 'Funders' to list below 'Inside GBIF > About > Become a member'
- [ ] Inside GBIF > About > Strategic Plan: : change to lowercase 'p' '..plan' for consistency
- [ ] Change 'Inside GBIF > Information' to Inside GBIF > News & communications'
- [ ] Move 'Awards' from 'Inside GBIF > Information' to 'Inside GBIF > About', below 'Strategic plan' 
- [ ] Change 'Inside GBIF > Programmes + projects' to 'Programmes & projects'

Tentative suggestions: not sure how this will work out, so please use your judgment on whether to implement.
- [ ] Inside GBIF > Programmes and projects > BID programme: not sure how this will look, but can we test appearance of 'ACRONYM: Name in Full' for BID and BIFA—thus 'BID: Biodiversity Information for Development' and 'BIFA: Biodiversity Information Fund for Asia'? I know this will wrap, but the lowercase programme, while consistent, still doesn't seem right to me.

**Comment by kcopas** [comment]
For further discussion/consideration (i.e. not for today): should we add a 'Knowledge centre' link under 'Inside GBIF > News & communications' that shows a search result of all documents, presentations and tools? This would respond to Mélianie's feedback after last Wednesday's demo, asking 'Where is the resource centre?' I am worried that network audience would see its absence as a loss of functionality.

**Comment by MortenHofft** [comment]
tweaks added in https://github.com/gbif/portal16/commit/c503e735a56b8c149023163d4869830a83b072e6
Let us see how many tools we end up with - the plan is still to give them an overhaul isn't it? removing dead links etc. But i wouldn't mind an "other publishing tools" under tools->publishing . it is what we do for news, etc so it isn't odd as such

**Comment by MortenHofft** [comment]
I have moved the knowledge centre discussion into its own issue (https://github.com/gbif/portal16/issues/124) and will close as it was inteded as a temporary catch all leading up to gb23
