### ISSUE TITLE
GRIIS download issue(s)

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#1032]
Text file encoding issues, perhaps? Via email from [Shyama Pagad](mailto:s.pagad@auckland.ac.nz):

> Please can you help with the question below. I did notice that some characters did not display properly. I downloaded from the species matching tool.
> Looking forward to hearing back from you.

-----Original Message-----
> From: [Anke Stein](anke.stein@uni-konstanz.de) 
> 
> I downloaded some data from the GRIIS website (which looks like a great resource!) as a csv file but have some trouble displaying some of the special characters. Some accents are shown correctly, but I get a lot of question marks e.g. for sources of entries for Russia or Serbia. I tried different encodings in a text editor, but didn't manage to display all the text correctly.
> Could you please let me know which encoding is used in your database, i.e. how I can display all sources etc. correctly without hieroglyphs?
>  
> Thank you very much in advance!

**Comment by MortenHofft** [comment]
Could eb that we have an encoding issue.
But I'm not sure I understand. How is the csv from the GRIIS website related to the website project? And how is that related to the species matching tool? 

Is it possible to get an example file for the failling csv? Both the downloaded as well as the one uploaded that returns a strange encoding?

Thanks

**Comment by kcopas** [comment]
Sorry—I presume it's a question of the download, but let me cycle this back through email...

**Comment by spag005** [comment]
Greetings,
We realized that Anke who reported the complaint may be referring to the GRIIS.org website. 

However, I have attached an example of an uploaded and corresponding downloaded file and a result of a species matching exercise.

[United_Kingdom.xlsx](https://github.com/gbif/portal16/files/2509558/United_Kingdom.xlsx)
[UK_Taxon_download.xlsx](https://github.com/gbif/portal16/files/2509544/UK_Taxon_download.xlsx)
[normalized_2.xlsx](https://github.com/gbif/portal16/files/2509551/normalized_2.xlsx)

Regards
Shyama

**Comment by ahahn-gbif** [comment]
I suspect a csv/Excel issue here, rather than data content problems. Opening a csv file directly with Excel frequently results in issues, because the standard encoding setting that the application uses on that action is usually "Windows (ANSI)". Opening a new Excel file instead and using the Data import dialog allows to set UTF-8 instead. Doing this, the characters show correctly (alternative version of "normalized" attached).
[normalised.xlsx](https://github.com/gbif/portal16/files/2509609/normalised.xlsx)

**Comment by spag005** [comment]
Thanks Andrea, will try this the next time and get back to you if I have any issues
Regards
Shyama

**Comment by MortenHofft** [comment]
If this continues to be a problem, then please open an issue with a link to the GBIF tool used and the csv uploaded and downloaded (csv please, not the xlsx as that introduce errors from the outside).

This FAQ item may also be of interest though it refers to downloads: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
