### ISSUE TITLE
Non-ASCII characters in passwords not correctly encoded

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1058]
We had legacy behaviour (no specific encoding, happened to work for ISO-8859-1) for passwords in the registry before.

This is now set to UTF-8 in the backends, following RFC 7617, but the portal needs to be updated.

The auth header for the username `søren` and the password `SØREN`, which is what the web browser sends, is:
```
Basic: c8O4cmVuOlPDmFJFTg==
```

If your terminal is set to UTF-8 you can get this with `echo -n søren:SØREN | base64`.

The registry receives:
```
Authorization: Basic c/hyZW46U9hSRU4=
```
which is ISO-8859-1-encoded (`echo -n søren:SØREN | iconv -t iso-8859-1 | base64`).

https://github.com/gbif/registry/issues/67
https://github.com/gbif/portal-feedback/issues/1399

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/a54c14fe1c8fa411fc1e562263084333abdd7dfe
