### ISSUE TITLE
GRSciColl prose content needs revising

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1064]
@timrobertson100 and @dnoesgaard

GRBIO (aka GRSciColl?) has been migrated in the APIs and are now available on UAT in the website.
https://www.gbif-uat.org/grbio

The prose for the about page is here
https://app.contentful.com/spaces/uo17ejk9rkwj/entries/CjbQ5GRDvaMuKkayyuMO0

there is also content in Crowdin for proof reading or complete change if needed. If you decide that the larger prose pieces should change a lot, then perhaps we should do so in the danglish version as well. It is nice that they do not drift too much.

https://crowdin.com/translate/gbif-portal-en/244/endk-en

**Comment by dnoesgaard** [comment]
Go ahead and assign this one to me, please :)

**Comment by dnoesgaard** [comment]
The Crowdin translations are done.

**Comment by MortenHofft** [comment]
I assume this can be closed then?
