### ISSUE TITLE
Test observations

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#108]
- [ ] Post to Facebook should have better metadata, and perhaps to add a picture. 
  ![post_to_fb](https://cloud.githubusercontent.com/assets/637631/19696060/eb181c68-9ae5-11e6-9555-d1ffb9883485.png)

**Comment by MortenHofft** [comment]
yes - all pages need opengraph tags to ease sharing through facebook

**Comment by kcopas** [comment]
@dschigel just noted this again: 

> Do you know the way we could replace or remove the passage  on cookies under the title, when posted to FB? Gives a bit weird impression that "GBIF is watching you". First three lines of the abstract would be better. 

@MortenHofft, maybe your present Altmetric investigations make this a relevant thing to look at now?

**Comment by dnoesgaard** [comment]
Hey @MortenHofft - maybe this one can fit into the tag work you're doing with Altmetric atm?

**Comment by burkeker** [comment]
Update of current metadata sending seen by Facebook:
![screenshot 2017-03-03 12 36 26](https://cloud.githubusercontent.com/assets/637631/23549849/5ac20410-000e-11e7-91f4-f0d0079f2ab9.png)

**Comment by dnoesgaard** [comment]
@burkeker gbif-dev.org shouldn't be accessible from the outside though, right?

**Comment by MortenHofft** [comment]
I've added the option to add open graph tags and have done so for cms driven pages
![screen shot 2017-07-21 at 10 43 00](https://user-images.githubusercontent.com/6759267/28455998-66974316-6e01-11e7-8d27-2a394f95a313.png)
