### ISSUE TITLE
add translation string

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1090]
Please add translation to gbif-portal-en:

enums.cms.vocabularyTerms.projectStatus.DISCONTINUED
(enums -> cms -> vocabularyTerms -> projectStatus -> DISCONTINUED)

"Discontinued"

**Comment by dnoesgaard** [comment]
On a separate note, would it be possible (and make sense) to use notation for context in Crowdin that is used to reference translations in the code , e.g.

enums.cms.vocabularyTerms.projectStatus.DISCONTINUED

(it makes finding translations 100x easier)

**Comment by dnoesgaard** [comment]
Exactly. When I want to change a translation, I grab the key and search for it in Crowdin. It would be easier if I didn't have to change dots to arrows. Make sense?

**Comment by dnoesgaard** [comment]
Oh, I may have misunderstood something. You're saying you don't control the way that Crowdin shows the context?

**Comment by MortenHofft** [comment]
It is a JSON object. in code that is referred to as `some.property.goes.here`. Crowdin shows that as arrows. You might be able to configure how they show JSON keys somewhere, I haven't looked. But if is can be changed, then it is a Crowdin configuration.
