### ISSUE TITLE
Update link in API summary page

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#1093]
Line 97 of the API summary page links to the developer blog. Not sure that it's as simple as swapping to the data blog, so we may want to remove or at least recast the context: https://github.com/gbif/portal16/blob/d3f7b407a4ba53ae2f7cd018986325926529198d/app/views/pages/developer/summary.nunjucks#L97

**Comment by jhnwllr** [comment]
I think you could put in the data-blog.
