### ISSUE TITLE
Publisher page: Create a stub page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#11]
Many pages, such as a dataset need to link to a publisher page.  We'd like a page which includes:
  1. The title of the publisher
  2. A declaration that this is a stub page
  3. A list of datasets published by the publisher, unstyled but clickable to aid navigation

**Comment by MortenHofft** [comment]
https://github.com/gbif/portal16/commit/99bcc81ebdbb8eaa4f9d026a6db905b8729cd109
