### ISSUE TITLE
Detect and format URLs in metadata

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal16#113]
URLs starting with `http://` are currently not detected nor formatted in dataset metadata. It would be a huge improvement if they were, as it would allow users to just click on these (cf. how it is done in the IPT). E.g. the URL `http://data.canadensys.net/vascan` in the description of http://demo.gbif.org/dataset/3f8a1297-3259-4700-91fc-acc4170b27ce

Note that URLs in DwC terms are already detected and formatted, e.g. `datasetID` on http://demo.gbif.org/occurrence/1078063802

**Comment by MortenHofft** [comment]
You are right of course and they now do so. thanks

**Comment by peterdesmet** [comment]
Nice! It's fixed now in the full description, not yet in the truncated one:

<img width="824" alt="screen shot 2017-06-26 at 13 59 25" src="https://user-images.githubusercontent.com/600993/27538362-dc9732d0-5a77-11e7-9b83-fa4712f7f0cc.png">
