### ISSUE TITLE
verify domain ownership for Google

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1139]
I'm getting some additional non-profit services from Google, but I need to verify that we own gbif.org. I think we did this recently, so we just need to replace the existing file with this one (assuming it has done its job):

[googlec6e2f5b9f4606d66.html.txt](https://github.com/gbif/portal16/files/3072381/googlec6e2f5b9f4606d66.html.txt)

(remove .txt - must be available at https://gbif.org/googlec6e2f5b9f4606d66.html)

Thanks.

**Comment by MattBlissett** [comment]
This is awkward to do, could you send me the DNS TXT record option instead?

**Comment by dnoesgaard** [comment]
Sure.

`@			IN		TXT		"google-site-verification=0h2yFFQ_BT38KR88ONQQHwVW6vDRyHvUYGmbD6sMlP0"`

**Comment by MattBlissett** [comment]
Done.

**Comment by MortenHofft** [comment]
> replace the existing file with this one

as far as i remember those files need to stay in place
