### ISSUE TITLE
Download on species-lookup doesn't work

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#1157]
**Download on species-lookup doesn&#39;t work**

1. Go to `https://www.gbif.org/tools/species-lookup`
2. Upload CSV
3. Lookup species
4. Click `Generate CSV`
5. The popup has a round circle to download and a somewhat off-center placed `cancel` link. Clicking the circle or anywhere else does not trigger a download for me.

-----

User provided contact info: @peterdesmet
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/9ab74ce4be141fef346eac4dceec002e:5f2f9e3967ae9ebbab56aa8b748f60e7e3a4d87a12213a90a82deacdf9369013de824eb912dd7b60906173cb0eadcba76435e996b77cd5fc2f1f9f48dad26a63)
Referer: https://www.gbif.org/tools/species-lookup
Window size: width 1377 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-09T07:23:54.535Z',mode:absolute,to:'2019-05-09T07:29:54.535Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-09T07:23:54.535Z',mode:absolute,to:'2019-05-09T07:29:54.535Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
I would actually close this issue and see if it ever resurfaces again.
