### ISSUE TITLE
Changes to country pages

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1168]
I'd like to request the following changes to the country pages, e.g.
https://www.gbif.org/country/CL

- [ ] add Projects tab (listing projects associated with country, e.g. https://www.gbif.org/resource/search?contentType=project&contractCountry=CL)
- [x] reorder sections on Participation tab (e.g. https://www.gbif.org/country/CL/participation) according to this:

* basic info (as currently)
* social media, feeds and newsletter (moved)
* (new field in Contentful `progressAndPlans`) - "Progress and plans"
* mission (moved)
* funding (moved)
* history (moved)
* structure (moved)
* REMOVE secondary links
* contacts (as currently)

Mock-up:

![Screenshot 2019-06-03 at 14 15 00](https://user-images.githubusercontent.com/21358085/58801150-08fb6980-860a-11e9-82c1-02d6ffd947d7.png)

Let me know if anything here doesn't make sense!

**Comment by MortenHofft** [comment]
The tabs area is being pressed for space on these pages as there is a request for a new one every so often. Adding an additional looks like the breaking point. I wonder if we should do something else entirely. Any ideas?
![Screenshot 2019-06-03 at 16 04 20](https://user-images.githubusercontent.com/6759267/58808016-79f64d80-8619-11e9-820e-3de59c131a31.png)

**Comment by dnoesgaard** [comment]
I see, right. We could collapse data into a dropdown to save _some_ space?

Data
   |- Data about
   |- Data publishing

**Comment by MortenHofft** [comment]
how about tabs being
`summary | data about | data publishing | participation (if there) | more`
with `more` being a dropdown with all the links to other parts of the site
* news
* alien species
* projects
* publications from
* publications about

**Comment by dnoesgaard** [comment]
Thanks Morten. Will follow up shortly.

**Comment by MortenHofft** [comment]
regarding `REMOVE secondary links`. If they are to be removed from the website, then they should be removed from Contentful as well shouldn't they? Else it is confusing and makes editors think they are used.

**Comment by dnoesgaard** [comment]
We can't drop alien species, so this is what KC and I agreed on:

`SUMMARY | DATA ABOUT | DATA PUBLISHING | PARTICIPATION | ALIEN SPECIES | MORE...`

(MORE drop-down containing)

- NEWS
- PROJECTS
- PUBLICATIONS FROM
- PUBLICATIONS ABOUT

OK?
