### ISSUE TITLE
Suggested dataset page does not open

### ISSUE THREAD

**Issue by asturcon** [gbif/portal16#1171]
If we go to https://www.gbif.org/dataset/b46569c1-4237-41be-b35f-7da37d18ef51 and we click on the suggested dataset that appears in the _suggestions_ section nothing happens. 

If I open the console of the dev tools of chrome I can see this error:
` Failed to load resource: the server responded with a status of 404 () `

I understand that If the dataset doesn't exist it shouldn't appear in the suggestions.

**Comment by MortenHofft** [comment]
thanks. it isn't exactly a good suggestion either. It simply does a free text search for the url and takes whatever comes up. it kind of works for urls with a seo friendly name. But for UUIDs it doesn't make sense
