### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#119]
We have added Google Analytics, but haven't added any specific events, search terms, filtering of IPs, environments etc. We could use this issue as a discussion of what we want to track and do. Please add below if you have ideas or if tracking of an event is already implemented. 
- [x] filter ips
- [ ] seperate uat and prod
- [ ] enable tracking of search terms across search types
- [ ] Find a good way to accumulate usage stats across items of a type (a ala how many clicked explore on dataset pages, not how many did it on this specific page)

**Comment by kbraak** [comment]
Each IPT version's download is tracked on current site:
![screen shot 2016-10-27 at 09 15 56](https://cloud.githubusercontent.com/assets/5981100/19757943/0f62fa0c-9c26-11e6-8723-1f3ef1fb6c64.png)

**Comment by kcopas** [comment]
The last three might be a little duplicative, but four of the goals tracked on the current site are worth replicating, imho:

+ Occurrence download (Goal 1)
+ 5-minute visit (Goal 2)
+ 30-minute visit (Goal 5)
+ Mega-browser (Goal 6) (seven-plus pages in a session)

**Comment by MortenHofft** [comment]
@kcopas mentions that this https://moz.com/blog/how-to-use-search-analytics-in-google-sheets-for-better-seo-insights might be interesting/worth looking into

**Comment by MortenHofft** [comment]
from [Jira](http://dev.gbif.org/issues/browse/POR-3016?jql=project%20%3D%20POR%20AND%20status%20%3D%20Open) from kcopas

**Adjust newsletter subscribe link to enable GA goal tracking**

The request is aimed at supporting Google Analytics tracking of on-site newsletter subscriptions as a new goal conversion.
This probably requires adding a Javascript 'onClick' event to the 'Subscribe' button, seen, for example, here:
http://www.gbif.org/newsroom/summary
The link is already redirected once:
http://www.jangomail.com/OptIn.aspx?RedirectURLSuccess=http%3A//www.gbif.org/newsletter-subscription/confirmation
Please review for feasibility. For more on tracking this specific GA event, see:
http://areatype.com/blog/tracking-newsletter-signups-google-analytics-goals
https://raventools.com/gaconfig/google-analytics-event-tracking/newsletter-signup/
as well as
https://www.google.com/analytics/web/?hl=en#management/Settings/a42057855w71692566p73962076/%3Fm.page%3DGoals%26m-content-goalList.rowShow%3D10%26m-content-goalList.rowStart%3D0%26m-content-goalList.sortColumnId%3Dname%26m-content-goalList.sortDescending%3Dfalse/
If implementation is overly complicated in current site, deferral the request as a new requirement for implementation in GBIF.org v3.
