### ISSUE TITLE
Progamme and project pages

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#12]
Migrate the existing pages into the project mirroring existing functionality.
There have been a lot of requirements capture and iterations already and the audience is rather small so we don't want to open these up to widespread changes at this stage,

**Comment by burkeker** [comment]
Prospective tasks are:
- [ ] API endpoints and URL alias handling for Programme and Projects.
- [ ] Related project/activities views in JSON format for consumption.
- [ ] Programme page templates/controllers.
- [ ] Project page templates/controllers.
