### ISSUE TITLE
Use other metric than impact factor for data paper journals

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal16#120]
As an organization valuing open science, please don't use impact factor as the (only) metric for data paper journals on http://demo.gbif.org/generic/publishing/data-papers.

<img width="753" alt="screen shot 2016-10-27 at 09 48 12" src="https://cloud.githubusercontent.com/assets/600993/19758837/85720d92-9c2a-11e6-9e15-abf05562d543.png">

Impact factors are a flawed metric (see this [recent article](http://blogs.plos.org/thestudentblog/2016/08/24/reforming-publishing-to-value-integrity/)) and by providing only that one, potential data paper writers are influenced in choosing a journal based on the wrong criteria. Rather, indicate which journals are [full open access journals](https://doaj.org/) and maybe also their APC costs. I'm happy to provide that information.

**Comment by dnoesgaard** [comment]
Duly noted. I have no problem leaving out the impact factor altogether. We have APC costs and OA information already, so we can include this in the table instead.

**Comment by peterdesmet** [comment]
Great!

**Comment by dnoesgaard** [comment]
How about something like this?

<img width="749" alt="screen shot 2016-10-27 at 14 17 14" src="https://cloud.githubusercontent.com/assets/21358085/19766850/5393b7a0-9c50-11e6-8df0-e9966626794e.png">

(estimate for easy comparison, based on 5000 words/15 pages)

**Comment by peterdesmet** [comment]
Nice, some questions/suggestions

* Open access = open access journal or does this also include hybrid journals?
* Would express APC estimates in same currency + indicate that currency + use thousands separator.
* I would drop impact factor altogether 😄

**Comment by dnoesgaard** [comment]
Thanks for your comments, Peter.

- "Open Access" currently includes hybrid journals - I guess I could categorize them "pure OA", "hybrid OA" or "not OA"?
- agreed
- will consider :)

**Comment by peterdesmet** [comment]
For OA, I would use the terms:

* Yes
* Hybrid
* No

For those that are yes, you could link the word `yes` to the DOAJ journal page, e.g. for Phytokeys: https://doaj.org/toc/1314-2003/12

You could also opt to not include hybrid/no, but it including them gives an better overview of where *not* to publish.

**Comment by dnoesgaard** [comment]
Thanks Peter!

**Comment by dnoesgaard** [comment]
Turns out I was mistaken about the "hybrid" journals. In my list, "hybrid" indicates a journal that's not "pure data". So AFAIK "yes" means pure OA.

I was able to pull DOAJ links for most of them, except for these:

BioRisk (Pensoft)
Biota Colombiana (Alexander von Humboldt Biological Resources Research Institute, Colombia)
Check List (Biotaxa)
China Scientific Data (Chinese Acadademy of Sciencies)
Data (MDPI Open Access Journals)

@peterdesmet, are you familiar with DOAJ and why I might not be able to find these journals?

**Comment by dnoesgaard** [comment]
Here's my latest version of the table

![screen shot 2016-10-28 at 13 53 06](https://cloud.githubusercontent.com/assets/21358085/19805633/f50f0d4e-9d15-11e6-9f22-7c9ae364473a.png)

Ideally, it will be sortable by clicking the column headers.

**Comment by peterdesmet** [comment]
Nice. I wouldn't add decimals to the price + would use `-` for `N/A` impact factor. I'll have a look at the journals you mention, but the publisher of the journal has to submit their journal to DOAJ, so DOAJ might not be aware of all.

Can you post the whole table?

**Comment by peterdesmet** [comment]
Didn't find those journals on DOAJ either. Have already notified Pensoft for BioRisk: https://twitter.com/peterdesmet/status/792029585596682240

**Comment by peterdesmet** [comment]
Also, typo in `Chinese Acadademy of Sciencies` -> `Chinese Academy of Sciences`

**Comment by dnoesgaard** [comment]
Thanks @peterdesmet. I'll work these thing in and post a complete table later. I actually tweeted DOAJ, and Check List has now been added.

**Comment by dnoesgaard** [comment]
Here's the whole table with corrections. I've also hyperlinked the APC estimatse so that the source of that information is easily accessible:

![screen shot 2016-10-31 at 11 02 14](https://cloud.githubusercontent.com/assets/21358085/19850598/87d564a8-9f59-11e6-9de4-89462d57c49f.png)

**Comment by peterdesmet** [comment]
Great! I assume `-` for APC means `no costs`?

**Comment by dnoesgaard** [comment]
Yeah, I actually changed it $0 for consistency. Agreed?

**Comment by peterdesmet** [comment]
Yeah, seems fine + links are helpful. Guess this issue can be closed. Nice overview!

**Comment by dnoesgaard** [comment]
Thanks for your thoughts and comments! Very helpful :)
