### ISSUE TITLE
double-up on threat status

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1207]
In translations, is there any difference between these two:

threatStatus.json
iucnStatus.json

Our Russian translatator noticed this...

**Comment by MortenHofft** [comment]
good question. 

iucn status is the status enumeration provided by iucn's APIs.

threatstatus is what we get in our own API and reflect publisher data
e.g. https://api.gbif.org/v1/species/2435099/distributions

They have been implemented at different points in time and I hadn't even noticed that they were identical.

I haven't seen anything stating that these are intended to be aligned, but clearly they are in practice. Except for the naming of the enumerations.

I do not know if we do any normalisation on the published values. Nor if we intend them to be the same. @mdoering you can probably help me here?

**Comment by mdoering** [comment]
I dont know where iucnStatus comes from, but threat status is part of our GBIF Java API and used in CLB to index data: https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/ThreatStatus.java

It is intended to represent the IUCN status values so this sounds like a complete duplication indeed

**Comment by mdoering** [comment]
It is also based on the IPT vocabulary here: http://rs.gbif.org/vocabulary/iucn/threat_status.xml

**Comment by mdoering** [comment]
which is actively maintained: https://github.com/gbif/rs.gbif.org/issues/22

**Comment by MortenHofft** [comment]
Thank you. I will then use one vocabulary for both IUCN and our own APIs threatStatus
