### ISSUE TITLE
Cross browser and device stability

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#121]
Catch all for browser and OS issues.
- [x] ie edge have problems with the drawer. it will occasionally slide to show the "hidden" drawer instead of the "page". I haven't been able to reproduce in ie10.
- [ ] viewport height not working properly on mobile safari leading to scrolling issues and hidden headers.

**Comment by MortenHofft** [comment]
## viewport height not working on mobile safari
mobile safari (and mobile chrome have also implemented this bug recently) do not consider viewport height to be the height of the viewport but the height of the device. basically that browser bottom bar that slides up when the user scrolls up is considered part of the height. that means that placing things along the bottom of the viewport height will hide them behind the browser bottom bar. And that making an interface the height of the viewport will require scrolling to see the whole page. 
Because we have a fixed header and the remainder of the page is viewport height minus header height it can lead to situations where you can scroll away from the header and not being able to retrieve it.

This wouldn't be a problem if safari could handle fixed headers, but fixed elements doesn't work when zooming to an input field. it will remain fixed to the screen instead of the page half the time. 

I'm not sure how to best approach this.

I have seen different solutions.
Some disable position fixed when input fields get focus and reenable it again on blur. Others avoid fixed headers. Others disable zooming, but that is generally not recommended as this is a useful feature of the web and nice for users. Others have scripts for repositioning based on resize events. Flexbox can be applied, but have browser issues.

**Comment by dnoesgaard** [comment]
- [ ] The "classification-list" separator (>) doesn't display correctly in Chrome for Mac

![screen shot 2016-12-07 at 16 12 59](https://cloud.githubusercontent.com/assets/21358085/20973195/10a79890-bc98-11e6-83f5-afecc8236f08.png)

**Comment by kbraak** [comment]
@MortenHofft some additional related issues:

Feedback doesn't work on mobile+Android+Chrome - https://github.com/gbif/portal16/issues/328
Login button not shown on mobile+Android+Chrome - https://github.com/gbif/portal16/issues/326
