### ISSUE TITLE
projects missing from country pages

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1227]
It seems that projects are missing from country pages—haven't been able to figure out why. There should be a projects option in the More... dropdown if a country has project, i.e.

https://github.com/gbif/portal16/blob/c31ee02ff5fa712aa31e8fc26e1a1c1b471c6237/app/views/pages/participant/country/nav.nunjucks#L43

**Comment by MortenHofft** [comment]
Could you give an example of a page that doesn't work please?

**Comment by dnoesgaard** [comment]
https://www.gbif.org/country/ZW/summary
