### ISSUE TITLE
Drupal api issues

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#123]
- [x] Limit do not work
http://internal.gbif-dev.org/api/cms/search?limit=100
returns `"limit": 50`

- [ ] offset seems odd:
http://internal.gbif-dev.org/api/cms/search?offset=1392
returns an error

- [x] http://internal.gbif-dev.org/api/cms/search?limit=100&offset=100
returns `"offset":50`

- [x] relatedGbifResources has defect urls:
http://demo.gbif.org/data-use/newsroom/uses/2015-galluzzi-et-al.debug
returns
```
relatedGbifResources": [
{
"url": "http://cms.gbif-uat.orghttp://www.gbif.org/species/2733060",
"title": "Bactris gasipaes",
"attributes": []
}
],
```
the content in Drupal is correct (http://www.gbif.org/species/2733060)

**Comment by burkeker** [comment]
By default the CMS API pages using "range" and "page". Range equals "limit", and "page" takes "range" to calculate offset, which means the number of offset can only work nicely if it's a multiple of range.

On the Express side I've translated "limit" and "offset" to the correct params to Drupal. Please try the above URL. For a random offset number the portal tries to calculate the closest number(page). See the second call.

This is not perfect, I know. But please close this issue if the API already supports what we need on Express.

**Comment by MortenHofft** [comment]
Sounds good. Didn't intended to create unnecessary work. I simply noticed the other day, and thought I would mention as I got 500s and odd behaviour. Thought that it might entail unforeseen errors in other scenarios as well - but if it is known behaviour and a part of the contract to only ask for multiples then I'm fine with that. Reading above I see that it sounds a bit abrupt. Didn't mean to.
