### ISSUE TITLE
Alternative citation for pre-DOI downloads

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1230]
For downloads from before we started issuing DOIs the citation should probably include a link to the download page rather than "https://doi.org/"

e.g. https://www.gbif.org/occurrence/download/0001232-150116162929234

**Comment by MortenHofft** [comment]
I'm not sure I understand the example:

![Screenshot 2019-08-20 at 13 55 27](https://user-images.githubusercontent.com/6759267/63345075-38408d80-c352-11e9-8f21-46baf6f9e112.png)

**Comment by dnoesgaard** [comment]
Sorry, my mistake. I assigned a DOI to this example after creating this issue.

Here's another one: https://www.gbif.org/occurrence/download/0000859-140827132448942

**Comment by dnoesgaard** [comment]
To ensure that people actually do cite when using an old download, could we just include the url of the download page itself in the citation—in the cases when no DOI exists?

So basically:

> **Citation**: GBIF.org (31 August 2014) GBIF Occurrence Download https://www.gbif.org/occurrence/download/0000859-140827132448942

(they'll still be encouraged to contact us for a DOI, but I'd rather they cite something identifiable than simple "GBIF.org")

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/c6054fb954e7f1baa292f7a17e71426a93ac62fb
