### ISSUE TITLE
"Soft" returns in MarkDown not displaying as expected

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#125]
Looking at my list in the Funders page (http://demo.gbif-dev.org/generic/funders), I was surprised to see the single carriage returns not respected in the country lists. I had expected:

> **Andorra**
> Institute d´etudes Andorrans

not

> **Andorra**  Institute d´etudes Andorrans

This means that the returns-that-aren't-line-breaks aren't working where countries have multiple funders e.g. Germany, United Kingdom, United States.

Is this rendering properly/as intended? If not, should we produce these as unordered lists?

**Comment by burkeker** [comment]
I've tried carriage returns within two pipes "|" didn't work, either. It seems it's a limitation of Markdown for multiline text in table. As [this](http://alvinalexander.com/text/how-put-multiple-lines-markdown-table-cell-multiline-table) tip works.
