### ISSUE TITLE
Strategic plan + implementation plan

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#126]
Urgently need to discuss Donald's wish to see the strategic plan presented with the implementation plan's 22-odd activities nested under its five priorities. Programme/project model may suffice, but I'd appreciate some help on a) feasibility and b) structure. Bringing it up after a discussion in Brazil, as it may also require some custom programming to produce the desired effect.

Note that [current stub page](http://demo.gbif.org/strategic-plan) is using the generic template and would need to be replaced.

**Comment by MortenHofft** [comment]
is the programme project ideal for this? Funding, project tables, funders, and the idea of making projects more into small sites as we have talked about seem to move this into another direction. See https://github.com/gbif/portal16/issues/93

Could normal generic entries suffice for the individual parts and then having another (possible uniquely styled) page for summarizing and giving an overview? It doesn't necessarily sounds like something that would require huge amounts of manual work to update once in a while?

**Comment by kcopas** [comment]
I would definitely like to work together to sort out how best to present all this. The target's moved a little, too, with the need/desire to create clear links between the longer term strategic plan and the annual-ish implementation plan.

**Comment by kcopas** [comment]
Stub out for initial launch—combined presentation of plans to follow in very early 2017

**Comment by kcopas** [comment]
[Initial summary page](https://www.gbif.org/strategic-plan)—with designed PDF attached—published as part of the switchover.
