### ISSUE TITLE
Review/simplify Drupal taxonomies

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#127]
With the introduction of cross-content search, the current set of Drupal taxonomies may be over-articulated. In addition, at least one legacy set is barely used for being somewhat impractical. 

I proposed the most recent revisions two years ago, which Burke then implemented. I now propose a quick but thorough review to see what can be safely stripped away.

**Comment by kcopas** [comment]
[ ] Create four new terms in the Drupal Topics taxonomy: data management, data paper, biodiversity science, phylogenetics
[ ] Edit the current Drupal Topic ’taxonomic research’ to ’taxonomy’
[ ] Delete ‘Mountain biodiversity’ from Drupal Topics taxonomy

Run import against Mendeley records against the following tags from the updated Drupal Topics vocabulary: 
+ Agriculture
+ Climate change
+ Conservation
+ Data management
+ Data paper
+ Ecosystem services
+ Human health
+ Invasive alien species
+ Biodiversity science
+ Phylogenetics
+ Taxonomy

**Comment by burkeker** [comment]
This is done as part of the literature search.
