### ISSUE TITLE
Integrate travel guidelines documentation

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#128]
Following on from the proposal on footer content, I'd like to ask for help in bringing the GBIF Travel Guidelines fully into the site. A search for this document /'travel guidelines'/ on the new site returns [no results](http://demo.gbif.org/search?q=travel%20guidelines)—probably the result of this originally inhabiting the IMS-legacy netherworld of files and documentation. 

The [link](http://links.gbif.org/travel_guidelines.pdf) currently in the footer resolves here:
http://www.gbif.org/sites/default/files/documents/GBIFtravelguidelines.pdf

As mentioned in #77 , admin staff note that this document need NOT appear in the footer, so long as it appears via search. As such it is probably a prime candidate for the featured search term 'travel guidelines' if it's brought into Drupal.

Whatever the most efficient solution is, we might want to address the legacy URLs, too, and redirect them to the file's new location.

**Comment by MortenHofft** [comment]
@burkeker what would be the best approach for this? Only generic contenttype supports featured search terms at this point.

**Comment by burkeker** [comment]
I am afraid that's not true, @MortenHofft. All editable content types support featured search term, just that, in this case, the travel guideline is not a Drupal "resource" _per se_, but merely a proxied link http://links.gbif.org/travel_guidelines.pdf to the actual file in the Drupal filesystem.
I'll then 
- [ ] create such a resource so it appears in the search result.

**Comment by MortenHofft** [comment]
Don't be afraid - it it good news - I must have misunderstood you then

**Comment by kcopas** [comment]
Highlighted again in review discussion with AMN & SLS.

**Comment by kcopas** [comment]
Notes surfaced from admin discussion. Two other docs that need to be available in the same way are 
-[ ] [travel authorization](www.gbif.org/sites/default/files/documents/GBIF Travel Authorisation Form (visitors) 2014.dot)
-[ ] [travel reimbursement](http://www.gbif.org/sites/default/files/documents/Visitor%20Travel%20Reimbursement%20Form%202016.xlt)

**Comment by burkeker** [comment]
To address this, I have:

- [ ] Modified allowed file extensions in the file field setting.
- [ ] Created 3 resources mentioned above with "travel guidelines", "travel authorization" and "travel reimbursement" as their featured search terms, respectively.
- [ ] Revised the URL http://links.gbif.org/travel_guidelines.pdf to http://www.gbif.org/travel-guidelines via http://links.gbif.org.
- [ ] Updated the footer link to the travel guideline.

**Comment by burkeker** [comment]
Please feel free to re-open this if there is still anything needed.
