### ISSUE TITLE
Add verbatim species view

### ISSUE THREAD

**Issue by mdoering** [gbif/portal16#129]
For non backbone species we need a verbatim view similar to the occurrence verbatim view.
Example in the previous portal: http://www.gbif.org/species/108589176/verbatim

A new tab view might be most appropriate with a table view of the data

**Comment by MortenHofft** [comment]
how about reusing the pattern from occurrence details where we show them both in one table. If the users a looking into verbatim views, it might be nice to be able to compare the differences like we allow for on occurrence details

**Comment by mdoering** [comment]
there used to be a verbatim view already when we had the same view for non backbone usages:
https://github.com/gbif/portal16/blob/17e65ea2d084e32faceb5f65e8b32c1be30b6640/app/views/pages/species/key/speciesVerbatim.nunjucks

Showing the verbatim infos next to the interpreted makes sense - maybe just an additional third column would be enough

**Comment by MortenHofft** [comment]
@thomasstjerne this is relevant to what you are up to

**Comment by thomasstjerne** [comment]
@MortenHofft  I will look into that. Could be as a separate tab?
