### ISSUE TITLE
Redundant hostnames

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#1298]
Notice from Google Analytics, fwiw (20/1/20):

Redundant Hostnames
First detected: Jan 14, 2020 7:56:47 AM
Last detected: Jan 14, 2020 7:56:47 AM

Property www.gbif.org is receiving data from redundant hostnames. Some of the redundant hostnames are:

    gbif.org
    www.gbif.org

Redundant hostnames are counted as separate rows in reports, so hits that are going to the same page on your site from different hostnames will be split into multiple rows. With data split across multiple rows, traffic to specific pages will appear lower than it actually is.

To avoid this problem, consider setting up a 301 redirect from one of your redundant hostnames to the other, or create a search-and-replace filter that strips "www." from hostnames.

Google Tag Assistant Recordings can help you verify that your redirect is setup correctly, or that your filter is working as intended.

Learn more: https://support.google.com/analytics/bin/answer.py?answer=1034834&hl=en

**Comment by MattBlissett** [comment]
We already have the redirect from http://gbif.org and https://gbif.org to https://www.gbif.org, so I don't know where these could be coming from.

**Comment by kcopas** [comment]
It was more fyi—I don't really understand this area terribly well…
