### ISSUE TITLE
Add download links to dataset JSON markup

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1299]
`distribution` should be added to the JSON markup of dataset pages:

```
...
"description": "blablabla",
"distribution": [
    {
      "@type": "DataDownload",
      "contentUrl": "https://www.gbif.org/occurrence/download?dataset_key=<key>",
      "encodingFormat": "zip"
    },
    {
      "@type": "DataDownload",
      "contentUrl": "https://api.gbif.org/v1/dataset/<key>/document",
      "encodingFormat": "xml"
    }
  ],
"license": "blabla",
...
```

(I don't know to what extent the URLs should or shouldn't be hardcoded)

**Comment by MortenHofft** [comment]
@dnoesgaard I have added as above. But reading the [specs](https://developers.google.com/search/docs/data-types/dataset#download) and following the link to https://schema.org/DataDownload it says that contentUrl is the
> Actual bytes of the media object, for example the image file or video file.

If that is the case we cannot do much else than referencing the verbatim archive (when it is an archive)

What do you think?

**Comment by dnoesgaard** [comment]
Hmm, annoying. I don't want to encourage people to download anything directly tbh. Let me ask my Dataset Search contact...

**Comment by dnoesgaard** [comment]
Ok, as I don't want to direct people to IPT endpoints, we should probably just roll this back. No point in linking *only* to the EML. Sorry.
