### ISSUE TITLE
Disable scroll zoom on occurrence page map

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal16#131]
On an occurrence page, you can currently zoom the map with the scroll wheel (or touchpad): http://demo.gbif.org/occurrence/1233599085

As this functionality is also used to scroll up and down the page, it can become difficult to scroll beyond the map, especially on mobile devices. Try to put the cursor above the map and scroll down the page: instead of scrolling further, you zoom out on the map.

I would disable the scroll zoom on the map and have users use the + and - buttons. Scroll should be reserved for page scroll only.

**Comment by MortenHofft** [comment]
The scroll is already disabled per default and only activated when interacting with the map. The height of the map is responsive such that it is always smaller than the height of the screen. This is exactly to ensure that the user do not get caught on the map on e.g. mobile devices and small screens.
We could consider disabling it completely. That might be acceptable for the occurrence page where little interaction is probably required. But for other pages with maps I would think that the above described behaviour makes better sense.

example of very small screen and the map adapting size
![screen shot 2016-11-07 at 14 53 39](https://cloud.githubusercontent.com/assets/6759267/20060149/02714a4c-a4fa-11e6-8239-7dffd6df6efe.png)

**Comment by peterdesmet** [comment]
Great, didn't realize zoom was disabled if you didn't interact with the map first + map height not being too high. Well done, leave it as it is! 👍
