### ISSUE TITLE
Hide or gray out gallery when no images are available

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#132]
This is just an idea that would help me and possibly others:

When returning a set of occurrences for which no images are available, could we hide or somehow gray out the `GALLERY` tab, e.g. this one has no images:

![demo_gbif_org_occurrence_gallery_dataset_key_6bc8ff15-8517-4704-96fc-b8696377b364](https://cloud.githubusercontent.com/assets/21358085/19999159/f838e7aa-a270-11e6-9de5-9a2a27aa253a.png)

So if it looked something like this, it could save me a click and time ;)

![demo_gbif_org_occurrence_search_dataset_key_6bc8ff15-8517-4704-96fc-b8696377b364](https://cloud.githubusercontent.com/assets/21358085/19999242/6c30049a-a271-11e6-84e7-9b42ceedb104.png)

**Comment by MortenHofft** [comment]
I completely agree that this would be nice to do. Only thing is that it will be delayed as additional calls are needed.
Also show a more useful information on the tab when there is no images. and while they load.
