### ISSUE TITLE
Return HTTP 404 for former participant organisations

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1332]
For former participant organisations (not countries) such as [this example](https://www.gbif.org/participant/364) please return HTTP 404.

Please let @helpdesk know when live

**Comment by MortenHofft** [comment]
Should we remove it from the public APIs?

**Comment by timrobertson100** [comment]
Thanks Morten

We do want to preserve history but don't want casual users to get confused. I think this suffices.

**Comment by MortenHofft** [comment]
The quick fix to remove former participants also mean that OBIS no longer has a participant page. @timhirsch suggests that we 
> link either to this page https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6 or to the ‘affiliate’ page for IOC at https://www.gbif.org/the-gbif-network/gbif-affiliates .

I will create a hardcoded code redirect to the network page (a regular redirect won't suffice as it is used in the angular routes that fiddle with browser history)
