### ISSUE TITLE
Add filters to allow range searches for coordinateUncertaintyInMeters

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1335]
Currently blocked by https://github.com/gbif/occurrence/issues/152

**Comment by MattBlissett** [comment]
This was deployed 3 weeks ago, sorry, I forgot to tell everyone.

http://api.gbif.org/v1/occurrence/search?coordinateUncertaintyInMeters=0,100

http://api.gbif.org/v1/occurrence/search?coordinateUncertaintyInMeters=0,*

http://api.gbif.org/v1/occurrence/search?coordinateUncertaintyInMeters=100000,*

Could you also update the API documentation in the portal?
