### ISSUE TITLE
UK bug report

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#1361]
@MortenHofft the [attached PDF](https://github.com/gbif/portal16/files/4694693/Bug_reports_GBIF_UAT_27.05.20.pdf) gives a rundown on a small set of issues our Ukrainian translators have found.

__I've resolved nr.1 and 6__: these strings were hidden in CrowdIn. nr.1 is relatively new and so mostly untranslated in other languages. nr.6 has only a handful of translations. Thinking in both cases that these were hidden accidentally, but they're now in the new CrowdIn pull request here.

I think nr.3, 8 and 9 are also all hidden in CrowdIn. They're complicated enough that it made me think they were hidden for a reason. I'd rather have you review, tbh.

nr.7 is the result of some navigation elements that the team overlooked—they'll pick those up, and I'll publish them as they come in.

nr.2, 4 and 5 are all squarely in your territory—as in, I wouldn't even know where to begin!

**Comment by MortenHofft** [comment]
3 is a type in the translation
should be NUMBER_FORMATTED not NUMBER_FORMATED

**Comment by dnoesgaard** [comment]
I have hidden a few translations at times—although I can't quite remember why. Probably when a translation wasn't used anymore? That doesn't appear to be the case here, so... ¯\_(ツ)_/¯

2) ?
3) was using SELECT instead of PLURAL—fixed
4) static, not translatable
5) ?
8) fixed
9) unhidden, needs translating

**Comment by MortenHofft** [comment]
5: I've changed it so enums always show the full text in filters (that is no truncation)

**Comment by MortenHofft** [comment]
4: I've made it translatable.

**Comment by MortenHofft** [comment]
All but nr 2 are solved, and that has a seperate issue https://github.com/gbif/portal-feedback/issues/2803
So I'm closing this
