### ISSUE TITLE
Use correct IUCN branding on species pages

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1368]
> The scale we use for the showing the red list is from Wikidata and is not the correct branding that IUCN uses.  This will need to be updated.

_Originally posted by @andrewrodrigues in https://github.com/gbif/pipelines/issues/257#issuecomment-638804219_

Thomas or Morten will presumably need to know what the correct branding is.

**Comment by MortenHofft** [comment]
I'm unable to find any image resources and useful branding guidelines or similar on their website.

I see that they use below (e.g. [here](https://www.iucnredlist.org/species/56289/11442549)). But the link I can extract from peaking in their code does not look like it is intended for public use: https://nrl.iucnredlist.org/assets/category-scale/category-scale_en-b35daaf0196bafd2fb96e6b3496d3152e032d75bf09c471dcc493eeb930c724b.svg

<img width="857" alt="Screenshot 2020-06-08 at 11 09 33" src="https://user-images.githubusercontent.com/6759267/84012920-90478f80-a978-11ea-9c8e-183c51f97e5b.png">

And this pdf is the description I can find on the website
https://www.iucnredlist.org/resources/redlistguidelines

@andrewrodrigues could you possibly get some more info on what they want and have them provide the resources we need. The PDF doesn't not seem to have relevant info, but I didn't read the 113 pages carefully.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/78f600a68311abf08700c762e1d8c7b575bc1045
