### ISSUE TITLE
Distribution status (present/absent) is not used when showing distributions

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1375]
This species: https://api.gbif-uat.org/v1/species/159674339/distributions is absent in Burundi, but is shown as present on the species page: https://www.gbif-uat.org/species/159674339

Required for https://github.com/gbif/data-mobilization/issues/175 to progress.

**Comment by MortenHofft** [comment]
It looks like it ignores the actual status
https://github.com/gbif/portal16/blob/master/app/views/pages/species/key/speciestypes/nonBackboneSpecies.nunjucks#L51-L52
