### ISSUE TITLE
Dataset taxonomy browse: early feedback

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#139]
The dataset taxonomy browse is wonderful.  

I know it is in an early stage of development, but some early feedback.

- [ ] Use ajax and a spinner rather than page reload
- [x] Change info for occurrence datasets to "The classification of all taxa derived from occurrences in Naturalis Biodiversity Center (NL) after normalising against the GBIF backbone taxonomy"
- [ ] Italicise names for genus and below
- [x] Keep the authorship for the genus when expanded (currently it disappears once clicked)
- [x] Improve the display of synonyms, rather than a species under a species (is there a standard way of labelling those @mdoering?)
- [x] Suggest improve the visuals for the occurrence count.  It reads like a record ID to me where it is currently placed.
- [x] Show core details in header on right hand side (name, rank, status, basionym, publishedIn)
- [x] Show all other details incl verbatim as a table similar to occ detilas

Feedback based on http://demo.gbif-dev.org/dataset/15f819bd-6612-4447-854b-14d12ee1022d/taxonomy/3297070 which looked like this:

![screenshot 2016-11-09 10 29 02](https://cloud.githubusercontent.com/assets/237221/20133318/6345d0d6-a667-11e6-986d-b3fca4abf991.png)

**Comment by mdoering** [comment]
BUG: the classification of the species http://demo.gbif.org/species/7650074 is shown as children in the browser: http://demo.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7/taxonomy/3211812

**Comment by mdoering** [comment]
I would suggest to show synonyms only in the species details section still to be done on that page. Likely in a kind of split screen next to the tree.

**Comment by mdoering** [comment]
https://github.com/gbif/portal16/commit/75d14f93643036ac0402e8ff8ad50070907a19f1

**Comment by mdoering** [comment]
show species details: https://github.com/gbif/portal16/commit/6eb8284c76e7db10e89f625dc6b88da947b7f5ff

**Comment by mdoering** [comment]
The species page for both datasets and the backbone has been refactored.
Apart from continuous ajax loading of clicked taxa in the tax browser and italic names in the tree all issues are solved. The other 2 are not critical right now, so we can close the issue

**Comment by mdoering** [comment]
![checklist species](https://cloud.githubusercontent.com/assets/327505/20429432/dd31884e-ad8e-11e6-92c7-be9fff67c441.png)
![occurrence species](https://cloud.githubusercontent.com/assets/327505/20429433/dd321d2c-ad8e-11e6-9405-f7fdc4303a5d.png)
![backbone species](https://cloud.githubusercontent.com/assets/327505/20429434/dd3236c2-ad8e-11e6-8cd2-37db44ce1239.png)
