### ISSUE TITLE
Add identifiedBy filter

### ISSUE THREAD

**Issue by muttcg** [gbif/portal16#1395]
The API is ready:

https://www.gbif.org/occurrence/download/0010796-200613084148143
https://www.gbif.org/api/occurrence/search?advanced=true&locale=en&identified_by=Carmelino+S%C3%A1ntiz+Ru%C3%ADz

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/acdfac3d4d13d388285d6143f0cc2d3b89df062f

@muttcg We have an autocomplete for recordedBy. shouldn't we have one for identifiedBy as well then?
