### ISSUE TITLE
how should present/absent work in the UI?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1396]
@ahahn-gbif and @MattBlissett you both have opinions on this and they disagree.

If I understand correctly, then Matt strongly believes that there should be a 1:1 correspondence between API and UI urls.

Andrea argues that it is such a fundamental filter that we should have it as a hidden default (clicking the trashcan will clear all filters and only show PRESENT). And showing all is, from the users perspective, adding a filter.

Personally I started implementation thinking of it as a filter like all else, but with a warning encouraging a choice. And then I wanted to add a pre-filter on all links. But that is annoying when clearing filters. But as Matt argues that could be solved by compromising on what it means to clear filters. Clear could mean to clear anything but the PRESENT/ABSENT filter?

**Comment by ahahn-gbif** [comment]
> Clear could mean to clear anything but the PRESENT/ABSENT filter?

I would be fine with that interpretation
I am not sure I understand the conflict yet. From the user perspective, having a filter labeled "presence data only" and with the box pre-checked, allowing to remove the filter implying that now both presence and absence are included, but having the filter "reset to default" on trashcan activation (box pre-checked again) should be consistent with API use, just phrasing the label accordingly?

**Comment by MattBlissett** [comment]
I don't know if we disagree, as I don't know what Andrea's opinion on the URL was.

I think https://www.gbif.org/occurrence/search should not have filters, so if the default is to filter for present occurrences, then links from the homepage, clicks on the homepage map and so on should go to https://www.gbif.org/occurrence/search?occurrenceStatus=PRESENT

That maintains consistency between the WWW URL and the API URL, which is particularly useful for explaining the API to beginners, including beginners with no programming experience, and quick use of the API (by using the portal to construct queries) for everyone else.

**Comment by MortenHofft** [comment]
Thank you both for your inputs. I've made a version and put in on UAT (as you might have seen). i will close this issue. Feel free to create a new one if you find the implemntation unfortunate.

**Comment by MattBlissett** [comment]
(I've also deployed it to gbif-dev.org, as UAT was overwritten with translations. Dev only has two absence records though.)

On maps (homepage, dataset, species etc) could you change the "Explore" and click-on-the-map links to have occurrenceStatus=present as part of the filter? The map has excluded absences for a year or two now.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/e6696262d8ed991bbd4deffe4f3420558fc02714
