### ISSUE TITLE
Language detection on first visit doesn't "stick"

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1399]
Visiting GBIF.org for the first time, with a browser set to request Spanish, returns the homepage in Spanish, but the language selector shows English is selected.

Clicking any link shows pages in English.

**Comment by MortenHofft** [comment]
Ahh. that autodetect is a leftover from when we didn't have translations. I should probably remove it. It only ever translated the headline.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/3370db3bd6a90ac0b505b7a764213028d53a9a7c
