### ISSUE TITLE
Consider moving extensions on occurrence page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1404]
The occurrence page currently has data in this order:

1. summary
2. map
3. images
4. record
5. about the dataset
6. extensions

A good example is this (UAT) link https://www.gbif-uat.org/occurrence/2810024015

The publisher reports that 

> The extensions appear below the “About the dataset” section which almost makes them appear as not part of the record and almost invisible because they are so low down.  Any chance of moving them up above that “barrier”?

This seems like a good suggestion to me

**Comment by MortenHofft** [comment]
I've only ever heard complains about the "About this dataset" section. And we have moved it down the page twice already. Perhaps it is time to remove it altogether. The link to the dataset is in the top of the page anyhow for anyone interested.
