### ISSUE TITLE
Observation trends using a year of 2018

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1408]
After selecting taxa, the date slider on the map defaults to 2018, and charts are generated with 2018.

I'd updated a hardcoded year, but all I can see is 2016 in the source.

(Low priority. It's still possible to drag the slider to 2020.)

**Comment by MortenHofft** [comment]
Based on useful feedback https://github.com/gbif/portal-feedback/issues/1671 we changed the default end date to current year - 2 (to compensate for the delay in records)
