### ISSUE TITLE
Improve maps api documentation

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1452]
From GBIF France:

> Missing parameters description on https://www.gbif.org/developer/maps
>  
> The Map page is missing the "Query parameters explained" table, like the very useful one on the Occurrence page: https://www.gbif.org/developer/occurrence#parameters

**Comment by ManonGros** [comment]
It is not just the map, the Download API is also missing an explanations of the parameters (https://github.com/gbif/portal-feedback/issues/3152)
