### ISSUE TITLE
Enable linking using original (taxon/occurrence) source ID

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1453]
This is desired by GBIF France (mirrored issue exists in occurrence here: https://github.com/gbif/occurrence/issues/220)

> From our occurrence page (ex: https://openobs.mnhn.fr/openobs-hub/occurrences/b88279d3-0950-4347-930f-b97ef2304b32), we would like to have links to:
> - the GBIF occurrence page: https://www.gbif.org/occurrence/2599165010
> - the GBIF species page: https://www.gbif.org/species/2888811
>  
> However, our portal only knows our own occurrence or species uuids, not the GBIF ones.
> Since our uuids (Occurrence ID or TaxRef species ID) are known by gbif.org, I'm able to forge the gbif.org URL, by calling the GBIF API first.
>  
> But to avoid this 2-steps mechanism and help integration with other portals, what do you think about implementing such "redirection" service on your side?
>  
> calling https://www.gbif.org/occurrence/{datasetKey}/{occurrenceID}
> ==> would redirect to the right occurrence page, using the OccurrenceID of the given dataset
>  
> calling https://www.gbif.org/species/{datasetKey}/{sourceID}
> ==> would redirect to the right species page, using external taxon uuid (sourceID) defined in the checklist (datasetKey)
> (datasetKey= checklist dataset ID, like https://www.gbif.org/dataset/0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6)

**Comment by MortenHofft** [comment]
That is already possible (have been for 3 years) and created exactly for that purpose, it is just a little known feature. But every now and then someone asks.

**Occurrence**
`https://www.gbif.org/occurrence/first?[someQueryGoesHere]`
Will do an occurrence search. if there is exactly 1 result, then it will redirect to that. If there are multiple, then it will redirect to an occurrence search.

In above example
https://www.gbif.org/occurrence/first?occurrence_id=3c168231-6fdd-40ea-994b-3f32606c9226

**Species**
Something similar exists for species, but it behaves slightly different as it has to use multiple APIs.
`https://www.gbif.org/species/first?[someQueryGoesHere]`

* If a `sourceId` is provided it will use the `/species?` [endpoint ](https://www.gbif.org/developer/species#nameUsages)
* Else it will use the `/species/search` [endpoint](https://www.gbif.org/developer/species#searching)
  * If no `datasetKey` is provided then it will assume backbone, unless you explicitly state `backboneOnly=false`

As with occurrences, it will link to the entry if there is only one result, else it will go to search.

e.g. 
https://www.gbif.org/species/first?sourceId=6B773CF4C72F0995A4228111BFAA28B8.taxon
https://www.gbif.org/species/first?datasetKey=0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6&sourceId=125295
https://www.gbif.org/species/first?q=Polymorphus%20L%C3%BChe,%201911&rank=GENUS&datasetKey=0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6&origin=SOURCE

Hope that helps

**Comment by MortenHofft** [comment]
A `redirect to backbone entry if available` could be an optional parameter. But I do not know if that is of interest
