### ISSUE TITLE
Evaluate/implement CMS search using multiple facets

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#147]
Currently CMS facet search doesn't support multiple filters in the same facet.
http://cms.gbif-dev.org/api/v2/search?filter[type]=data_use&filter[type]=news

We need to decide whether we want to improve it in this release.
This is relevant to #124

**Comment by burkeker** [comment]
We agreed that the default behaviour of the search should be enough for the initial release. We would then observe how it is used and decide whether to tackle this by manipulating deep into the Drupal Search API, or the content might be hosted with different search scenario.

**Comment by MortenHofft** [comment]
if it isn't supported shouldn't it be disabled in the interface as well then?

**Comment by burkeker** [comment]
What do you mean by disabling it in the interface?

When a filter is checked, the facet is automatically updated with available filters that has intersection with the checked one. Since content types are mutually exclusive, filter[type]=data_use&filter[type]=news for now only return results of news.

This issue is about returning both data_use and news in this query, so called AND query.
