### ISSUE TITLE
Add ability to view publishing organisation to network pages

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1475]
From VertNet:

> ..but having also the list of distinct organizations that those data sets come from would be even more useful from the community-building perspective. Is it reasonable to add a tab that lists the organizations?"

Currently, we have the network tab - perhaps we should have "datasets" and "organisations" tabs, each stating "The datasets/organisations that participate in the network".

**Comment by MortenHofft** [comment]
The list of datasets is nicely available in the API, but organisations not so. 

We can do this as a proxy API that gets all distinct publishers by paging through the datasets (800 for OBIS)
https://registry-api.gbif-uat.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6/constituents?limit=25&offset=0
and look up the publisher for each.

Or we can add facets to the API request. E.g.
`https://registry-api.gbif-uat.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6/constituents?limit=0&facet= publishingOrganizationKey`
and look up the publisher for each.

Or we can add a new endpoint in the API
`https://registry-api.gbif-uat.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6/constituentOrganizations`

Which solution do we prefer?

**Comment by timrobertson100** [comment]
Since this is strongly modelled in the registry, it should be the final option. It's a simple SQL statement on the primary data rather than a hacked view from secondary copies.

I propose the API should be similar to our `/node/{UUID}/organization` so would be `/network/{UUID}/organization` in the Registry API .

**Comment by timrobertson100** [comment]
See https://github.com/gbif/registry/issues/287

**Comment by MortenHofft** [comment]
Available in dev. When the API is deployed to uat and prod it will show there as well
