### ISSUE TITLE
Create a form for uploading derived datasets

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1477]
from @timrobertson100 
> In addition, we need a form that logged in users can post the file and generate a derived dataset. The API is [documented](https://github.com/gbif/registry/blob/master/docs/derived-dataset.md)

**Authorization**
@mike-podolskiy90 I see that basic Auth is supported. Is it also possible to use a bearer token (as in the data repo implementation and other registry services)?

**Updating**
I see that it is possible to update previously created derived datasets. Is this something that we want to support as well in the UI? And can I get a list of the derived datasets I have created?

**Comment by mike-podolskiy90** [comment]
Authorization - yes, it should be possible.
Updating - I think we should provide this functionality in the UI.
It's not possible to get all derived datasets created by the user right now, but having this sounds reasonable

**Comment by MortenHofft** [comment]
**List my derived datasets**
For downloads we have `/occurrence/download/user/{user}` (returns the downloads I have created)
Could we have a `/derivedDataset/user/{user}` that returns all my derived datasets?

**Authorization**
The portal normally use the trusted application approach - is this supported?

**Comment by MortenHofft** [comment]
@thomasstjerne I suggest that we

* add a tab on user profiles with the list of derived datasets that user has created. It will look similar, and redirect to the corresponding derived dataset pages (those already exists). The filter of course won't be available.
* Add a create and about page. You can look at https://www.gbif.org/data-repository/upload at use that as a starting point
  * Instead of the search tab we could have a `My Uploads` that only shows when logged in and shows the same list as under my profile.
* Add an edit button to the list and detail views if you are the owner of the dataset. Edit will take you to a form similar to the create one.

<img width="1060" alt="Screenshot 2021-04-06 at 09 44 49" src="https://user-images.githubusercontent.com/6759267/113676520-cfd82880-96bc-11eb-877c-a04b48fd101e.png">
