### ISSUE TITLE
Show quarterly analytics for GBIF regions

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1486]
The same quarterly statistics and charts as we already use for ISO-3166 regions are now also produced for the GBIF regions.

Data is in https://analytics-files.gbif.org/gbifRegion/

Please add pages for each region showing these analytics.  

While the analytics pages are being changed, I think it would also be useful to expose the source CSVs for each figure, e.g. add a small link to the corresponding CSV.

**Comment by MortenHofft** [comment]
@timrobertson100 the last thing I remember about Regional pages was that more clarification was needed before we were to expose anything.
How should we go about these? Should we explore region pages or put them on https://www.gbif.org/the-gbif-network for now?

**Comment by timrobertson100** [comment]
Regional pages go far beyond this.
I propose we modify the "explore country or area" on the [Analytics page](https://www.gbif.org/analytics/global) to allow the selection of a region (e.g. 2 drop downs or one covering both)

**Comment by MortenHofft** [comment]
Makes sense to add it to the list on top of the global analytics page. But that is just an entry that takes you somewhere. If not the network pages and not a region page as such. Then perhaps just `https://www.gbif.org/analytics/regional/:REGION` ?

**Comment by timrobertson100** [comment]
Ah, yes I see. I overlooked that we moved the country charts to the country pages.

I imagined that it would stay on the analytics page, as you propose. In the future, in a redesigned "the gbif network" section, we could reconsider.

**Comment by MortenHofft** [comment]
In that case I suggest this
https://www.gbif.org/analytics/global will use optgroup to have region and country in one dropdown
```
GBIF Regions
  Africa
  Europe
  ...
Countries and Areas
  ...
```

<img width="874" alt="Screenshot 2021-02-01 at 14 36 34" src="https://user-images.githubusercontent.com/6759267/106465943-f69a9880-649a-11eb-9e8e-0aeeb09b2903.png">

**Comment by timrobertson100** [comment]
Sounds like a sensible approach

**Comment by kcopas** [comment]
Just to flag this: we should probably use the “verbatim” names of the regions (e.g. Europe and Central Asia, Latin America and Caribbean) rather than the vernacular (Europe, Latin America)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
