### ISSUE TITLE
Implement literature search (phase 1) in the content API

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#15]
In the current implementation Drupal triggers a crawl of mendeley and generates JSON files.

In phase 1, we wish these to be searchable from omnisearch and agree that the best first implementation will be to import these into Drupal and surface in the CMS JSON API.  We should consider if these are really the same content type as the ```data-use``` type to keep the API concise.  Certainly from a naive user perspective, they are all just documenting use of GBIF.  We could consider a flag of ```curated``` for the GBIFS authored items.

In the future (phase2+) we may rewrite crawlers in Java and do richer APIs.

**Comment by burkeker** [comment]
The data-use articles is a news coverage that may include multiple scholar papers as use cases, while mendeley citations may include reports that are not necessarily use cases of GBIF data. Therefore I'd suggest we should surface the literature as a distinct content type and it should be filterable from a search result. To make them available for search, some tasks are:

- [ ] Create a bibliography content type
- [ ] Dump all the crawled result (without changing the current crawling) to the content type
- [ ] Configure and rebuild the index for generic full text search of Content API.

**Comment by timrobertson100** [comment]
I'd suggest calling this the "reference" content type.  It is not a bibliography, which is the list of sources used to compile some work.  It is a content type documenting referenced use of GBIF, which is then further categorised by the tagging vocabulary.

**Comment by timrobertson100** [comment]
Replaced with https://github.com/gbif/portal16/issues/60
