### ISSUE TITLE
project page table shifts columns

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#150]
projects table shifts columns. presumably when there is no values to display

![screen shot 2016-11-23 at 15 16 41](https://cloud.githubusercontent.com/assets/6759267/20564993/f56c856c-b18f-11e6-8ee5-ea742f650751.png)

**Comment by kcopas** [comment]
Those project pages look suspect to me—they're programme calls, not projects.

**Comment by MortenHofft** [comment]
> Those project pages look suspect to me—they're programme calls, not projects.
that seem to have been fixed since
I believe Burke also fixed the shifting columns. Can you please confirm and close if so @burkeker

**Comment by burkeker** [comment]
Was because the API end exposed unpublished contents. Fixed by modifying query criteria.
