### ISSUE TITLE
discrepancy between simple and advanced species search for the same name

### ISSUE THREAD

**Issue by Jegelewicz** [gbif/portal16#1509]
A simple search for Phalacropsylla shannoni (https://www.gbif.org/species/search?q=Phalacropsylla%20shannoni) returns nothing.
![image](https://user-images.githubusercontent.com/5725767/112669152-fbd5ed00-8e24-11eb-9f64-7bb51ec275d2.png)

Simply clicking "Advanced" (https://www.gbif.org/species/search?q=Phalacropsylla%20shannoni&advanced=1) reveals a name.
![image](https://user-images.githubusercontent.com/5725767/112669207-0bedcc80-8e25-11eb-944d-8da91ea3097e.png)

This is unexpected as I cannot see that any filters have changed between the simple and advanced search.

I figured out that selecting the "search across checklists" option in simple search also reveals the name in the simple search (actually, it forces me into advanced search), but it seems misleading to have this selected for me behind the scenes when doing an advanced search.

**Comment by mdoering** [comment]
I agree that _simple_ and _advanced_ are not very intuitive to understand that the searched corpus is different.
Maybe it would be better to use the terms _Backbone_ and _ChecklistBank_ for the tabs instead?

**Comment by mdoering** [comment]
It does indeed. It is just a bit apart, so it's easy to miss when you just what the tabs and results

**Comment by Jegelewicz** [comment]
> Seems like a good idea to relabel those. It does state it quite clearly already though
> 
>     You are searching for species in the GBIF taxonomy.
>     SEARCH ACROSS CHECKLISTS

As someone who is not a daily GBIF user - those terms are meaningless. How would I know the difference between "GBIF taxonomy" and "CHECKLISTS"? (In fact, I am still not sure I understand why there is a difference.)

**Comment by MortenHofft** [comment]
I would consider it outside the scope of a search page to explain what a checklist is. That isn't to say that it couldn't link to an introduction article on what the GBIF data types mean (occurrences, datasets and dataset types, publisher, nodes etc). 

@dnoesgaard let me know if you believe we have some texts that would be natural to link to.
