### ISSUE TITLE
programme page overflows

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#151]
links overflow table. they should either wrap or be clipped with ...
currently they lead to horizontal scrolling
![screen shot 2016-11-23 at 15 18 50](https://cloud.githubusercontent.com/assets/6759267/20565040/2d376f84-b190-11e6-9644-a68722fee46d.png)

**Comment by dnoesgaard** [comment]
Hey guys, did you remove links from project pages altogether? I just had one of the Living Atlases partners notice that the links they had provided weren't showing...

**Comment by MortenHofft** [comment]
> Hey guys, did you remove links from project pages altogether? 

I have created a separate issue for this. seems like it was never there. https://github.com/gbif/portal16/issues/175

**Comment by MortenHofft** [comment]
No longer relevant - there are other mobile issues, but this isn't one of them
