### ISSUE TITLE
New more flexible page type

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1517]
It has been raised that it would be useful to have a richer page type than our usual "dataUse", "news" etc.

This is an attempt to clarify what that could look like

A Contentful model could be
```
COMPOSITON:
blocks [FeatureBlock, HeaderBlock, MarkdownBlock, HeroBlock] // on or more of a list of allowed block types - these will not influence search results
title: string // for <title> element which shows on tab and will be used for search
description: string // for <description> element which shows when e.g. facebook link to the page. Also used in search.
searchable: boolean // the usual we have on all items - include in search results or not

FeatureBlock: // Based on https://github.com/gbif/portal16/issues/573#issuecomment-815785980 
title: string
features: [feature] // a list of features that will show as a block

HeaderBlock: // similar to the headers on news etc.
title
summary
primaryImage

ProseBlock:
body

HeroBlock:
image: Asset
title: string
summary: string
links: [url] ? // for action buttons?
```

That would allow for building something like below where A: HeaderBlock, B. ProseBlock and C: FeatureBlock

![composition](https://user-images.githubusercontent.com/6759267/114842665-5a193e80-9dd9-11eb-98bf-b2d39c13c661.jpg)

The main challenge with this is search. It would require a fair bit of work I think. Since the core item have no content (and we rely on that for our current approach)

**Comment by MortenHofft** [comment]
I would like to know

* Is this idea of building a page composed of blocks what we want?
* What block types do we need?
* What need are there for these pages to be found through search? We can add the option for keywords (like we have elsewhere), but the pages themselves do not have any content beyond that as they are just a set of references.

**Comment by kcopas** [comment]
Regarding search, all things being equal, I had expecting that keywords (which we already use very sparingly) would provide the means of surfacing these.

**Comment by kcopas** [comment]
My suggestion here:

Necessary blocks
* Title (required)
* Summary (not required)

* Feature bar (4x desktop | 2x tablet | 1x mobile)
    * Title (optional)
    * Prose block (optional)
    * Features (mandatory)

* Add feature strip(s)

**Comment by dnoesgaard** [comment]
Could we have some simple metadata on the core item to help search?

**Comment by MortenHofft** [comment]
We could have a normal body and summary field. It just feels a bit weird not to show it then. And it also makes for a somewhat convoluted model to have some self-referential pointer to insert `self` as a block which was the only other option I could come up with.

If you have another model in mind @dnoesgaard then please suggest it, the suggestion of mine is far from perfect. But it is fairly simple.

**Comment by dnoesgaard** [comment]
I don't know what the best solution is, search-wise, tbh.

I agree with the `composition` model that allows you to add x numbers of blocks of different types in a desired order. I like the idea that nothing is mandatory in the `composition` itself model and that you can add several blocks of same type. Would that make sense?

We can then also define new block types later on, if need be?

**Comment by MortenHofft** [comment]
The challenge is really search I think. And even if we changed the way we do search to include referred children, then it wouldn't be clear which children to include - it would be odd for example to return results based on the content of the featured articles or even their titles (since the real content of those are indexed and available elsewhere). 
The simplest solution I can come up with is keywords and a description text (which we will use for meta tags as well). I imagine that these landing pages are also more about using them in menus and direct links, than to have them appear in search.

**Comment by dnoesgaard** [comment]
Ah I think I see what you mean. Like Composition A contains a feature block with links to news item A, data use B, event C—should searches matching data use B then return composition A?

Again, I'm not sure what the best solution is—but I think we should start simple and see where we can go?

**Comment by dnoesgaard** [comment]
(happy to help try to set up the content models)

**Comment by MortenHofft** [comment]
> (happy to help try to set up the content models)

Sounds good - I've updated my suggestion above with what we have discussed in this thread. If you create the model in dev and add some test content, then I can afterwards add it to the index and create the UI

**Comment by dnoesgaard** [comment]
I've got a bare-bones model ready now with a single entry:

https://app.contentful.com/spaces/qz96qz790wh9/entries/4rxRvuCY1Zoi1UXL1ZrJol

I can't remember if the crawler needs to be updated in order to index new content types?

**Comment by dnoesgaard** [comment]
Note, I've allowed `featureBlock` to contain the same content type as the feature set on the homepage.

**Comment by MortenHofft** [comment]
Based on your content example I've implemented https://www.gbif-dev.org/composition/4rxRvuCY1Zoi1UXL1ZrJol/my-first-composition.

<img width="412" alt="Screenshot 2021-04-26 at 13 50 43" src="https://user-images.githubusercontent.com/6759267/116078129-887b0180-a696-11eb-96b6-632eb33f76cc.png">

**Hero**
I didn't include the hero type, as I wasn't sure what was intended with the fields. Could you make a mock of what you imagined? How are the links intended to be used? As highlighted action buttons?

**Comment by dnoesgaard** [comment]
For **Hero**, perhaps something like this?

![hero_block](https://user-images.githubusercontent.com/21358085/116200593-d0526500-a738-11eb-8244-5da5b84d3af4.png)

Perhaps we don't need two text fields and I guess only one link really makes sense?

We could also add a left/right switch for the text block?

Thoughts?

**Comment by dnoesgaard** [comment]
Btw, the implementation looks great and works like a charm!

**Comment by kcopas** [comment]
yeah, super to see this progress @MortenHofft !

**Comment by MortenHofft** [comment]
@dnoesgaard so when you say Hero you do not mean those full width background images with some floating text?
In the above example it looks like it is an image with same width as the text - so it appear almost like an inline images?

**Comment by dnoesgaard** [comment]
Yeah, it looks like that because that's how I did the mock-up. But I'm actually not quite sure about the width of the image.

@kcopas?

**Comment by MortenHofft** [comment]
I also noticed that the hero in the contentful item is placed mid page. I would normally think of a hero as a header. It can be used elsewhere of course, but then the header is typically at least as heroic I would think? So before implementing anything, it would be nice to have it clarified.

**Comment by dnoesgaard** [comment]
Please ignore the placement. The mock-up was just to illustrate the floating text and call-to-action button.

**Comment by kcopas** [comment]
Maybe "hero" is the wrong name here. I think the true hero is the image that goes with the header block (full-width for available viewport).

Daniel's mock-up aligns with what I had in mind for being able to provide some visual variety and relief (as well as secondary emphasis—an image masquerading as h2/h3, if you will) to a composition page made up largely of multiple feature blocks. Making it clickable reinforces its utility in such a setting…

**Comment by MortenHofft** [comment]
I've updated the page https://www.gbif-dev.org/composition/4rxRvuCY1Zoi1UXL1ZrJol/my-first-composition2

It just uses the feature row and adjust the layout depending on the number of features added per row.
For smaller devices it just stacks it all and for mobile it removes images (hoping that it will load faster)

<img width="407" alt="Screenshot 2021-04-28 at 12 33 02" src="https://user-images.githubusercontent.com/6759267/116390416-4a104e80-a81e-11eb-8d28-c6b81190d670.png">

**Comment by kcopas** [comment]
@MortenHofft this looks fantastic! So, reading between the lines in contentful, the way you've added greater flexibility is by keying the various display modes based on whether there are 1, 2, 3 or 4 features in the feature block—is that right?

Can't wait to field test it (but I have to)…

**Comment by MortenHofft** [comment]
Yes - so a feature block should contain 1-4 items. And it just show them on one line (styling them a bit differently depending on count). If on a  tablet then 4 items is wrapped to 2x2. If mobile then it is all just a stacked list.

**Other types**
That doesn't mean we couldn't have more types. E.g. another semi-full-width-hero-like-card with more options (say link buttons and left/right switch as @dnoesgaard mentioned)

@kcopas you also mentioned the desire to have image only and text only. If that is still the case, then we need to change the content model as image and title is both required for features. @dnoesgaard could you add a new contentType or relax the constraints on the existing Feature contentType depending on what you prefer?

**Comment by dnoesgaard** [comment]
This is awesome!

- I noticed that you *can* have more than 4 features in a feature block—the UI simply adds another row. Should we keep this? Or should I restrict `featureBlock` to 1-4 features?
- I'll wait for @kcopas to elaborate before changing anything. Image/text only could easily be done in `textblock`?
- Seeing the `featureBlock` with a single full-width feature, I'd love to have some flexibility in regards to the floating text, i.e. width and alignment. Ideas?

**Comment by dnoesgaard** [comment]
Another small thing: I think we still wanted the option for Summary to be shown in `headerblock`, right @kcopas?

**Comment by kcopas** [comment]
> Another small thing: I think we still wanted the option for Summary to be shown in headerblock, right @kcopas?

Yes, please.

**Comment by MortenHofft** [comment]
The field has been renamed in the Contentful model it seems (it used to be `description` unlike the usual `summary`). I've update the code accordingly.

**Comment by dnoesgaard** [comment]
Have we used `description` previously?

**Comment by MortenHofft** [comment]
I think so. I can see in my code that I have renamed a standard component from summary to description. But I might have lost my mind. But I guess that is what the dev environment is for.

**Comment by dnoesgaard** [comment]
I'd like to propose that we merge this and deploy to prod. It's gone from dev and we're probably going to have to start using it with real content for us to be able to iron out any other kinks and make further developments. Being a new content type, it shouldn't affect any existing content either.

@MortenHofft, what do you think? I can start copying over the content model in Contentful...

**Comment by MortenHofft** [comment]
If you are happy with it, then yes please port to prod cms. thank you.

**Comment by dnoesgaard** [comment]
Done.

test entry: 
https://app.contentful.com/spaces/uo17ejk9rkwj/entries/3fvWSwDCj8tZBpRFiWC8QQ
https://www.gbif.org/composition/3fvWSwDCj8tZBpRFiWC8QQ

**Comment by MortenHofft** [comment]
in prod, uat and staging. If the need for changes appear, then feel free to create a new issue.
