### ISSUE TITLE
docs: new occurrence filter - modified

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1533]
We should add the new field to the documentation. This is related to issue https://github.com/gbif/occurrence/issues/219
NB: the filter is currently only in dev environment

**Comment by DanBIF** [comment]
Arter.dk is looking so much forward to seeing this in prod. to see updates in our big Naturdatabase. By the way - the ministry announced us officially today (TV2 Go'morgen Danmark and again tonight and more during this week).

**Comment by michaelrangstrup** [comment]
@MortenHofft @thomasstjerne this sounds promising. What is the appx. ETA of seeing this one in Production do you think?

**Comment by michaelrangstrup** [comment]
@thomasstjerne brilliant!!!! Thanks so much!
