### ISSUE TITLE
GRSciColl - link to the registry for suggest a change

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal16#1555]
Now that we will have the new "suggest a change" feature in the registry, we should make sure that people can access it from the portal.
Right now on https://www.gbif.org/grscicoll, there is a generic "suggest a change" button that sends me an email and a "suggest a change" link on each page that either sends me an email or link to IH.

I think we need the following:

1. a way for people to suggest adding a collection or an institution (link to those pages: https://registry.gbif.org/institution/create and https://registry.gbif.org/collection/create). This could be instead of the generic button for example (and perhaps also available from each entry page?).
2. a way for people to update a specific entry. In other words, a link to the registry page of a specific entry. I think this should be replacing the link available on the GBIF.org institution/collection pages. We should keep the link to IH for IH records.
3. we should make it clear to users that they can suggest deletions, merges or convert institutions to collections
4. for staff update, I guess they will still have to email me so on the staff pages, we should probably leave the email.

**Comment by MortenHofft** [comment]
This implementation should be changed. See https://github.com/gbif/portal-feedback/issues/3910
