### ISSUE TITLE
resources are not searchable by language

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#156]
Working on an easy to access previous Gbits newsletters, I noticed that these resources aren't searchable by language despite having the information available, e.g.

http://demo.gbif.org/cms/search?q=gbits&type=document

![search_and_inbox__43_messages_](https://cloud.githubusercontent.com/assets/21358085/20703774/562e4610-b61d-11e6-8bd2-37c7c30c5640.png)

![gbits_newsletter_no__46__chinese__simplified_](https://cloud.githubusercontent.com/assets/21358085/20703786/618cf42a-b61d-11e6-8d10-713719349ac6.png)

(perhaps relates to #99 ?)

Not sure where in the hierarchy of issues this quite belong, so I'd appreciate if you could squeeze it in where it belongs, @timrobertson100. Thanks!

**Comment by burkeker** [comment]
Thanks for raising. Resources have been mapped to core language properties in the latest deployment.
