### ISSUE TITLE
Directory of contacts - a few issues from Admin

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#157]
Admin has raised a few issues in the directory:

- [ ] in Nodes committee, non-chair members should be listed in the capacity of Node managers, not Nodes Regional Representatives
- [ ] some members have no role:
Endresen, Dag Terje Filip
Krishtalka, Leonard
Chettri, Nakul
Akampurira, Innocent
Holetschek, Jörg
Berendsohn, Walter
Wheeler, Ben
- [ ] can vacant seats on committees  be displayed?

**Comment by dnoesgaard** [comment]
(@kcopas, just fyi...)

**Comment by kcopas** [comment]
Logging a request for adjustment/refinement of the same page, please—

In the [list of the Secretariat contacts](https://demo.gbif.org/directory/contact-us#gbif_secretariat), can we please cluster an initial view/sort that shows DH at the top, followed by the four heads of groups (alpha order of last name? Hahn, Hirsch, Nielsen, Robertson) and then an alphabetical listing of all other staff?

Don't know whether updating titles in the directory will update the current display to this or whether other adjustments are in order, but given that I've consulted DH and TH on this, it would be good to implement this for v1.

**Comment by burkeker** [comment]
The missing roles looks like content issue to me. Correct me if I am wrong.

As to sorting, @MortenHofft & @cgendreau is it better to have that done from the report endpoint, or to sort them at the Express end?

**Comment by MortenHofft** [comment]
>The missing roles looks like content issue to me. Correct me if I am wrong.

I would assume the same, but cannot say without looking in the Directory. And no access from here.

> As to sorting, is it better to have that done from the report endpoint, or to sort them at the Express end?

How does it work now? They are already sorted it seem? The first is Donald, Anne mette and Tim R. then alpha. So someone somewhere is doing a custom sort i would guess. I would suggest updating that to reflect Hahn and Hirsh. And if you aren't sorting it in express Burke, then Christian is sorting already (unless the alphabetical ordering is by chance).

**Comment by cgendreau** [comment]
There is a sort in the backend but I can't remember at which level exactly.

**Comment by dnoesgaard** [comment]
> The missing roles looks like content issue to me. Correct me if I am wrong.

take Dag Endresen for example. He's the node manager of Norway, and listed as such in the directory: http://directory.gbif.org/#/people/74

He, however, has no role in the Nodes committee section of the directory of contacts page.

**Comment by cgendreau** [comment]
I fixed the Secretariat contacts order.
For the missing roles I can confirm the Directory API returns the expected result so it should not be a data issue. They all seem to have links with node AND participant (or GBIF role) so I would have a look at the "de-duplication" code in the frontend.

**Comment by kbraak** [comment]
@MortenHofft IMHO this issue should be labelled as a release blocker. Showing the correct role for contacts in our network is fundamental.

**Comment by MortenHofft** [comment]
this page have been reimplemented. Admin has approved that the issues has been fixed
