### ISSUE TITLE
Cookie consent - add a reject option

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1591]
Currently it isn't possible to reject cookies. only to accept. If the user do not accept then we do not add any analytics, but the popup remains until the user accepts.

@ManonGros asks for this to be changed (on behalf of a user). @MattBlissett says that what we do is illegal.

@kcopas Do you have any concerns with us adding a "reject" similar to what we do for the hosted portals?

@MattBlissett is it correctly understood that this is what you propose?

**Comment by kcopas** [comment]
Yes, @MattBlissett is correct—I'm usually logged in and so forget this is how it's functioned, but when I have seen it, I've had the same thought. My only concerns are for leaving it as is.

**Comment by MattBlissett** [comment]
You can see the current behaviour by opening https://www.gbif.org/ in a private window.

As well as a reject button, the current wording would need to be changed. Now:

> GBIF uses cookies and the like for the purposes of statistical analysis, improving the friendliness and usability of our website, tailoring content to your interests and engaging with social media. By visiting our website, you consent to our and third party use of cookies as described in our privacy and cookie policy.

Perhaps (influenced by the hosted portals text):

> GBIF uses cookies and similar technologies for the purposes of statistical analysis, improving the friendliness and usability of our website, tailoring content to your interests and engaging with social media. You may decline non-essential cookies by selecting “Reject”. Please see our [privacy policy](https://www.gbif.org/terms/privacy-policy) for further information.
