### ISSUE TITLE
Adjust date display on non-data pages

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#163]
Placement of a dateline above the title works on news and featured data use pages, but I'm continuing to find our use of it on other generic pages problematic. 

I can see showing the last-modified date, but probably placed in a footer to let the user know, well, when the page was last updated. Date created, though, is really not meaningful on these pages. Most of them were created on 14 Oct, apparently, but none of the content dates to that vintage anyway.

**Comment by MortenHofft** [comment]
Yes that doesn't sound like it works. I must admit that I liked the idea, but if the content doesn't support it (in that creation date is meaningless), then we shouldn't do it. And you are right, that for generic pages it probably isn't that interesting anyhow. Hm, what to do then. @burkeker has implemented a way to edit that in Drupal, but without us agreeing on some guidelines for what the principles are, then it will just lead to chaos I imagine.

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/portal16/issues/253

**Comment by MortenHofft** [comment]
articles no longer have dates
