### ISSUE TITLE
GRSciColl - update UI to accommodate new contact model

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal16#1636]
The new contact model is now implemented: gbif/registry#379 (comment)

We need to show the new contacts on the GRSciColl pages.

Right now there are 2 fields in collections and institutions (in the API):

contacts -> old model
contactPersons -> new model

the same for the endpoints, e.g.: https://api.gbif.org/v1/grscicoll/institution/a2e50ff3-62ae-419a-8749-455342e0b455/contactPerson

The IH synch will only update the contacts under the new model.

**Comment by ManonGros** [comment]
@MortenHofft I think the portal might still be displaying the old contact, see this example:
https://www.gbif.org/grscicoll/institution/79adfa73-4a2e-4b3b-9e2c-4aa83e05d2b8
https://registry.gbif.org/institution/79adfa73-4a2e-4b3b-9e2c-4aa83e05d2b8/contact

**Comment by ManonGros** [comment]
I don't know if this is related but I think the portal might still display the old contacts (reported by one of our users):
https://www.gbif.org/grscicoll/institution/442fa096-b2bf-4ecc-b513-ae0958eeec25
https://registry.gbif.org/institution/442fa096-b2bf-4ecc-b513-ae0958eeec25/contact

**Comment by MortenHofft** [comment]
Yes that is the same issue: that the API has been changed and so the website shows stale content. This was the same issue that we recently addressed when rewriting the registry-console.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/93ad21aa2481beb40b68e046240d13eb993b2a4a
