### ISSUE TITLE
check if image is avaiable before printing it on programme pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#164]
If there is no images, then don't print them at:
https://demo.gbif-dev.org/programme/living-atlases
The problem seem to be that there is no image url and no check

![screen shot 2016-12-06 at 08 32 32](https://cloud.githubusercontent.com/assets/6759267/20916929/c5ad3cc8-bb8e-11e6-9c6d-85755d5fd04e.png)

**Comment by burkeker** [comment]
Fixed as https://github.com/gbif/portal16/commit/5d3a151369e92dbfd601cd264dead21f554bcd0f
