### ISSUE TITLE
Document geodistance filter and predicate

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1643]
The developer docs for the API don't describe the geodistance search.

Example search filter: https://api.gbif.org/v1/occurrence/search?geoDistance=90,100,5km (lat,lng, distance)
 
Predicate:
{
  "creator":"...",
  "notification_addresses": ["..."],
  "send_notification":"true",
  "format": "DWCA",
  "predicate":
  {
    "type":"geoDistance",
    "latitude":"90",
    "longitude":"100",
    "distance":"5km"
  }
}

**Comment by MattBlissett** [comment]
`geoDistance` is documented on the new technical documentation site for both searches and downloads.

https://techdocs.gbif.org/
