### ISSUE TITLE
image cropping

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#165]
Reported by Dmitry S. Schigel

FYI I noticed that rectangular images become square in the new search results, compare http://demo.gbif.org/search?q=PLAZI “LAZI” image with the original, also trimmed but less http://demo.gbif.org/news/page/82100, where both links to Plazi are their-end 404s, should probably go to http://plazi.org/about/about-plazi/. The images that should possibly fit, not fill the boxes in the search results?

**Comment by MortenHofft** [comment]
Hi Dmitry

**images**
I see the problem but I'm not sure what the best solution is. But I'm inclined to say that article header images shouldn't be that sensitive to cropping. It makes it very difficult to use the images and the result would be that we wouldn't be showing them. If there is a need to show Plazi's logo it should probably be an image inline in the article. @kcopas and @dnoesgaard would you find that terribly limiting? An alternative could be: upload images in whatever ratio and we will never crop, but that will be difficult to show in a nice consistent way I believe.

**Dead links**
As for the dead links that will happen with old articles. Links change. There is no way around it. If you go to a 2 year old BBC article and click a link to an external site it is also likely to be a 404. If we see it as a large problem, we can test all links programmatically and someone could be assign the task of updating links when they broke. For high visibility pages that might make sense, but less so for old articles I would think.

**Comment by kcopas** [comment]
It is a two-year-old news item that lacked any obvious photographic content, so the logo was used. We're only just learning how best to use the current implementation of photos, and I don't want to base ANY design decisions or adjustments on something like this.

I'm not crazy about having to edit old news either, except in the most urgent circumstances.

**Comment by dnoesgaard** [comment]
I agree with everything said here. I for one am very happy with the use of images on the new site. Takes getting used to, but the result is good. IMO this issue can be closed...

**Comment by MortenHofft** [comment]
let's close then. Going forward I suggest we try to avoid using "crop-sensitive-images" as hero images. No matter the design we land on in the next 4 years it seem nice to have flexibility with image displayment. For images inside articles we can have all manners of fixed ratios.
