### ISSUE TITLE
Classification browser fails if Google Analytics is disabled/blocked

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1666]
The classification browser on https://www.gbif.org/species/4 fails if Google Analytics is rejected, `Error: ga is not defined`.

I hadn't noticed this when using UBlock, which is odd, only when pressing "Reject" on the terms.

**Comment by MortenHofft** [comment]
ahhh, makes sense actually. The event tracker doesn't properly check that GA is present.
