### ISSUE TITLE
resource URL not exposed in resources

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#167]
I would very much like the Resource URL to be shown on resources :)

![imarine_gateway__data_e-infrastructure_initiative_for_fisheries_management_and_conservation_of_marine_living_resources_and_imarine_gateway__data_e-infrastructure_initiative_for_fisheries_management_and_conservation_of_marine_living_resource](https://cloud.githubusercontent.com/assets/21358085/20969456/54d97f92-bc89-11e6-9071-1a55123cf958.png)

**Comment by burkeker** [comment]
Fixed as https://github.com/gbif/portal16/commit/7e5389c8876f279b5a74d11f2bc4470379924702.

**Comment by dnoesgaard** [comment]
It appears that there's a small typo in the link text

> Go to resourcee

(extra "e")
