### ISSUE TITLE
Handle DWC changes to Basis of Record, including Material Citation

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1678]
The two existing bases of records Literature and Unknown will no longer be used, but they will continue to exist in the API for backward compatibility -- we need to handle existing downloads using these values in their filters. Ideally, these should be hidden from the search filter list and from the map filter list.

Material Citation will be added to the enumeration, and occurrences that previously were parsed to Literature will parse instead to Material Citation.  I think "Recorded in X" is appropriate for the top of the occurrence page.

Pipelines issue: https://github.com/gbif/pipelines/issues/635

**Comment by MortenHofft** [comment]
You also mentioned that a new type called `Occurrence` would be added. Is this correct please.

So the new list (active) is
* "OBSERVATION",
* "MACHINE_OBSERVATION",
* "HUMAN_OBSERVATION",
* "MATERIAL_SAMPLE",
* "MATERIAL_CITATION",
* "PRESERVED_SPECIMEN",
* "FOSSIL_SPECIMEN",
* "LIVING_SPECIMEN",
* "OCCURRENCE"

And then we have LITERATURE and UNKNOWN as deprecated values that need support. Where support mean old downloads will show these values in the predicates. But the values will NOT appear on individual interpreted occurrences not in the occurrence index?

**Comment by MattBlissett** [comment]
Also `Occurrence`, yes.

> And then we have LITERATURE and UNKNOWN as deprecated values that need support. Where support mean old downloads will show these values in the predicates. But the values will NOT appear on individual interpreted occurrences not in the occurrence index?

Correct.

**Comment by MortenHofft** [comment]
Thank you. These are the changes that I believe are required

**portal16**
* [ ] translations should be added, but none removed as they will appear in downloads
* [ ] enumeration list should be changed to only include currently supported (those that we force values into in the index)

**gbif-web**
* [ ] graphql schema should be updated
* [ ] react-components should have added translations (same as portal16)
* [ ] react-components should have new set of enums (same as portal16)

**registry**
There shouldn't be any usage here as we do not deal with individual occurrences
