### ISSUE TITLE
Using search to present "curated" groups of tools

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#169]
Problem: I want to do a search that pulls of a set of tools that don't necessarily have anything in common (except that I want to group them and present them together).

I thought about using "purpose" to group them, but it appears we're not exposing that facet for tools. So any other suggestions? Can I add a unique tag and search by that?

(ping @burkeker + @MortenHofft)

**Comment by MortenHofft** [comment]
hmm - what is the use case? if they really do not have anything in common then when do you want to present them together?
There are already a lot of tag types in use for tools. Seems wrong to introduce yet another one unless there is good reasons to do so. Is this for internal or external usage?

My initial suggestion would be to use the topics tag. But that of course assumes that they do in fact share one or more topics :)

what you say @burkeker You are our in house tagging expert

**Comment by dnoesgaard** [comment]
My use case was that we wanted to provide a list of tools for collection management / digitization, and rather than having to make a generic content page, I'd rather curate it by using a search and linking to it.

**Comment by burkeker** [comment]
http://www.gbif.org/resources?f[0]=gr_resource_type%3A1010&f[1]=gr_purpose%3A871&searched=1

So we may just expose the purpose facet again. @timrobertson100 has opinion about having too many facets on the content search - a bit overwhelming for visitors. Guess we need to find other ways to consolidate them.

**Comment by MortenHofft** [comment]
purpose is already exposed right?
![screen shot 2017-01-04 at 12 24 03](https://cloud.githubusercontent.com/assets/6759267/21640926/b60a7f14-d278-11e6-9c7a-7957f6203ec3.png)

**Comment by dnoesgaard** [comment]
Purpose isn't exposed when type=tool.

Anyway I don't know. But we can leave this one for now and focus on other things. I'll keep thinking of what might be a solution that would make sense.

**Comment by MortenHofft** [comment]
Hi Daniel - things have changed a lot since. I'm closing this one. please reopen if needed.
