### ISSUE TITLE
Improve occurrence tombstone page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1699]
The tombstone page for occurrences that have been deleted can be improved by showing the last fragment.

I suggest it make a call to https://api.gbif.org/v1/occurrence/N/fragment and if it returns 2xx show something like "This record existed but has been deleted by the publisher. To aid diagnostics, the last available view of this record is shown: <json/xml etc>"

Future improvements could be to try and determine if we can confidently redirect, but adding this already would be easy and helpful.

**Comment by timrobertson100** [comment]
@MortenHofft 

- UAT DwC-A example [web](https://www.gbif-uat.org/occurrence/1270725256) and [json](https://api.gbif-uat.org/v1/occurrence/1270725256/fragment)
- UAT BioCASe example [web](https://www.gbif-uat.org/occurrence/142316222) and [xml](https://api.gbif-uat.org/v1/occurrence/142316222/fragment)

**Comment by dshorthouse** [comment]
This will be really helpful to sanity check attempted re-mappings at my end from one gbifID to another. Here's a recent one in what I call the "administrivia" bucket:

https://www.gbif.org/occurrence/3461476140
https://api.gbif.org/v1/occurrence/1087520255/fragment

**Comment by MortenHofft** [comment]
There are now a basic tombstone page.
 
E.g. https://www.gbif.org/occurrence/1087520255

The most obvious improvement would be to suggest occurrences that *might* have replaced the lost one. Ideally driven from the APIs. Something along:
```
[Same recordNumber and recordedBy: 1 result] 
[Same scientificName and catalogNumber: 2 results]
```

**Comment by dshorthouse** [comment]
I notice that:

`curl -I https://www.gbif.org/occurrence/1087520255`

...produces a `HTTP/2 302`, with a `location: /occurrence/1087520255/fragment`.

And the location:

`curl -I https://www.gbif.org/occurrence/1087520255/fragment`
 
...then produces a `HTTP/2 200`.

We're in grey territory here, but might that first response be better represented as a `303`?

From RFC 7232, https://datatracker.ietf.org/doc/html/rfc7231#section-6.4.4

> A 303 response to a GET request indicates that the origin server does
>   not have a representation of the target resource that can be
>   transferred by the server over HTTP.  However, the Location field
>   value refers to a resource that is descriptive of the target
>   resource, such that making a retrieval request on that other resource
>   might result in a representation that is useful to recipients without
>   implying that it represents the original target resource.
