### ISSUE TITLE
Revise homepage: Iteration 1

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#17]
Hold a requirements capture session with DH, KC and TH and revise the page to reflect their first thoughts.

This is likely to require several iterations and therefore anticipate this will all change.

**Comment by MortenHofft** [comment]
requirements capture is done, and home page stripped to minimum. implementing a crude version is next step

**Comment by timrobertson100** [comment]
The current unstyled homepage satisfies the goal of the milestone.
