### ISSUE TITLE
In Carousel Blocks, move image caption to tooltip

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1706]
To make the carousel cards align more smoothly can we move the image caption (description) into a tooltip, revealed when hovering over image?

**Comment by javiesgm** [comment]
I think maybe something like this? 

https://xd.adobe.com/view/ec87d785-eea2-40d8-b6bb-aec13e5a9436-b9d4/

**Comment by dnoesgaard** [comment]
Has this been deployed anywhere yet? I'd like to see it action :)

**Comment by MortenHofft** [comment]
This might partly fix the issue that the arrows jump up and down. But they will still do in some cases. Perhaps just fix there position relative to the top instead? E.g. 100px down?

**Comment by javiesgm** [comment]
Let's try it

**Comment by dnoesgaard** [comment]
Awesome, this is great.

I don't know the best way to solve the jumping arrow issue. We could also position them on either side of the dots? Not sure if that would work...

**Comment by javiesgm** [comment]
Maybe to solve the jumping-arrow issue they could be position-fixed to the image instead of the whole box?

**Comment by MortenHofft** [comment]
> Maybe to solve the jumping-arrow issue they could be position-fixed to the image instead of the whole box?

The images can have different sizes. So that wouldn't help as far as I can see.

**Comment by MortenHofft** [comment]
> Let's try it

I've changed it. But I would think it was easier to test this in drawings than having to do a code release to test it.

**Comment by dnoesgaard** [comment]
@javiesgm can you figure out what a good value would be?

(I still that a simpler solution would be to position the arrows on either side of the dots.)

Or—another idea could be to lock the dimensions of the block and then dynamically adjust font-size of body text to fit (if too much text). Not at all sure if this something that can be done, but just a thought.

**Comment by javiesgm** [comment]
> You can see it in staging env
> 
> This might partly fix the issue that the arrows jump up and down. But they will still do in some cases. Perhaps just fix their position relative to the top instead? E.g. 100px down?

I meant, let's try this

**Comment by javiesgm** [comment]
I think the tooltip looks perfect. As for the arrows, I think a fixed value of 160px could work.

**Comment by dnoesgaard** [comment]
Hey Morten, as mentioned in our talk, I'd like to roll back to the having the arrows aligned to the center rather than fixed to 
 xx pixels from the top. The tooltip captions are great so please go ahead and merge that to master and build to prod at your leisure.

Moving forward, we'll put some more effort into defining constraints for the models to work with all kinds of content. Thanks for your help!

**Comment by MortenHofft** [comment]
FYI: I've just looked at a bunch of carousel usages in real world. They all fix the height to be the same. 

In the the current design, that can be achieved my uploading images with the same size (e.g. rounded as in the mocks) and make sure the text isn't very long (as in the mocks). Then the height will remain the same for all carousel elements.
