### ISSUE TITLE
Super Text Block?

### ISSUE THREAD

**Issue by javiesgm** [gbif/portal16#1710]
When reviewing the proposed mockups for the thematic landing pages, I noticed that the text size is different from the "body" of the current text block. 

For reference:
https://drive.google.com/open?id=1d5dp-bPJi2e9qRNegCZdZRMKRNLxamdS&authuser=jgamboa%40gbif.org&usp=drive_fs

We need a block to include text in a single column that looks the same as the carrousel and media block with the ability to change the background to an image or different colors.  

In this sense, I do not know if the most convenient is to include more options in the current text block: +text size, +include background image, +change background color, +change text color. 

Or, create a new block called featured text block that allows us to include this type of options. 

The proposed text size is the same as the carrousel block and the media block: text-size: 16px, line-height: 1.8em. Color options: current color: #4e565f and white: #f1f1f1. Background color: include black (#333333) to the current 3 colors available. 

If it is just an image, it would be amazing to be able to define its height.

**Comment by javiesgm** [comment]
Here it is 
[text-img block.pdf](https://github.com/gbif/portal16/files/8176726/text-img.block.pdf)

**Comment by MortenHofft** [comment]
Examples from the file

<img width="1173" alt="Screenshot 2022-03-03 at 10 58 33" src="https://user-images.githubusercontent.com/6759267/156541462-d50d0030-f41e-46bd-8c4e-2a3764eddf88.png">
<img width="1171" alt="Screenshot 2022-03-03 at 10 58 24" src="https://user-images.githubusercontent.com/6759267/156541477-afaeb37a-63c4-4ccb-a195-bb7839d8a621.png">

Some text is centered. Other top aligned. Is that an additional setting?

**Comment by javiesgm** [comment]
Yep

**Comment by javiesgm** [comment]
Home Text-size updated:
![Home – Health – 4](https://user-images.githubusercontent.com/14220404/156541935-8dc7a96c-9ac9-40bb-963a-a031366d1c06.png)

**Comment by javiesgm** [comment]
Mobile version:
![Home – Health – 3](https://user-images.githubusercontent.com/14220404/156542044-c52bacb5-84d4-4d6e-812e-1c0b61f2ecd4.png)

**Comment by MortenHofft** [comment]
The majority of the images above isn't about this issue - right?

**Comment by javiesgm** [comment]
Not directly related. The image block we talked about is different

**Comment by javiesgm** [comment]
Please remove the custom style field from this block. 

CSS for text should be: 
text-size: 16px
line-height: 1.6em
font-weight: 400

**Comment by MortenHofft** [comment]
I've added the style above (except changing text-size to font-size). If you no longer want the `style` field in Contentful then feel free to remove it from the model. The website supports it for now, but do not require it, so it can safely be removed from contentful.

**Comment by javiesgm** [comment]
Ups. font-size! 

And I forgot, but can you include a margin-bottom for text as you had done for the traditional "Text block."

.body-text--markdown p {
margin-bottom: 1.5em;
