### ISSUE TITLE
Carrousel block fine tuning for composition pages in GBIF.org

### ISSUE THREAD

**Issue by javiesgm** [gbif/portal16#1714]
Fine-tuning to Carrousel block includes adjustments to padding and fonts styling for different screen sizes. I include this .pdf file hoping it clarifies the full extent of the changes. 

[carrousel block - ft.pdf](https://github.com/gbif/portal16/files/8264930/carrousel.block.-.ft.pdf)

**Comment by MortenHofft** [comment]
I'm not sure I got all changes included. It is a bit difficult to know what the changes are, and going through all margins again is fairly time consuming, so I just estimated which looked to be changed.
