### ISSUE TITLE
Feature block font size and styling

### ISSUE THREAD

**Issue by javiesgm** [gbif/portal16#1718]
The last adjustment for this block is: 

font-size: 16px
line-height: 1.6em
font-weight for titles: 500
font-weight for descriptions: 400

Please leave the margins and padding as they are.

**Comment by javiesgm** [comment]
I also noticed that the font-size used for the content placed on the "body" field remains 18px and not 16px.
<img width="1262" alt="Screenshot 2022-03-17 at 14 51 14" src="https://user-images.githubusercontent.com/14220404/158823994-ebc7c5df-0977-406f-aa91-49df54aa4a76.png">

**Comment by javiesgm** [comment]
Hey Morten, the body content should have these parameters: 
font-size: 16px
line-height: 1.6em
font-weight for titles: 500
font-weight for descriptions: 400 

It remains at font-size 18
<img width="1453" alt="Screenshot 2022-06-23 at 10 09 23" src="https://user-images.githubusercontent.com/14220404/175249745-bec581ca-c760-45e7-9256-f331cc802b5d.png">

Markdown formatting is also missing. For example, lists don't show the dots or numbers.

**Comment by MortenHofft** [comment]
Thanks Javier - The style for all those blocks vary quite a lot, but for some I started using the same classes to simplify life. But originally they  were all different in the design so they had different classes. I might have introduced some bugs in my attempt to streamline it. I have aligned classes, but in the past we had font size 18 for some body text and 16 for other. That might have been lost. Please just create an issue if I have messed things up with my attempt to simplify it a bit.

**Comment by javiesgm** [comment]
Thank you, Morten! And yes, you are right. During several revisions, while developing these blocks, I moved back from 18px to 16px.

**Comment by MortenHofft** [comment]
No worries, it should be on prod now. Let me know if it looks wrong

**Comment by javiesgm** [comment]
The only thing I see is that the line height remains at 32px. Could you please update it to 1.6em? 
And that's it! 💪

**Comment by MortenHofft** [comment]
I will do so, but I will do so to the class that applies to most if not all of those blocks and their descriptions. Let me know if you want this block to be different from the rest.

**Comment by javiesgm** [comment]
Ok. I think a line-height of 1.6em works on all of the different block descriptions. 🤞
