### ISSUE TITLE
GRSciColl - collection doesn't display contacts

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal16#1724]
This collections has two contacts in the registry: https://registry.gbif.org/collection/3550b9ce-ab18-4a26-9207-aeb0947ad948
but they aren't displayed on GBIF.org: https://www.gbif.org/grscicoll/collection/3550b9ce-ab18-4a26-9207-aeb0947ad948

**Comment by MortenHofft** [comment]
I have no idea how I could be so silly, but apparently I only updated institutions to the new contact API. I have fixed that. Sorry

```
  .-'---`-.
,'          `.
|             \
|              \
\           _  \
,\  _    ,'-,/-)\
( * \ \,' ,' ,'-)
 `._,)     -',-')
   \/         ''/
    )        / /
   /       ,'-'

```
