### ISSUE TITLE
previous/next story should always be internal links

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#173]
On https://demo.gbif.org/news/newsroom/news/bid-2015-africa-call-for-full-proposals
When clicking previous story the link leads to the BID site. That is confusing. I suggest that those links should always be internal links to the site itself.

**Comment by burkeker** [comment]
This is intended by the comms team, after the launch of the BID site the news items of relevant announcements had their URL redirects set up to point to the BID site. I am tagging @kcopas and @dnoesgaard here. Please feel free to re-open this if there is anything I can help to address.
