### ISSUE TITLE
Page for monthly snapshot DOIs and links

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1730]
Every month GBIF prepares several formats of export, one of which is made available in MS Azure, AWS, and GCS (soon to be Google Big Query too).

We need a page we can refer to that provides the listing of exports, driven from the registry API (same as user downloads API call, but for the account making the monthly downloads). I've spoken with @dnoesgaard and he can provide the final text, but the page can start with the following (please make the sections with an anchor to ease the links):

# Occurrence Snapshots 
_Periodic exports of GBIF occurrence data_  

Every month GBIF takes a full occurrence snapshot, saved in different formats to ease usage. All snapshots are issued with a DOI to simplify citation, and some formats are copied to public clouds for easy use on those environments.

## Cloud-based datasets

GBIF makes data available on the [Microsoft Planetary Computer (Azure)](https://planetarycomputer.microsoft.com/dataset/gbif), as an [Amazon AWS Open Dataset](https://registry.opendata.aws/gbif/) and on a public Google GCS bucket (`gs://public-datasets-gbif/occurrence`).

When using cloud-based snapshots, we always recommend creating a [Derived Dataset citation](https://www.gbif.org/citation-guidelines#derivedDatasets) for the records that you use. When referring to the full dataset, the citation format the citation format is: 

> GBIF Occurrence Data https://doi.org/10.15468/xxxxx

The following table provides the DOIs for each month:

| Date           | Format         | Citation                                               |
|---------------------|--------------|---------------------------------------------------|
| 2022-01-01 | `parquet` | GBIF Occurrence Data https://doi.org/10.15468/xxxxx          |
| 2022-02-01 | `parquet` | GBIF Occurrence Data https://doi.org/10.15468/xxxxx          |

## Monthly snapshot datasets 

The monthly exports of GBIF are listed below.

| Date           | Format         | DOI                                               |
|---------------------|--------------|---------------------------------------------------|
| 2022-01-01 | `parquet` | https://doi.org/10.15468/xxxxx          |
| 2022-02-01 | `avro` | https://doi.org/10.15468/xxxxx          |

**Comment by MattBlissett** [comment]
The query is `https://api.gbif.org/v1/occurrence/download/user/download.gbif.org?status=SUCCEEDED`, it needs authentication.  Only the `status` filter is supported: https://github.com/gbif/registry/blob/master/registry-ws/src/main/java/org/gbif/registry/ws/resources/OccurrenceDownloadResource.java#L200-L216

**Comment by MortenHofft** [comment]
Can this issue be closed? https://www.gbif.org/occurrence-snapshots

**Comment by timrobertson100** [comment]
I was also confused by this today - reopening as I think @dnoesgaard suggestion (or something similar) is needed
