### ISSUE TITLE
Citation widget failing

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1756]
[This](https://www.gbif.org/api/widgets/literature/latest?gbifDatasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7) works but the [same URL](https://www.gbif.org/api/widgets/literature/latest?gbifDatasetKey=4bfac3ea-8763-4f4b-a71a-76a6f5f243d3) with a different dataset key is giving 500. The API [appears to work](https://api.gbif.org/v1/literature/search?gbifDatasetKey=4bfac3ea-8763-4f4b-a71a-76a6f5f243d3)

The publisher has written to helpdesk

**Comment by timrobertson100** [comment]
Logs show 

```
Template render error: (/var/www/portal16/app/views/widgets/literature/latest.nunjucks) [Line 171, Column 47]
  Error: Unable to call `result["authors"]["slice"]`, which is undefined or falsey
    at Object.exports.prettifyError (/var/www/portal16/node_modules/nunjucks/src/lib.js:34:15)
    at /var/www/portal16/node_modules/nunjucks/src/environment.js:486:31
```

**Comment by MortenHofft** [comment]
Works now. Apparently we rarely have papers without authors so it was never detected that is fails without. Looks fine now:
https://www.gbif-staging.org/api/widgets/literature/latest?gbifDatasetKey=4bfac3ea-8763-4f4b-a71a-76a6f5f243d3
