### ISSUE TITLE
invalid lock file

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1760]
https://github.com/gbif/portal16/commit/9267479e9b92668fe8dd4b75609762db47faad0d

@thomasstjerne I see you have updated the npm-shrinkwrap to a version that is incompatible with the version of node we are using to run the project. It works, but it gives warnings. 

I suspect it was by mistake?

I suggest that we either update to node 16 (that supports the version 2 you have updated to) or roll it back to the previous version. 

What is your thoughts?

**Comment by MortenHofft** [comment]
Perhaps that is why our builds have gone from 2 minutes to 10 minutes?

**Comment by thomasstjerne** [comment]
I think this was by mistake - we can rollback if you prefer

**Comment by MortenHofft** [comment]
I prefer to either roll back to a valid file or update node to a matching version. But I do not know what if anything has been added to the package file since. So that will have to be tested

**Comment by thomasstjerne** [comment]
Closing, we are on node 16 now
