### ISSUE TITLE
Improve visibility of absence data

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1762]
In discussions with D. Hobern while testing a dataset he plans to publish he suggests improvements that would bring more clarity to records of absence:

- The Occurrences [search] view had a visible indicator on each absence record that it is an absence. [It is in the table on the detail record, so I presume he refers to the search table]
- The Dataset view included alongside each Event an indicator of the number of taxa present/absent (e.g. replace the values for "Occurrence count" with e.g. "273 (206 absent)")
- The individual event views again indicated which records are absences and perhaps sorted occurrences with presence first (maybe even descending by count or measure) and absence afterward

**Comment by MortenHofft** [comment]
1) https://github.com/gbif/portal16/commit/ce61d435032e602969ab88d0d9f17578e5171ee8
