### ISSUE TITLE
Popup for survey

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1768]
@MortenHofft, as previously discussed we need to recruit respondents for a survey. I don't have the final link to the survey, but we should get started anyway. My inspiration is what Aarstiderne have on their site.

![Screenshot 2022-06-22 at 16 30 04](https://user-images.githubusercontent.com/21358085/175054877-9da65c9f-cef3-4f8e-819f-70b972dcc68c.png)

I would like something very similar, like this:

![Screenshot 2022-06-22 at 16 26 39](https://user-images.githubusercontent.com/21358085/175054987-5f705827-3dcb-401f-a81c-3a27ff598839.png)

We are imagining that this will appear when visiting a page under /occurrence/ after 10 seconds.

It should annoying enough to make people see it but not so annoying that they can't choose to ignore it.

How does this sound? Anything I haven't thought about?

**Comment by javiesgm** [comment]
For the styling, I'd go with something similar to what we have already in place for the cookies. 

Something like this
![Web 1920 – 1](https://user-images.githubusercontent.com/14220404/175539704-5ca179af-6582-411f-a224-7caf51b4af29.png)

**Comment by dnoesgaard** [comment]
Yes, please.

**Comment by dnoesgaard** [comment]
This is the final link, btw: https://surveyapac.deloitte.com/jfe/form/SV_23JpuX4LK0ofHim

**Comment by kcopas** [comment]
Just to be clear, @thomasstjerne —the agreed text is in [Daniel's comment](https://github.com/gbif/portal16/issues/1768#issue-1280269905)— @javiesgm was just mocking up something!

**Comment by MortenHofft** [comment]
There has been enough respondants. Remove the survey again.
