### ISSUE TITLE
Logos page alias update 

### ISSUE THREAD

**Issue by javiesgm** [gbif/portal16#1772]
We have been working on an updated version of the GBIF logos and identity system page and we need to update the alias /logos so that it points to [this page](https://www.gbif.org/composition/6lIWX44DtYLMYBqB3k2UAh/_preview) instead of the [old page](https://www.gbif.org/logos). 

Thanks!

**Comment by MortenHofft** [comment]
There is a field called url alias in contentful.
The existing page https://app.contentful.com/spaces/uo17ejk9rkwj/entries/4DXYM8oohOuKI2sw4syEGk
has the value `/logos`

The new page https://app.contentful.com/spaces/uo17ejk9rkwj/entries/6lIWX44DtYLMYBqB3k2UAh
has no urlAlias listed.

You should update that. If it does not work, then please reopen.

**Comment by kcopas** [comment]
My apologies—I thought we needed to update these in the registry when switching pages at a given alias!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MortenHofft** [comment]
No worries. I see it worked
