### ISSUE TITLE
Document the /occurrence/search/predicate and predicate map APIs

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1778]
The GBIF search and Map APIs were enhanced to support the predicate serialisation format.
This was not documented while we iron out issues which seem to be resolved.

Can this now be documented @fmendezh  ?

An example:

```
curl -X POST "https://api.gbif.org/v1/occurrence/search/predicate?limit=0&facet=occurrenceID" \
   -H 'Content-Type: application/json' \
   -d '{"predicate": {"type": "in","key": "COUNTRY","values": ["FJ","TO"]}}'
```

**Comment by dshorthouse** [comment]
Yes please!

Here's a use-case / script that fishes for occurrence records on GBIF. Given a barcode lifted off an image such as a duplicate herbarium sheet acquired from another institution that stuck on their own barcode sticker prior to donating in their exchange network, had they already published data we can import into our collection management system? https://github.com/dshorthouse/flatplant-barcodes/blob/main/barcode.rb
