### ISSUE TITLE
Miscategorization of literature (Biodiversity Science)

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#178]
Hey @burkeker,

In the latest import of literature from Mendeley, it seems that (nearly) all papers have had the topic Biodiversity Science (1327) added. This is of course not intended. We only wanted this applied to any paper that _didn't_ have any other topics matched from Mendeley tags. We described the logic like this:

- if Mendeley tag(s) match(es) core topic in Drupal, assign this topic(s)
- if no matches found, assign to topic “Advancing Biodiversity Science”

Agreed?

**Comment by burkeker** [comment]
Updated the literature topic mapping script. https://github.com/gbif/gbif-drupal/commit/dc89b95e8bd1834fa9273eb181cb1e719436c767

Please verify and close this issue. Thanks @dnoesgaard !

![literature mapping](https://cloud.githubusercontent.com/assets/637631/21498830/83b0bcac-cc30-11e6-89bc-85a210970c3a.png)

**Comment by dnoesgaard** [comment]
Hey Burke. Much better, thanks.
