### ISSUE TITLE
Loading mixed (insecure) display content

### ISSUE THREAD

**Issue by kbraak** [gbif/portal16#179]
Please see screenshot below. For more information about this warning see [here](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_passivedisplay_content).

Presumably we'll serve the GBIF API with HTTPS, which will help fix most warnings. Other cases such as when we load publisher logos will remain though (see screenshot below). 

**Related issues**: IPTs served with HTTPS have the following mixed _**active**_ content issues because the IPT web services (gbrds.gbif.org & gbrdsdev.gbif.org) and tools.gbif.org/ws-validurl arent' served with HTTPS:
* https://github.com/gbif/ipt/issues/1307
* https://github.com/gbif/validurl-ws/issues/1

![screen shot 2016-12-21 at 10 43 33](https://cloud.githubusercontent.com/assets/5981100/21384323/627e6e14-c76a-11e6-8aac-1b94e086227f.png)

![screen shot 2016-12-21 at 10 52 47](https://cloud.githubusercontent.com/assets/5981100/21384660/c116431a-c76b-11e6-9262-4c04740000b3.png)

**Comment by MortenHofft** [comment]
hardcoded http url. will be changed when the home page is implemented properly. I have changed it manually for now.
https://github.com/gbif/portal16/commit/c0b3ce509576cbb6b4656a9d5afe6d3d3f6d0235
