### ISSUE TITLE
Time formats

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1797]
Something seemed to have changed recently in our APIs. Either way we show odd time intervals on event pages.

The behaviour we want is: A user enters a time and and offset in Contentful
e.g. 14:00 UTC-3
That is currently presented through the API as 2022-09-29T14:00:00-0300

The website should just show the time `14:00 (UTC-3)`. NB that is isn't necessarily full hours it could be (UTC-4:45).
The method we use for time intervals is https://github.com/gbif/portal16/blob/master/app/helpers/format.js#L128
I [recently changed it](https://github.com/gbif/portal16/commit/73d9e6c53c4fc6e921b6e5741af5126a18dedb17) as issues was starting to show. But clearly didn't fix it.

I spend 45 minutes not getting anywhere, apparently I'm approaching this in a wrong way. I would think it was a simple task, but alas.

@thomasstjerne could you help me please?

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/portal-feedback/issues/4364

**Comment by thomasstjerne** [comment]
For some reason (that I cant remember) we are [giving moment an array of formats](https://github.com/gbif/portal16/blob/aca238ad38379a347e1399587bc5a39cff013910/app/helpers/format.js#L65) rather than relying on the default moment parsing. We were missing `YYYY-MM-DD` format which made some dates parse wrongly.

**Comment by thomasstjerne** [comment]
There are also quite some examples where winter dates have been entered in Contentful with UTC offset +2, even though they fall outside daylight saving time. So the portal is actually showing the correct date in these cases.
