### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#180]
I think events need a little love:

In searches,
- [x] filter by upcoming (default)/past events
- [x] display date of event rather than date the object was created in Drupal
- [ ] maybe filter by year of event
- [ ] filter by venue country
...

**Comment by burkeker** [comment]
venue country, although not explicit, has been mapped to the country field that other content types are sharing, so filterable on the site wide search.

**Comment by burkeker** [comment]
Within reach I've done two of them. For the rest I'd suggest there should be a specific "event" view, for example, when content type = event is selected, perhaps show a calendar like layout and provide range/sort controls.

**Comment by dnoesgaard** [comment]
Thanks. Having a specific search view for events sounds good to me :) Let me know when/if you need additional input or comments.

**Comment by MortenHofft** [comment]
Subscribing to upcoming events seems like a nice feature from the existing site. Do you know how many people do that @dnoesgaard ?
Aside from that, the implementation, more or less supports what we have on the current site.

**Comment by dnoesgaard** [comment]
@MortenHofft Subscribing how? RSS?

**Comment by dnoesgaard** [comment]
Silly me, just realized that you are of course referring to the ical-feed which I agree is _very_ useful feature. I'm going to look into the usage...

Out of curiosity (and because Anne Mette asked), is it possible to have a similar feed for "internal" events?

**Comment by dnoesgaard** [comment]
Just to clarify my previous comment - admin are creating eventsin Drupal for internal use (meetings, conferences, etc.) which are _not_ published. They use the [GBIFS admin report](http://drupaledit.gbif.org/admin/reports/event-gbifs-admin) to keep track of these. So my request would me a "secret" or pwd-proteced ical feed of all events, including unpublished ones. This is, however, not currently super high priority...

**Comment by MortenHofft** [comment]
@dnoesgaard regarding more filtering. Currently there is 5 upcoming events. Furthering filtering seems unneccessary doesn't it? Or is it for past events you need it?

**Comment by dnoesgaard** [comment]
I honestly can't remember how this looked back in December. So for now, let's just say that we're ok...
