### ISSUE TITLE
Remove irrelevant protocols in the occurrence search

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1802]
We should protocols that aren't relevant to occurrences:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/237221/200325414-cf2d705e-c976-484f-a06f-109c87011d23.png">

I suggest we either control that through configuration or hide anything with 0.

RSS caused some confusion for example and existed as an endpoint type for the IPT v1.

**Comment by MortenHofft** [comment]
I've narrowed the list of possible protocols to the one that has 1 or more occurrences in above screenshot.
But it will still show zero if e.g. `DiGIR MANIS` is no longer used, but since it is a valid protocol it will show in the list
