### ISSUE TITLE
Links for literature on taxon page are local instead of external

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal16#181]
If an article listed in the "References" section on a taxon page has a DOI, the reference is a clickable link, e.g. http://demo.gbif.org/species/2138546

However the link is local, e.g. http://demo.gbif.org/species/10.3897/BDJ.3.e6313 and not http://dx.doi.org/10.3897/BDJ.3.e6313 I'm guessing the code for parsing DOIs doesn't insert the expected http://dx.doi.org/ prefix. Note that the correct prefix for resolving a DOI is evolving, it used to be http://dx.doi.org/. then just http://doi.org/, and now appears to be https://doi.org/ .

**Comment by MortenHofft** [comment]
Thank you. I guess urls in references should also be made into links. But at least now the urls work.
