### ISSUE TITLE
new translation: add polish

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1815]
Add polish as a language option to UAT

**Comment by MortenHofft** [comment]
I'm waiting for crowdin to properly updates its pull request to put the data into the expected `pl` folder

**Comment by MortenHofft** [comment]
Once Crowdin does as expected, we can do :

add `pl` a lot of times to `config/locales.js`
* it should be added to `locales` when in uat
* As there is no contentful version of polish currently in our project, then we should just leave that part out.
* then a language iso mapping for translations: `translationMap['pl'] = 'pol';`
* we do not need to change the momnet map as Moment calls it "pl" as well.
* then add what we call it in our vocabulary https://api.gbif.org/v1/vocabularyLanguage: `vocabularyMap['pl'] = 'pl-PL';`

And then we need to add the `moment` configuration for polish in `app/views/shared/layout/html/html.js` => `require('moment/locale/pl');`

**Comment by MortenHofft** [comment]
@MattBlissett you have admin access to Crowdin - could you update the configuration please (so that polish is synced to the proper folder)
https://crowdin.com/project/gbif-portal/apps/system/github

**Comment by MortenHofft** [comment]
I see that you have removed `update_option: update_as_unapproved` was that illegal as well?

**Comment by MattBlissett** [comment]
I moved the existing crowdin.yml file out of the way, as the web interface wouldn't allow any changes and said it was corrupt.

The file as it is now is generated by Crowdin. I translated Poland → Polska and will see what happens.

**Comment by MortenHofft** [comment]
It seem to respect that you simply renamed the folder

**Comment by MortenHofft** [comment]
But removing `update_option: update_as_unapproved` might well change behaviour unless you know that it didn't work anyhow or have been changed to default.

The intention of that line was, to not discard to existing translations of the english source changed, but simply mark it as unapproved for the translators to decide what to do. This is useful if e.g. Daniel makes a small change, correct a typo or such, but we do not want to see the french translation discarded completely.

**Comment by MattBlissett** [comment]
It must be the locale mapping that is no longer accepted in the crowdin.yml. That's set within the Crowdin branch configuration.

I've restored the update_option and Crowdin seems to have accepted it.
