### ISSUE TITLE
allow links in translation 

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1819]
https://github.com/gbif/portal16/blob/7d3a839d397287fb3d5c16b4a068f52932d8cdf7/app/views/pages/occurrence/download/occurrenceDownload.html#L293

As with downloadReport.promoteTransperant (in the line before) could we please we please allow MD/HTML in this translation? I've included a link but it doesn't get parsed.

I think we could also merge the two translations if easier.

**Comment by dnoesgaard** [comment]
Oh yeah, that would of course be easiest. I don't think they are used in any other places.

I'll check and combine

**Comment by dnoesgaard** [comment]
Both are now combined in `downloadReport.promoteTransperant`.

**Comment by MortenHofft** [comment]
deployed to prod
