### ISSUE TITLE
Delete unused source translation

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1823]
https://github.com/gbif/portal16/blob/7d3a839d397287fb3d5c16b4a068f52932d8cdf7/locales/source/en-DK/components/downloadReport.json#L19

as per https://github.com/gbif/portal16/issues/1819

**Comment by MortenHofft** [comment]
Done. You are welcome to leave pull requests if you want to. And also welcome not to. But I've noticed that you often take the effort to locate the line that needs changing

**Comment by dnoesgaard** [comment]
Ok, I'll give it a try next.
