### ISSUE TITLE
New footer banner - Global Core Biodata Resource

### ISSUE THREAD

**Issue by javiesgm** [gbif/portal16#1855]
It is necessary to include a banner in the footer of the website pointing out that GBIF is a Global Core Biodata Resource. 
This is a suggestion on how it could look like.  

![footer](https://user-images.githubusercontent.com/14220404/235164984-ffe29bdb-add6-4bc3-b686-645c3df398fa.png)

I'm including the Global Core Biodata Resource logo in .svg 
![gcbr](https://user-images.githubusercontent.com/14220404/235165153-62d807b0-d738-4e2b-98ab-cccf1ceb5ec7.svg)

It should link to this news item https://www.gbif.org/news/6PHdgoyIF6RmI7u4VOouuD

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/2c1b3c368d28e1babebdd77a0d838f40022fd85e
