### ISSUE TITLE
GRSciColl search: code and country

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1861]
We noticed people typing "Finland" into [collection](https://www.gbif.org/grscicoll/collection/search) and [institution](https://www.gbif.org/grscicoll/institution/search) search.

I took a look at the [search SQL](https://github.com/gbif/registry/blob/dev/registry-persistence/src/main/resources/org/gbif/registry/persistence/mapper/collections/CollectionsSearchMapper.xml) and it doesn't look particularly trivial to add to the generic '?q=' query (although it could be achieved if preferable).

I suggest instead adding options to search by code and by country in the UI similar to the [management console](https://registry.gbif.org/collection/search?country=DK) which I expect would satisfy many entry needs.

**Comment by MortenHofft** [comment]
Given that we have a new GrSciColl site coming up within the next month, I suggest closing this issue. Just let me know if you disagree
