### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#1866]
With the GDPR changes, it's time to remove Google Analytics.

@kcopas to confirm, but I think this means we can also remove the accept/reject cookie banner, though it would need to be replaced with a notice that functional cookies are used -- probably in the privacy policy, or maybe as a separate page linked from the footer.

**Comment by kcopas** [comment]
I suspect JIRA was still there as a legacy. If it's truly inoperable among you lot, then I'll remove it as well.

**Comment by kcopas** [comment]
@MattBlissett , could I ask you to swap Plausible in for GA on the discourse forum? 

Looks simple enough ([see here](https://meta.discourse.org/t/add-plausible-analytics-or-fathom-tracking-to-discourse/173310)) I could probably manage, but the moment I got it wrong, I could spend hours down a rabbit hole of shame and imposterhood…

**Comment by MattBlissett** [comment]
I think this has been completed.
