### ISSUE TITLE
More environments for gbif.org

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1869]
We currently use UAT as a translation environment. Meaning that every time there is a new push from Crowdin, then we build that to UAT. This is appreciated by the translators.

But it means that we cannot use UAT for testing new features and showing them to a group. 

Could we create a gbif-translations.org or such instead?

**Comment by MattBlissett** [comment]
What about making www.gbif-staging.org public and using that for testing translations?  Or vice-versa, I'm not sure how often we have portal16 bits translated before they go to production.

**Comment by MattBlissett** [comment]
Superseded by https://github.com/gbif/infrastructure/issues/19
