### ISSUE TITLE
Display of event dates, granularity and ranges

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1877]
in cases where event date is only a year, we should only show year precision instead of 1 january.
And in cases of ranges, we should show that.

In the API layer we will soon populate year, month, day to be consistent with eventDate.

Ranges will always be formatted as a date-slash-date.

**Comment by MortenHofft** [comment]
example records
https://www.gbif-dev.org/occurrence/76522
https://www.gbif-dev.org/occurrence/76524
https://www.gbif-dev.org/occurrence/76523

**Comment by MattBlissett** [comment]
And a convenient search for the three: https://www.gbif-dev.org/occurrence/search?dataset_key=06a00852-f764-4fb8-80d4-ca51f0918459&event_date=2018&taxon_key=7429082&year=2018&advanced=1

**Comment by MattBlissett** [comment]
This is now on UAT, and there's a dataset full of examples: https://www.gbif-uat.org/occurrence/search?dataset_key=d6167827-973d-429a-a00c-8ea294d62d80

It would be useful to have this ready very soon, so the website looks good before announcing the change on the mailing list etc.

**Comment by MortenHofft** [comment]
branch `feat-1877-event-range`
