### ISSUE TITLE
Changes in directory

### ISSUE THREAD

**Issue by marcos-lg** [gbif/portal16#1886]
New values added to the role enum:
- FUNDING_CONTACT
- INVOICE_CONTACT
- FINANCIAL_CONTACT
- TRAINER
- MENTOR
- AMBASSADOR
- TRANSLATOR
- REVIEWER
- JURY
- AWARD_WINNER

New enum AreaExpertise:
- AGRICULTURE_AND_FOOD_SECURITY
- BUSINESS_SECTOR
- CITIZEN_SCIENCE
- CLIMATE_CHANGE
- COLLECTIONS_MANAGEMENT
- CONSERVATION
- DATA_ANALYSIS_AND_VISUALIZATION_STATISTICAL_MODELING
- DATA_MANAGEMENT
- DATA_MOBILIZATION
- DATA_PAPERS
- DATA_PUBLISHING
- DATA_USE
- DNA_BARCODING_AND_METAGENOMICS
- FRESHWATER_ECOLOGY
- HUMAN_HEALTH_AND_ONE_HEALTH
- IMPACT_ASSESSMENTS
- INVASIVE_ALIEN_SPECIES
- LONG_TERM_MONITORING_SYSTEMATIC_SURVEY_DATA
- MACHINE_OBSERVATIONS
- MARINE_ECOLOGY
- SOIL_BIODIVERSITY
- THREATENED_SPECIES

New enum programme: 'BID','BIFA','CESP'
New enum award: 'GRA','EBBE1ST','EBBE2ND','EBBE3RD'
New enum certification:  'BIODIVERSITY_DATA_MOBILIZATION', 'BIODIVERSITY_DATA_USE',        'BIODIVERSITY_DATA_PUBLISHING_SUPPORT'
New enum certificationLevel: 'BASIC','ADVANCED'

New fields added to the person:
- orcidId
- areasExpertise
- languages
- profileDescriptions
- certifications

New endpoints:
- https://api.gbif-uat.org/v1/directory/person/41/profileDescription - GET, POST, PUT and DELETE
- https://api.gbif-uat.org/v1/directory/person/41/profilePicture - GET, POST and DELETE. The get accepts the param base64=true
- https://api.gbif-uat.org/v1/directory/person/41/certification - GET, POST and DELETE

**Comment by MortenHofft** [comment]
@marcos-lg What are the APIs where those roles are listed in their entirety? And the expertice etc. I would like to have the uptodate information, but do not see it https://api.gbif-uat.org/v1/enumeration/basic but perhaps I just do not know what to look for

**Comment by marcos-lg** [comment]
The directory has its own endpoints: https://api.gbif-uat.org/v1/directory/enumeration

**Comment by MortenHofft** [comment]
@kcopas 
Which of this information do we consider public and should be available on public APIs and possibly websites?
Is:

orcidId
areasExpertise
languages
profileDescriptions
certifications

all inteded as public?

**Comment by MortenHofft** [comment]
@marcos-lg Why do the directory have its own list of language enumerations? 
Do we really need another one?

https://api.gbif.org/v1/enumeration/basic/Language
https://api.gbif-uat.org/v1/directory/enumeration/Language
https://api.gbif.org/v1/vocabularyLanguage

**Comment by MortenHofft** [comment]
I guess that last comment in traditional chinese partly explains why we aren't using the 3-letter versions

**Comment by MortenHofft** [comment]
I've added orcid as the only field to the UI and made sure the roles display properly.

**Comment by marcos-lg** [comment]
I can change the casing yes.

For the language you should actually use https://api.gbif-uat.org/v1/directory/enumeration/language . I have to remove the one with the upper-case L.
