### ISSUE TITLE
Directory driven lists

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1889]
Use the directory as the source of info for people displayed in our lists of [translators](https://www.gbif.org/translators#_gbif-volunteer-translators), [ambassadors](https://www.gbif.org/article/1ye7qAa9Z2HVSn85bfSmLP/), [GRA](https://www.gbif.org/graduate-researchers-award#_previous-winners) and [Ebbe winners](https://www.gbif.org/ebbe#_ebbe-nielsen-challenge-winners), and [trainers and mentors](https://www.gbif.org/article/5SExsCfj7UaUkMCsuc6Oec/mentors-and-trainers#_volunteer-mentors)

This work should be enabled by https://github.com/gbif/portal16/issues/1886

**Comment by MortenHofft** [comment]
@kcopas and @marcos-lg 
I the intention to replace tables listed above completely with information from the directory?
Because it isn't obvious for me how to do that. Could you please specify what part you imagine reproduced with data coming from where?

**Comment by marcos-lg** [comment]
@kcopas some of the fields of those pages are not present in directory, for example, the language of the translators or the news item for GRA winners(among others). So if we want to reproduce those pages we need to add more fields to the directory.

**Comment by MortenHofft** [comment]
**translators table**
> name, language, country, annual badges

That looks straight forward. I think the language field in the directory should be explained better. It wasn't obvious to me what the inteded usage of this field was. I'm guessing now that it isn't the languages a person speak, but what translations the person has contributed to. That should be explained in the UI. Perhaps the field should even be more self explanatory (difficult to name perhaps)? 

annual badges is the certificates and the year i guess.

**ambasadors**
> name, Affiliation, country, area of expertise, orcid

where does the Affiliation come from. In the example I've looked at it isn't the same as the institution of the person. nor the associated participant. 

the rest is self explanatory

**GRA**
> year, name, country, news item, 

year, name, country is easy. News item i cannot see linked

**Ebbe**
> year, prize, project, recipients, countries, news, orcid

year, prize, recipients, orcid and countries we can get at with enough transformations, but `project` I do not see anywhere. Neither do i see the news item.

**Volunteer Mentors**
> Name, email | Country | Areas of expertise | Project Mentor | Trainer | Node Mentor

name, email, country, area of expertise,
trainer is a role.
there is no role called `Project Mentor` or `Node mentor` there is only `mentor`. What is the intention here?

The UI has fields `GBIF role, start, end, programme, award` -  It doesn't sounds like they are all meaningful for all roles?

**Whom to expose from the directory**
Our directory is behind a VPN and login. We now discuss exposing some of that information. But which people do we expose? We have 1330 people currently in the directory. It doesn't all seem suited for a public API. I need to know what people to expose and which fields are safe. We could perhaps specify some roles or awards or required associations that would need to be present for someone to be public.

**Comment by MortenHofft** [comment]
@kcopas and I talked this over:

update: just remove new items in all tables
project name in ebbe prize - that could be removed as well
for volunteers - just use the role `mentor` and do not use 2 diff roles.

ui
award field only relevant for award winners
programme field only makes sense when role = mentor
language: rename in UI to make it clear what it is used for
@marcos-lg the UI should probably be conditional based on what role is picked

**Comment by MortenHofft** [comment]
how is the start and end date intended to be used for award winners?

**Comment by kcopas** [comment]
Very good question. In reality, all we want to do is assign the year. In practice, we can fill out the start and end dates in whatever way gets interpreted as `Ebbe Nielsen Challenge, 2nd prize, 2023`, or `Graduate Researchers Award, 2021.

**Comment by MortenHofft** [comment]
I'll update this issue with whatever makes most sense when consuming the API then. I suspect 2022-1-1 -- 2022-12-31 makes most sense then. without an end date it is difficult to search for who won in 2023 as it will include 2022 winners.

**Comment by MortenHofft** [comment]
@marcos-lg could we make it possible to search relations for awards as well. So that I can get all GRA winners

**Comment by marcos-lg** [comment]
@MortenHofft for the images, is this url enough? https://api.gbif-uat.org/v1/directory/person/41/profilePicture

**Comment by MortenHofft** [comment]
I've made an example of how it could work here https://www.gbif-dev.org/composition/3fvWSwDCj8tZBpRFiWC8QQ/_preview
It would only work on composition pages as it is a custom block type
https://app.contentful.com/spaces/uo17ejk9rkwj/environments/dev/entries/3fvWSwDCj8tZBpRFiWC8QQ
Would this solution work for you?

**Comment by MortenHofft** [comment]
> @MortenHofft for the images, is this url enough? https://api.gbif-uat.org/v1/directory/person/41/profilePicture

I cannot see it. No access. And thumbor cannot either. So I cannot display it in the browser no. But I guess you need to keep it protected. Hmm - annoying. I'm not sure what a good solution is

**Comment by MortenHofft** [comment]
@marcos-lg What is the reason for not using the language enum we have for languages? 
https://api.gbif.org/v1/enumeration/basic/Language
I notice that you use another set of language codes. It makes translations trickier

**Comment by kcopas** [comment]
pinging @laurarussell @dnoesgaard for review, please:

> I've made an example of how it could work here https://www.gbif-dev.org/composition/3fvWSwDCj8tZBpRFiWC8QQ/_preview It would only work on composition pages as it is a custom block type https://app.contentful.com/spaces/uo17ejk9rkwj/environments/dev/entries/3fvWSwDCj8tZBpRFiWC8QQ Would this solution work for you?

It looks like it fulfills the functionality we need and have discussed for our current use case (lists in website)—thanks.

**Comment by dnoesgaard** [comment]
This looks good.

A few comments for consideration in next iterations:

- Would it make sense to "configure" the list via the json settings? Maybe to define which roles you'd like to include in the list? So instead of having a translatorsList component, have a peopleList and then select the role(s) via settings?
- Could the table allow sorting by clicking the column headers?

**Comment by MortenHofft** [comment]
Sorting: it could it is just a bit cumbersome to implement because it should sort by translated terms and not the actual values. Which means that I cannot use my standard way of translating. But yes - it is perfectly doable.

I have stayed clear of making this a general component for lists. Instead I've made special endpoints for each of the defined types. This avoid exposing emails for award winners, while still having them for mentors (which is what I see in the current markdown versions). Searching for arbitrary roles can also create very big lists, and since the API do not search people, but roles that means that people will be repeated multiple times. Currently I have a proxy that removes duplicates, but that isn't a nice solution if there is large result sets.

Is it a real need to have tables with arbitrary roles and other filters? If so we should expand the API

**Comment by MortenHofft** [comment]
Also I would need to know exactly what roles we expose, and exactly what fields. I'm worried about gdpr if I make this a flexible solution.

**Comment by kcopas** [comment]
> Also I would need to know exactly what roles we expose, and exactly what fields. I'm worried about gdpr if I make this a flexible solution.
> 
Good thought, but we should deal with GDPR through the privacy policy. I will draft a new clause for volunteers and award winners in §2 (which, tbh, should already be there, given the current lists…)

**Comment by laurarussell** [comment]
My initial thought on the list display is sorting. For volunteers, we often look for volunteers in a specific region, then country.

I was thinking that when we clicked on an individual, we'd get the pop-up from the directory that showed all of their pertinent information. But maybe that doesn't work with contentful pages?

![image](https://github.com/gbif/portal16/assets/742537/2b6e5bff-a1a2-4cdb-a756-21d2de925115)

For mentors, I don't need all the existing columns, especially, if there is a pop-up. Probably just name, country, region if we have it in the directory, and mentor since year. Not sure how difficult it would be to display expertise now? 

Not really concerned if their email addresses are there/clickable. Originally I think we thought people would directly reach out to mentors, but I don't think that happens. So this is more about recognition. If no pop-up, I like that their ORCID is clickable.

**Comment by laurarussell** [comment]
> **Volunteer Mentors**
> 
> > Name, email | Country | Areas of expertise | Project Mentor | Trainer | Node Mentor
> 
> name, email, country, area of expertise, trainer is a role. there is no role called `Project Mentor` or `Node mentor` there is only `mentor`. What is the intention here?

We've done away with Project Mentor and Node Mentor. We don't necessarily need to list the trainer role (unless maybe we do it in a different box/list). Trainers are mentors. But not all mentors are trainers. :-D

**Comment by MortenHofft** [comment]
Who is this for? Should the directory support search by role instead / as well. If you look for data that isn't intended public at least.

**Comment by laurarussell** [comment]
One more follow-up on language from above.

> _language_
> I think the language field in the directory should be explained better. It wasn't obvious to me what the inteded usage of this field was. I'm guessing now that it isn't the languages a person speak, but what translations the person has contributed to. That should be explained in the UI. Perhaps the field should even be more self explanatory (difficult to name perhaps)?

*******
We use languages for both what they speak (important for mentors and ambassadors) and what they translate. For translators, we award badges for the fact that they were a translator in a given year, not for what languages they translated.  So I think I convinced @kcopas (maybe or I just wore him down) that language wasn't necessary at the role level.

From the directory issue with regard to languages: https://github.com/gbif/directory/issues/31

> @kcopas - just to double-check this:
> 
> > We think languages should also go there [on person].
> 
> From the discussion above, you had indicated a wish to be able to specify which languages a person had been responsible for in their role as a translator, separate from other languages they may know. I don't have an opinion, but just want to check in case that was overlooked. Thanks

Kyle
> I did do the suggesting. We've had a discussion and I'm persuaded that managing that information in the main profile will serve more general purposes better. Like Eeyore says, "Thanks for noticing."

Marcos
> Ok, I will move the languages and the areas of expertise to the main profile then. And the rest will stay as in the sketches I've put above.

**Comment by laurarussell** [comment]
> Who is the audience for these tables? Should the directory support search by role instead / as well. If you look for data that isn't intended public at least.

Anyone in the general public. Examples:

I want recognition for my role as a volunteer (that everyone can see).
I want to show my boss that I'm a volunteer.
I want to be a volunteer and I want to see who else is a volunteer.
I'm looking for a specific type of volunteer so I want to see who is available in my country, region, etc. so I can ask them to serve as a mentor, trainer, speak at event, etc.

**Comment by MortenHofft** [comment]
I ask because you write, "I need" and "we often look for ...", which indicate that the audience is the secretariat. For that we have the directory. And if that isn't doing a good job, then we could extend that.

From that it isn't obvious to me that a popup with address and email and phone number makes sense for a translator or an award winner. On the contrary I would think it was giving away too much information. Just because I win the Ebbe Nielsen award and you have my email to contact me doesn't mean I want it on a public website.

Anyway, most things can be done. I just need clear specifications. My understanding was that we ported the existing tables, but that target seem to be moving a bit. Which is fine. But I'm not sure what to do :)

**Comment by laurarussell** [comment]
> I ask because you write, "I need" and "we often look for ...", which indicate that the audience is the secretariat. For that we have the directory. And if that isn't doing a good job, then we could extend that.

Sorry...the "I" in my examples was meant to be an external user of the list (not I as in me, Laura who works at the Secretariat).

I'll let @kcopas  respond to this.

> From that it isn't obvious to me that a popup with address and email and phone number makes sense for a translator or an award winner. On the contrary I would think it was giving away too much information. Just because I win the Ebbe Nielsen award and you have my email to contact me doesn't mean I want it on a public website.

**Comment by kcopas** [comment]
@MortenHofft I would tend to agree with you. Award winners and translators seem like the ones where there's far less need or rationale for displaying detailed contact info. I'm not for consistency for consistency's sake.

**Comment by MortenHofft** [comment]
I've put this into production. There is no content yet so nothing shows. But it is available in dev, uat, staging and prod.
I've provided an example in dev
https://www.gbif-dev.org/composition/3fvWSwDCj8tZBpRFiWC8QQ/copmposition-test

The only custom parameter is a table styling. Else everything is decided by the type.
```json
{
    "tableStyle": "max-height: 1500px; border-radius: 4px; box-shadow: 0 3px 10px 5px rgba(0,0,0,.1);"
}
```

I've mimicked the existing Contentful tables as well as I could given the data we have available in the directory. 
Please create new issues if there are changes needed.
