### ISSUE TITLE
add datasetName and datasetId to UI

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1912]
https://github.com/gbif/pipelines/issues/662#issuecomment-1980416062

from @rukayaj 
> I've had another request for the GBIF UI to allow searching by datasetName. Use case:
>
> Colleagues have received funding from a particular funding agency and have published samples associated with these projects in our Collections Management System which are grouped using datasetName. It would then be useful to be able to search out the relevant data in GBIF.
>
>The same data field in the CMS is also used to identify other datasets, such as e.g. all accessions used for the Arctic collections paper we published last year (which I guess was when we started talking about datasetName).
>
>While it’s great that it’s available via the API, this is not a solution that is easily accessible to many users, and hence it would be very nice to be able to search for it in the standard GBIF UI. In other words, our users are not comfortable using the API for this kind of search and would prefer to have it in the UI with a download option.

**Comment by rukayaj** [comment]
Wow awesome! Thanks very much @MortenHofft
