### ISSUE TITLE
Remove facebook

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1939]
Our facebook integration is deprecated. And after discussion comms decided that we should remove the facebook integration for user profiles. That means that it is no longer possible to login or register using facebook.

**Comment by MattBlissett** [comment]
Should we tell any users who are currently using Facebook for login?

**Comment by MortenHofft** [comment]
We do not track usage of login strategy, but we have 8000 users with an associated facebook account.
If users report that they miss the feature, then we could adapt to the latest facebook api changes
