### ISSUE TITLE
cms facets are not multiselect

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#194]
the cms search interface appears to be a multiselect one, but is in fact single select.
It should either support multiselect or the interface should reflect the API. 

The API seem to ignore everything but the last parameter of a type
http://demo.gbif.org/cms/search?category_purpose=955&category_purpose=991
vs
http://demo.gbif.org/cms/search?category_purpose=991&category_purpose=955
these do not give the same result. because only the last parameter is used.

It seems to be the case for all facet types. not only content types as mentioned here: https://github.com/gbif/portal16/issues/147

This of course leads to an odd experience when clicking around.

**Comment by burkeker** [comment]
This is fixed from the CMS API side by showing only the facet selected. https://github.com/gbif/gbif-drupal/commit/bd33a6f119375cc0fc1f3b0fa5f14bd07bc8e506

Updated UI at 55699b8. And e2e test 6adaad5
