### ISSUE TITLE
facet counts not updated correctly in cms search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#195]
The facet counts do not always update correctly. I suspect a racing condition. 
I've created a small video showing it. ther action happens around 25 seconds in.

notice the audience counts -  they show the counts for another search than the shown one. Probably because that ajax reponse is slower.
https://gbif.app.box.com/s/yxdzz4u6u598d4ohplrnmx24t6deg7qd

**Comment by burkeker** [comment]
Thanks, Morten. I believe this is fixed together with #67.
