### ISSUE TITLE
developer documentation links are dead

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#196]
seemingly all links to examples are dead. The error seem to be an error in the template. the root of the links are templated, but not correctly and hence not resolved.
example
http://localhost:7000/developer/registry#p_decade click on the example link
takes you to 
http://localhost:7000/developer/%7B$%20apiBase%20$%7Ddataset/search?facet=DECADE&limit=0

same goes for other links I have tried.

@mdoering you might know how to fix this easily?

**Comment by mdoering** [comment]
the occurrence.nunjucks template does it right. Instead of 
<a href='{$ apiBase $}dataset/search

it should be 
<a href='"+apiBase+"dataset/search
