### ISSUE TITLE
Specify type of "product" when informing GBIF about usage 

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1963]
In the form shown on download pages when a user clicks "Tell us about usage" (`downloadKey.showUsageFormModal`), please add a dropdown for **Type** between **Title** and **Authors(s)**:

options:

journal article
book
book chapter
conference paper / proceedings
preprint / working paper
report
web page
thesis / dissertation
course / teaching materials
magazine article
statute
patent
newspaper article
software / computer program
hearing
television broadcast
encyclopedia article
case
film
bill
other (please elaborate in comments below)

**Comment by dnoesgaard** [comment]
perfect, thanks!

**Comment by dnoesgaard** [comment]
was this rolled back? i see the field in the form but it's no longer in the emails sent.

Also, can we make sure that type=="" is not an option?

**Comment by MortenHofft** [comment]
Nothing has been rolled back no, it is the same code that you tested last week. And yes we can make type a required field.

If the mail doesn't include the type, then I doubt it ever did. I didn't look into the mail client part (I haven't implemented this code originally), but just used the ui to send the mail so you could evaluate if it was like you wanted it to. We probably misunderstood each other. I will look at that part of the code and ask you to evaluate it again.

**Comment by dnoesgaard** [comment]
I must have dreamed seeing it 🤣  Perhaps it was just this I saw

> comments: TEST: Is there a type included here Daniel? type: journal article

**Comment by MortenHofft** [comment]
That is a confusing message to say the least. The formatting of those mails is also confusing in code I just notice. Do you use it for automatic parsing? I believe I've added it now, and changed the formatting slightly. Please review if it is useful now (UAT). You better fill in the form yourself to avoid misunderstandings.

**Comment by dnoesgaard** [comment]
All good now. Can be deployed to prod.
