### ISSUE TITLE
Adapt the portal to use the Sex and TypeStatus vocabularies (UAT)

### ISSUE THREAD

**Issue by marcos-lg** [gbif/portal16#1974]
We're reprocessed the data in UAT to use the new vocabularies for Sex and TypeStatus:

https://api.gbif-uat.org/v1/vocabularies/Sex/concepts/latestRelease
https://api.gbif-uat.org/v1/vocabularies/TypeStatus/concepts/latestRelease

Then the portal has to be adapted to use those values instead of the enums that we've been using til now.

**Comment by MortenHofft** [comment]
Currently an enum but changing to a vocabulary. We could simply copy and rename the pathway filter.
It isn't ideal, but since we are revisiting filters anyhow I would think it was fine
