### ISSUE TITLE
Northern West Siberia IPT is not displayed on the map

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/portal16#1980]
Northern West Siberia IPT installation http://ipt.ugrasu.ru:8080/rss.do is not displayed on the map https://www.gbif.org/ipt (coordinates 61°00'05.5"N 69°01'44.9"E) - it is present in the API.

**Comment by mike-podolskiy90** [comment]
@MortenHofft

**Comment by MattBlissett** [comment]
It's not in http://api.gbif.org/v1/installation/location/IPT_INSTALLATION, and isn't on https://registry.gbif.org/organization/fa46e267-4d25-41f5-bbbe-1cd75860b943 which is I think the value that's used.

**Comment by mike-podolskiy90** [comment]
Indeed, it's not present in the location response. However, it's linked to the organization https://registry.gbif.org/organization/fa46e267-4d25-41f5-bbbe-1cd75860b943/installation. Or do I confuse something?

**Comment by MattBlissett** [comment]
The latitude and longitude on https://registry.gbif.org/organization/fa46e267-4d25-41f5-bbbe-1cd75860b943 are null.

I don't remember, but I think the location for the IPT is the location of the primary associated organization.

**Comment by mike-podolskiy90** [comment]
Oh right. So it's organization's coordinates, not IPT

**Comment by mike-podolskiy90** [comment]
I've added the coordinates it is displayed now. Closing.
