### ISSUE TITLE
DBpedia info is about country not species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#199]
**DBpedia info is about country not species**

info on Argentina Hill. species page is about Argentina the country.

is it possible to filter the dbpedia query somehow?

-----
fbitem-species3026341
Reported by: @mortenhofft
System: Chrome 55.0.2883 / Mac OS X 10.11.6
Referer: http://demo.gbif.org/species/3026341
Window size: width 1974 - height 1129

**Comment by MortenHofft** [comment]
Removed for now - it is a shame, but I couldn't find a stable way to get the correct data. There might be a better way to query that I overlooked, but the current version created to many false positives.
