### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#202]
**Broken image**

On first page view the image did not show, but on refresh it did.

-----
fbitem-7ff603e5cee85f8d3bb68abe45ba6ebee3872bb4
Reported by: @timrobertson100
System: Chrome 54.0.2840 / Mac OS X 10.11.5
Referer: https://demo.gbif-dev.org/generic/publishing/data-papers
Window size: width 1433 - height 799

**Comment by MortenHofft** [comment]
@MattBlissett I moved the issue here. Not sure it really has anything to do with the portal - as I would guess it is the image cache only. But for now it is here as a reminder.

**Comment by MortenHofft** [comment]
I haven't been seeing this for a while. I'm closing it. If I understood you correctly @MattBlissett you believe you had solved it?
