### ISSUE TITLE
home page - counts of occ and species

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#208]
The home page needs implementation.
Expand home page with featured data stories and events and a brief introduction to what GBIF is.

**ideas**

* [x] events (requires cms api to allow event search sorted by event date)
* [ ] show counts and maps
* [x] data papers would also be nice to show.
* [ ] images and info about he gallery

Basically stats and leading attention to what we believe is telling the story of what GBIF is. The network aspect could need some attention.

Could easily take some iterations as there is no doubt many opinions on what that page should do and support.

**Comment by MortenHofft** [comment]
There is now a home page with more than a search box.

https://demo.gbif-dev.org/?underDevelopment

This could go in many directions and could need love. But for now the question is: how do you guys ( @kcopas, @dnoesgaard, @burkeker) feel about it? It is intended to start the conversation about what we want. If you want to tell a story, then what is it? Do you have text already? What visuals could support that story?

Is it something we can use as a first version? I suspect we will do many iterations on this. If we say yes for now, then we will proceed and make it into a Drupal item instead of the hardcoded current version and clean the visuals a bit.

If nothing else it can serve as an inspiration for better ideas :)

There is for example not a lot of counts in this version. Neither gallery or data papers or newsletter.

**Comment by MortenHofft** [comment]
One thing that I miss is the links to occurrences and species search. I'm obviously not the prototype user, but is is annoying having to do an omni search when I already know that it is an occurrence search I want to do. Maybe those links shouldn't have been removed.

**Comment by MortenHofft** [comment]
Occurrence page have been further updated. this time around with using the geo ip to show information about the node and datasets and publishers and occurrences from the estimated country. 
Prose and feedback would still be appreciated @kcopas . Without you guys I end writing something in danglish with little relevance :)

**Comment by MortenHofft** [comment]
copas, hirsh, robertson and hobern have given feedback and suggestions. i believe the only possibly nlocking thing missing is counts

**Comment by dnoesgaard** [comment]
I for one do agree that having the counters somewhere on the home page would be good. Adding them to the search bar may be an easy solution, but might also cause some confusion, e.g.

![screen shot 2017-06-22 at 11 27 49](https://user-images.githubusercontent.com/21358085/27427065-f24ed444-573d-11e7-8c27-6b72c8a90a09.png)

**Comment by MortenHofft** [comment]
counts added as outlined in mock up by Kyle Copas. There have been little feedback on thisissue so I will close it and open a new issue if something specific comes up.
![screen shot 2017-08-10 at 08 45 30](https://user-images.githubusercontent.com/6759267/29157720-56290184-7da8-11e7-9818-0b1244df558c.png)
