### ISSUE TITLE
occurrence search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#209]
There is a bunch of occurrence filters missing. Most notably the location filters.

**Comment by MortenHofft** [comment]
Ideas for locations filters are welcomed.

So far all I have thought of is:

* use map view for drawing.
* show geometrical queries as location name instead of the geometry only (look into impact and cost)
* Try to make the many checkboxes more understandable. possibly just an explainer
* insert wkt instead of drawing

![screen shot 2017-01-18 at 09 08 36](https://cloud.githubusercontent.com/assets/6759267/22056041/5106edc8-dd5e-11e6-8e7e-786c0a82edb2.png)

**Comment by rdmpage** [comment]
@MortenHofft Given how widely used GeoJSON is, it would be great to be able to paste in a GeoJSON shape as a query.

**Comment by MortenHofft** [comment]
closed with https://github.com/gbif/portal16/commit/3ccef06e782f17d3ddf6a3743706c9dde918c5d1
some work is still needed, but the core functionalities are there and all filters should be available
