### ISSUE TITLE
projections on maps

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#210]
The maps api supports multiple projections, but this isn't supported on the site. To do so we need basemaps (@MattBlissett have talked about building our own) and to implement switching it in the angular directive. it also raises questions about how to link to the occurrences  https://github.com/gbif/portal16/issues/135

There isn't any support for styles currently. That seems essential as we have it on the old page and hexagons aren't ideal for every situation

**Comment by MortenHofft** [comment]
There is no basemaps for any other projections that mercator. Since this isn't supported on the current site either, i will remove blocker. It is a huge improvement though and should have high priority

**Comment by kbraak** [comment]
Does it make sense to remove the projections button from maps in the meantime then? 
![screen shot 2017-02-27 at 10 31 40](https://cloud.githubusercontent.com/assets/5981100/23355885/08270b76-fcd8-11e6-9ad3-a136beca371f.png)
