### ISSUE TITLE
APIs status endpoint

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#216]
Many of the feedback issues we receive are related to temporary outages of our services. It would be very useful and provide for a much better user experience if we informed our users of known instabilities.
To do so we could implement a service that reported on the health of the system. I'm assigning you @MattBlissett as you have expressed that it should be a simple task :)

this should also test maps status

**Comment by kcopas** [comment]
+100!

**Comment by kbraak** [comment]
Thumbs up! Please try to implement the following related issues at the same time:

* [Show alert on dataset page whenever indexing is off - POR-2148](http://dev.gbif.org/issues/browse/POR-2148)
* [Show reason last crawl attempt failed on dataset page - POR-3087](http://dev.gbif.org/issues/browse/POR-3087)
* [Provide dataset validation/indexing report - POR-3051](http://dev.gbif.org/issues/browse/POR-3051)

Similarly, these also account for many of the feedback issues we receive.

**Comment by peterdesmet** [comment]
Yes please, similar to https://status.github.com/ and ideally accessible via an API (cf. GitHub).

**Comment by dgasl** [comment]
It would be so useful.

Any idea of how long this could take?

**Comment by MortenHofft** [comment]
There is now a health page. It is currently driven by the portal as there is no API to do so at the moment. That of course makes it useless if the portal also crashes. But that of course would also be the case if a dedicated health service crashed.

status page here https://www.gbif.org/health
non stable API here `https://www.gbif.org/api/health`

If there are issues they will also show as an alert on the site

![screen shot 2017-11-30 at 08 58 26](https://user-images.githubusercontent.com/6759267/33419868-a9517060-d5ac-11e7-9007-ee2c6480b15b.png)
