### ISSUE TITLE
Title missing in search for litterature

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#218]
Title seem to be missing from the api. Maybe we should remove items that are that incomplete?

https://demo.gbif.org/cms/search?type=literature&category_country=DK
![screen shot 2017-01-09 at 14 52 19](https://cloud.githubusercontent.com/assets/6759267/21768697/50e067a0-d67b-11e6-859b-8a25cfc03404.png)

**Comment by burkeker** [comment]
The same link appears to be showing title now.
