### ISSUE TITLE
3/4 programme pages return error 500

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#224]
The Living Atlases page is the only one of the four programme pages NOT returning error 500, internal server error—i.e. https://demo.gbif.org/programme/bid

**Comment by MortenHofft** [comment]
Hi Kyle. Yes, the CMS driven pages is very fragile these days. I believe that @burkeker is on top of it. I have also created these issues about it:
https://github.com/gbif/portal16/issues/217
https://github.com/gbif/portal16/issues/212
https://github.com/gbif/portal16/issues/213

**Comment by burkeker** [comment]
Well it's the fragile me. Fixed on dev. To be pushed to prod. https://demo.gbif-dev.org/programme/bid
