### ISSUE TITLE
infrastructure pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#226]
The infrastructure pages should be available on the new site.
How to best transfer them is to be decided. They are currently in Drupal but not available for search or display.
We could make one long technical document or reuse the tabs as we do on country and dataset pages /imitating the current layout).

**Comment by burkeker** [comment]
Some content work is needed, including updating them and perhaps restructure those.

**Comment by MortenHofft** [comment]
The infrastructure pages hasn't been transfered to the new site. They can be replicated as articles if needed. The tabs will, as on other pages not be possible, unless we do something extra. Last we discussed this it was decided to postpone developments of such until someone missed having them.

**Comment by dnoesgaard** [comment]
@MortenHofft - is this referring to http://www-old.gbif.org/infrastructure/summary ?

**Comment by MortenHofft** [comment]
yes - notice that not a single soul has asked for them since we launched. Not that i have heard of at least. Could be changed to a brief text and a video and a more technical pdf with all the details.

**Comment by dnoesgaard** [comment]
Part of it is available in this new piece:
https://www.gbif.org/data-processing

I don't know why we decided to make this part of the tools menu!

**Comment by dnoesgaard** [comment]
To be continued in https://github.com/gbif/portal-feedback/issues/1352

(please close this one)
