### ISSUE TITLE
Test HTTPS compatibility with old browsers

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#228]
I set up the HTTPS configuration to be pretty secure, it gets a good grade at SSL Labs: https://www.ssllabs.com/ssltest/analyze.html?d=demo.gbif.org

That may be "too secure", meaning we block too many XP users, or old Androids etc.  However, it may be that so many sites also block them, they are forced to upgrade anyway.

We need to investigate the statistics and see if there's a potential issue here.

**Comment by MortenHofft** [comment]
I have tested ie versions with virtual box

**failed**
ie9 windows7 fails
ie10 windows 7 fails

**worked**
ie10 windows 10 works
ie11 windows7 works

We have little support for ie8 and ie9 on the site as we make use of more modern css and js.

**Comment by MortenHofft** [comment]
IE10 windows 7 works for me
