### ISSUE TITLE
Feedback species page

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal16#229]
@MortenHofft Here are some hurried thoughts on the species page. The layout is nice and clean, but I think there is a fair bit of wasted space, and prominence given to things that are minor and/or for which GBIF has no data. There's some redundancy (e.g., classification as breadcrumbs and nested list). The gray box with things like source, IUCN, etc. takes up a lot of space for minimal content, what we do know could appear as a list below the species name. The source should go near the end. Needs an image of the the species, either from a source dataset or from, say, PhyloPic. In general I think tabular display of data should probably go below the fold, above the fold should be everything the user needs to know at a glance. In the example below, this is a trapdoor spider from Australia, this is not easy to work out from the page, but with an image, a common name, and the map centred on Australia, this would be very clear to the user.

![img_0052](https://cloud.githubusercontent.com/assets/83306/22017103/c487a94a-dca0-11e6-94a0-4761290fb334.PNG)

**Comment by thomasstjerne** [comment]
The Species detail page have been reworked with valuable input from this and other issues. I will close this as it refers to an older version of the page. Issues targetting the current version of the page are welcome.
