### ISSUE TITLE
Duplicate results in literature search

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#233]
"Darwin Core: An Evolving Community-Developed Biodiversity Data Standard" appears twice in https://demo.gbif.org/cms/search?q=Robertson&type=literature with both entries pointing at the same entity.

**Comment by timrobertson100** [comment]
Actually it looks like there are 20 results and all 20 appear on page 1 and page 2, so appears might be a bug in the paging?

**Comment by MortenHofft** [comment]
@dnoesgaard 
There's something odd about the pagination, e.g.

https://demo.gbif.org/cms/search?type=data_use

If you click page 2, nothing happens. Page 3, however, brings up new results, but then page 4 again appears to remain unchanged...

**Comment by burkeker** [comment]
Both are relevant to paging conversion to the param that CMS API accepts. Now the two cases in this issue work as expected on DEV:
https://demo.gbif-dev.org/cms/search?offset=0&q=Robertson&type=literature
https://demo.gbif-dev.org/cms/search?type=data_use
