### ISSUE TITLE
Omnisearch should show all content types for sprint 1

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#24]
The omnisearch will provide results for:
- datasets
- publishers
- occurrences
- data-use (and literature)
- programme 
- projects
- countries

During sprint 1 we will not implement participants or nodes

**Comment by MortenHofft** [comment]
and species

**Comment by MortenHofft** [comment]
it shows those that have been available. AS the cms api is evolved, the articles needs to be adjusted to new types and urls
