### ISSUE TITLE
Alternative design for citation and DOI on dataset page

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal16#242]
I like that both the citation and DOI are mentioned in the gray box at the top of the dataset page, but I find the current design with the two "labels" a bit ugly.

## Current version

![current](https://cloud.githubusercontent.com/assets/600993/22200351/0fa29134-e15f-11e6-98d3-ee3ce1336a03.png)

## Alternative version

![alternative](https://cloud.githubusercontent.com/assets/600993/22200352/0fb6a732-e15f-11e6-85e5-a713f707dc9d.png)

* I added another `dt dd` group, with the label "citation"
* I spaced all `dt`s evenly, so they line up vertically
* Instead of a label, I made the citation a regular link, which would point to the same location as now: the full citation at the bottom of the dataset page. It could be named "Full citation" or "How to cite this dataset"
* The DOI remains a label, but with enough padding on the left so it doesn't stick to the Full citation" link.

**Comment by MortenHofft** [comment]
I like the attention to details. Thank you. I'm still not to happy with this page overall I must admit, but may a lot of small improvements a la this one can bring it forward.

**Comment by rdmpage** [comment]
Just to be contrarian I like the "quote" label, it is consistent with other sites that try and get users to cite content, e.g. http://search.crossref.org (see below).

![screenshot 2017-01-25 06 26 21](https://cloud.githubusercontent.com/assets/83306/22280313/b70c1e2c-e2c7-11e6-8885-e859a12da382.png)

The CrossRef site also displays citations in a popup:

![screenshot 2017-01-25 06 31 30](https://cloud.githubusercontent.com/assets/83306/22280349/f4b8d09e-e2c7-11e6-84bb-d06306ac4300.png)

This supports multiple styles that users might want, at the moment GBIF has its own style that isn't terribly useful.

**Comment by peterdesmet** [comment]
I agree that providing the citation in multiple formats would be really useful. Maybe the link text should say "Cite this dataset" which then unfolds a box where a citation format can be chosen and copied. Also look at Zenodo for inspiration.

**Comment by MortenHofft** [comment]
I'd like to provide multiple citation formats. There has been some internal disagreement on the usage of this, but this is +2 for it. Thanks. This will also require some changes in the APIs and ideally do the same for downloads.

**Comment by rdmpage** [comment]
See my issue https://github.com/gbif/portal-feedback/issues/33 (which probably belongs here). CiteProc generates multiple citation formats (this is the same tool used by CrossRef, Zenodo, Mendeley, etc.).

**Comment by kbraak** [comment]
DataCite's [DOI Citation Formatting service](https://blog.datacite.org/citation-formatting-service-upgrade/), which uses [citeproc.js](https://github.com/juris-m/citeproc-js), can be used to generate a citation in various formats. For example, `https://citation.datacite.org/format?doi=10.15468/aomfnb&style=apa` returns a citation for the [eBird dataset](https://doi.org/10.15468/aomfnb) in APA style. 

The same thing can be done using DataCite's [DOI content negotiation service](http://citation.crosscite.org/docs.html), whereby the backend calls the DOI Citation Formatting service.  For example, `$ curl -LH "Accept: text/x-bibliography; style=apa" https://doi.org/10.15468/aomfnb` returns the same citation for the [eBird dataset](https://doi.org/10.15468/aomfnb) in APA style. Note this content negotiation service is currently in testing and goes into production 9 May. It is described in detail in [this blog post](https://blog.datacite.org/content-negotiation-update/).

**Comment by MortenHofft** [comment]
I'm closing this in favour of https://github.com/gbif/portal-feedback/issues/33 and will stick with the blue box - sorry Peter. Adding different version to download the citation sounds good to me.
