### ISSUE TITLE
DOI display redundant and DOI link broken

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal16#244]
On the dataset page the DOI link has a label "DOI" then the DOI itself has the "doi:" prefix, which seems redundant. The link is also broken, currently it is doi:10.15468/inygc6 which isn't a URL.

![screenshot 2017-01-25 06 32 51](https://cloud.githubusercontent.com/assets/83306/22280394/4bce9706-e2c8-11e6-8dcd-c9d13c24911f.png)

**Comment by MortenHofft** [comment]
Yes that shouldn't be like that. neither the double DOI nor the missing link. And there are more not properly resolved DOIs around I've noticed. Thanks for reporting.
