### ISSUE TITLE
Display paragraphs in dataset description

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal16#254]
Since one of the later versions of IPT, a dataset description can consist of multiple paragraphs. This is displayed correctly on a dataset page on the IPT (e.g. http://dataset.inbo.be/dagvlinders-natuurpunt-occurrences) and formatted as such in the EML:

```
<para>
...
</para>
```

On the dataset page on GBIF however, all paragraphs are lumped together in one big blob of text: https://demo.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa#description Can those paragraphs be kept?

**Comment by cgendreau** [comment]
This is working for all updates after deployment of registry-0.60 (2016-11-30).
I reinterpreted dataset 1f968e89-ca96-4065-91a5-4858e736b5aa

**Comment by peterdesmet** [comment]
Do you plan a complete update of the registry at some point?
