### ISSUE TITLE
Format URLs (and email addresses) in dataset description

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal16#255]
Currently, none of the URLs in dataset metadata (descriptions and other sections) are displayed as clickable links on the dataset page, see e.g. http://doi.org/10.15468/ezfbee on https://demo.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa#description

Note that this is correctly done on the current dataset page: http://www.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa and IPT http://data.inbo.be/ipt/resource?r=dagvlinders-natuurpunt-occurrences

The same could be one for email addresses, e.g. opendata@inbo.be in the description.

**Comment by MortenHofft** [comment]
you are right - it should - i have simply postponed it. thanks for the reminder. closed by https://github.com/gbif/portal16/commit/df024b9139f46cc5165d50061453ac3d12cf3848
