### ISSUE TITLE
Suggest-a-dataset not working

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#256]
Getting an error when submitting a form:

> This isn't good. We couldn't save your suggestion. Please try again later or alternatively go straight to https://github.com/gbif/data-mobilization/issues where the suggestions are managed

Mac 10.11.6, both Safari and Firefox

**Comment by MortenHofft** [comment]
My bad! For some insane incomprehensible reason I managed to delete the entire folder that should handle this!

**Comment by MortenHofft** [comment]
On the positive side - it crashed with grace

**Comment by kcopas** [comment]
+1 … ?
