### ISSUE TITLE
Implement a curated field in the CMS for featured search items

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#26]
When a user searches for e.g. "BID" or "Licenses" we wish to promote that to a prominent block in omnisearch.  This is currently mocked (try searching for "bear" in dev).
- [x] The CMS API should surface the means to implement this in the web layer

Content editors should be able to provide a list of terms that provide this functionality.  This is strictly controlled.  Terms should not duplicate across content items.  E,g. "license" should only be applied to 1 and only 1 object in the CMS to promote it - the CMS should enforce this to editors.  

This does not affect the behaviour that "license" will return several results, which are ranked accordingly, but this is specifically to dictate what gets featured.

This needs to be surfaced in the CMS API.
- [ ] From the Web UI, it should be demonstrated by accessing http://internal.gbif-dev.org/search?q=license

**Comment by burkeker** [comment]
All content types have such a term reference field as 6a79592. The rest would be on Search API.

**Comment by timrobertson100** [comment]
Burke - this appears ready to close doen's it?  e.g. "BID" illustrates this

**Comment by burkeker** [comment]
Closing this as it's been working as expected with BID and IPT.. , etc.
