### ISSUE TITLE
Feedback icon looks more like a chat box

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#262]
**Feedback icon looks more like a chat box**

Change the icon to something more intuitive so that users can easily recognize the feedback icon

-----
fbitem-publisher6fc06c4f-cbc6-408b-9d93-3061dfe015c9
Reported by: @siro1
System: Chrome 55.0.2883 / Windows 10 0.0.0
Referer: https://demo.gbif.org/publisher/6fc06c4f-cbc6-408b-9d93-3061dfe015c9
Window size: width 1536 - height 831
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T14:13:36.083Z',mode:absolute,to:'2017-02-06T14:19:36.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T14:13:36.083Z',mode:absolute,to:'2017-02-06T14:19:36.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Siro
I've changed it from bug to an idea as I do not really consider it a bug. Good that you found it anyway.

If you have suggestions for what the icon should be, then please provide it here. I know Burke agree with you and have suggested a bullhorn as attached.
![screen shot 2017-02-06 at 16 38 01](https://cloud.githubusercontent.com/assets/6759267/22653740/a7ee834a-ec8a-11e6-9a65-fa1e4c66b460.png)


Personally I think it a fine icon and a fairly standard one (see the attached Google search) and do not think that a chatbox/message icon is misleading. On the contrary. But I guess it is a matter of taste and associations.
![screen shot 2017-02-06 at 16 35 32](https://cloud.githubusercontent.com/assets/6759267/22653648/5c768070-ec8a-11e6-99b5-4548573d9315.png)

**Comment by siro1** [comment]
Mmm, may be try using one with the word "feedback" written in the icon?

**Comment by MortenHofft** [comment]
@siro1  Perhaps. Remember that it should be possible to translate that. What is feedback called in Swahili?

In danish it would be something along the lines of "Tilbagemelding". In german i believe it is "Rückmeldung". 

Point being that it could get very long. But that might also be ok. A bit odd on mobile perhaps. Do you have a suggestion for an icon?

**Comment by burkeker** [comment]
Bullhorn will be suitable I believe. http://getbootstrap.com/components/

**Comment by MortenHofft** [comment]
Given that we get as much feedback as on the previous site I guess people still know how to provide feedback. If someone have a specific suggestion and an svg and ideally an evidence based argument please reopen.
