### ISSUE TITLE
Drupal API doesn't expose all participant info (eg. history)

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#265]
The Drupal API expose the participant, but only some of the content. This is essential to have for the country pages. Ex: http://cms-api.gbif-dev.org/api/v1/gbif_participant/8513

**Comment by burkeker** [comment]
This is due to a content massaging error. Will fix it.

**Comment by burkeker** [comment]
The gbif_participant endpoint now uses participantId from Directory API for calling node information, e.g. http://cms.gbif-dev.org/api/v1/gbif_participant/2

And now the history, vision & mission as well as other textual contents are shown.
