### ISSUE TITLE
cms content type "news" doesn't expose Related GBIF resources

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#269]
Comparing old and new version of this news item:

OLD: http://www.gbif.org/newsroom/news/poland-becomes-voting-participant
NEW: https://demo.gbif.org/news/poland-becomes-voting-participant

the "Related GBIF resources" isn't shown on the new version. It is, however, shown in data use content, e.g. https://demo.gbif.org/data-use/newsroom/uses/2016-luizza-et-al

**Comment by MortenHofft** [comment]
This is still the situation but the page has changed so much since, that it would be nice with a confirmation that this is still something we should look into.

**Comment by dnoesgaard** [comment]
Actually, we do expose it now (secondary links). So happy to close this one.
