### ISSUE TITLE
Cache busting on assets

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#27]
Currently we do not version static assets. This of course needs doing before going live. And ideally before (second) release to uat.

**Comment by mdoering** [comment]
asset versioning implemented using the gulp-rev module: https://github.com/gbif/portal16/commit/4a3e140558e06adb6cbbc26ffe1ce41761f7bfe4

**Comment by MortenHofft** [comment]
Images fail to load as the image urls have been versioned but the referencing url hasn't
http://internal.gbif-dev.org/search?q=argentina

Same for page specific scripts
http://internal.gbif-dev.org/tools/species-lookup

**Comment by mdoering** [comment]
page specific script versioning should be fixed with last commit.
The country flags are dynamically included URLs, thats indeed a little tricky.

I suggest to create a nunjucks filter that will apply the manifest.json to convert asset filenames on server side page rendering for dynamic content

**Comment by mdoering** [comment]
Implemented a "flag" and a "rev" nunjucks filter to use the rev-manifest file versions and simplify the generation of a country flag image path

**Comment by MortenHofft** [comment]
We see 404s for http://demo.gbif.org/favicon.ico
I suspect that some browsers don't care much what we say about the favion but simply look for that specific filename.

**Comment by mdoering** [comment]
I have excluded the favicon.ico from asset versioning: https://github.com/gbif/portal16/commit/5f39cb0c423728f6a4454aba4abbee01dd1848ae

**Comment by MortenHofft** [comment]
Dev environment still have cached assets leading to errors after each build.

**Comment by MortenHofft** [comment]
[logs](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-05T07:17:11.536Z',mode:absolute,to:'2017-01-05T09:17:11.536Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22http:%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram) show that this is still an issue.

**Comment by MortenHofft** [comment]
We just had an issue with a build that all assets weren't versioned leading to a site without css. Doing a new build solved it. Maybe async calls that just happen to work most of the time? If it happens again we should revisit the asset versioning. Could also be one of those things that we test for in smoke tests?

**Comment by MortenHofft** [comment]
Closed with https://github.com/gbif/portal16/commit/371ee74b38fa921ca6e3a709bab6271cb4c0074e

We might consider simplifying this process to also make it easier to not cache stuff. But for now it will do
