### ISSUE TITLE
link downloads and articles

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#275]
@kbraak suggests here https://github.com/gbif/portal16/issues/65

Ideally we will begin maintaining a list of 'isCitedBy' relationships for the download hence we plan to monitor its usage in journal articles. Therefore I'd like to propose that if we know the download was used in a journal article that we provide a link to the article from the download homepage.

Special care should be taken to ensure that a download that has been cited gets protected against routine cleanup/deletions.

**Comment by MortenHofft** [comment]
I like that idea - if I understand correctly we do not have the data, data model or API to do so currently? So I guess it would be a concerted effort to get to this.

After that it sounds like a simple thing to implement in the front end. 
When that are in place, we can also ask the user to associate downloads to articles as suggested here: https://github.com/gbif/portal16/issues/274

![screen shot 2017-02-13 at 13 10 29](https://cloud.githubusercontent.com/assets/6759267/22896365/0e69bc4e-f220-11e6-9d33-26020b56e2a5.png)

**Comment by MortenHofft** [comment]
A simple way to proceed could be to simply create a Github issue when users linked a download to an article. Could be a crude test if anyone cares to add that linkage manually. And from there we could validate and put it into Mendeley. Obviously this wouldn't be the ideal solution.

**Comment by kbraak** [comment]
A great example of reciprocal linking taken from this [Elsevier article](https://www.elsevier.com/connect/bringing-data-to-life-with-data-linking) is described below:

> Elsevier and [PANGAEA](http://www.pangaea.de/) – Data Publisher for Earth & Environmental Science – have built an advanced linking service for Earth Sciences research; authors submitting papers to participating journals are encouraged to submit their raw data sets to PANGAEA, where they are archived and assigned a unique, persistent identifier. When the paper is published online, the reader will see an interactive map application that visualizes the geographical locations of the data sets at PANGAEA and offers links to the data records. Equally, the data set at PANGAEA is linked to the published article on [ScienceDirect](http://www.sciencedirect.com/).

To see how it works, view either [this dataset in PANGAEA](https://doi.pangaea.de/10.1594/PANGAEA.704574) or its corresponding [journal article](http://www.sciencedirect.com/science/article/pii/S0031018201004618).

I do think GBIF should start storing these linkages to papers in our registry for datasets and for downloads as soon as possible. In parallel we can start to explore how to make similar reciprocal linkages with journals, and explore external APIs that allow looking up papers linked to a dataset's DOI.  

---
![screen shot 2017-02-15 at 17 12 41](https://cloud.githubusercontent.com/assets/5981100/22983319/051d6f36-f3a2-11e6-8eef-d3e99aa11636.png)

@rdmpage @dschigel @MortenHofft

**Comment by kbraak** [comment]
Ideas captured above related to reciprocal linking are related to Implementation Plan items _1.d.viii_: "Provide clear online reporting of the use of data for data publishers" and _3.e.i_: "Develop scalable approach to support research journals and data journals in publishing to GBIF Network".

@ahahn-gbif @dschigel

**Comment by dschigel** [comment]
Came to my mind that a dataset demand map, country shading by N downloads per country, would be an interesting add-on to the dataset stats page - @timrobertson100 once did something like that for me and Siro. The impact/use map would looks like similar to journalmap.org or the Elsevier example above, papers detected through citation of GBIF DOIs as pins on the world map. Could be the same map, it would then show you attempted and successful uses in one view.

**Comment by MortenHofft** [comment]
This link is now provided when we have the data in mendeley.
There is no checking before deleting datasets, but it makes sense. That however isn't web related. Closing issue.
