### ISSUE TITLE
Feedback form doesn't work

### ISSUE THREAD

**Issue by kbraak** [gbif/portal16#279]
As per title. Please see evidence attached. 
![screen shot 2017-02-14 at 18 03 23](https://cloud.githubusercontent.com/assets/5981100/22939873/61e7a4ba-f2e0-11e6-970a-88b3a210cf09.png)

**Comment by MortenHofft** [comment]
That figures since I just asked you why you didn't use the idea option for your ideas 😄 
I'll look at it. thanks.

**Comment by MortenHofft** [comment]
Thanks. I have added country code labels to all created issues based on the users ip. I couldn't really test that on localhost and builds were off limit for me last weeks. I'm testing on UAT and will do a prod build if it works. thanks :)
