### ISSUE TITLE
Problems with explore occurrences feature on dataset page

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#283]
from @kbraak https://github.com/gbif/portal-feedback/issues/85

At global zoom level, when you press the explore occurrences icon beside the map, the resulting occurrence search doesn't include all occurrences that were view on the map. I suspect this is a problem with dateline handling.

**Comment by MortenHofft** [comment]
This is the same issue on the existing site. Some of this is fixed on the dev API, but not it all it seems. Once there is clear guidelines for how to address the API I can update the maps to match the newest version.

**Comment by MortenHofft** [comment]
Hi @kbraak I have created an issue on the occurrence search API. you can follow along there: https://github.com/gbif/occurrence/issues/13

**Comment by kbraak** [comment]
Thanks a lot @MortenHofft

**Comment by MortenHofft** [comment]
as a workaround for now the map widget links different places depending on zoom level. if you see more than half earth (this is where the api fails) it links to everything. less it links to the bounds. Button changes text accordingly. It isn't perfect, but is better at least.

![screen shot 2017-06-21 at 17 16 55](https://user-images.githubusercontent.com/6759267/27391937-8de3ece4-56a5-11e7-9202-534efd15ed4c.png)

![screen shot 2017-06-21 at 17 17 04](https://user-images.githubusercontent.com/6759267/27391943-91128e0c-56a5-11e7-8302-adde37b81e7f.png)

 I will close this issue as it is an API one and is created there.
