### ISSUE TITLE
cms urlhandling fails with 500 on /countries

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#286]
I haven't looked into the reason, but I see that this url fails: https://demo.gbif.org/countries with error 500

```
Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at cmsData.cmsEndpointAccess.then.body 
```

**Comment by burkeker** [comment]
Some clarities needed here. We have /country showing the list of countries, which I believe should be replaced by /the-gbif-network. And, does /countries point to anything? Otherwise we should do redirect.

**Comment by burkeker** [comment]
As the result of discussion, /country will be redirected to /the-gbif-network, /countries should return 404.
