### ISSUE TITLE
Prefer showing verbatim occurrence data, rather than interpreted data

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#29]
The current portal shows interpreted data, and hides verbatim data on a separate tab.  The new portal is bringing the verbatim data to the same page, but I think we should consider something more radical:

For some fields, primarily the taxonomy, show the data provider's verbatim data, and give less prominence to our interpretation.

This would be especially useful where we have matched to a higher taxon, made a fuzzy taxon match, or made no match at all.

We should look at our data and see what the effect of this would be.  We have good occurrence data which is linked to a poor part of the taxonomic backbone (looks bad for the data provider), but we also have poorer occurrence data which is improved by showing the interpreted name.

**Comment by thomasstjerne** [comment]
closed by https://github.com/gbif/portal16/commit/6b459a6db217e75d6e6fac8ac999a04929f893ec
