### ISSUE TITLE
Caching on incomplete downloads

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#292]
When initiating a download it seems wrong that the html response is cached as long as the download is preparing or running.
What are the options for telling varnish not to cache? This is also useful for partial search results for example.

**Comment by MattBlissett** [comment]
Varnish seems to be passing on the `maxage` directives you've set in Dev.  You can also set `s-maxage` to tell Varnish to cache something for a different time to the user's browser, which may be useful on occasion:

```
Cache-Control: public, s-maxage=30, maxage=60
```

This would tell Varnish to cache the page for 30 seconds, and the browser to cache it for 60.
