### ISSUE TITLE
Make region pages

### ISSUE THREAD

**Issue by kbraak** [gbif/portal16#293]
_Copied from [Issue POR-2155](http://dev.gbif.org/issues/browse/POR-2155):_

> From a.heughebaert@biodiversity.be 04/Jun/14 
> 
> _As regional representative, I would be delighted to see same pages/figures per Region._

---
Indeed GBIF.org v1 provided information on the regional self-organization of Participant Nodes. It included:
* a list of all regions with a primary contact for each one
* a page for each region listing its member countries and organizations and regional activities. 

**To see what these pages looked like, please see the screenshots below.**

---
Other Jiras related to this:

* [Add regional reports - POR-2155](http://dev.gbif.org/issues/browse/POR-2155) 
* [Regional view of participants (restore old portal functionality) - POR-1811](http://dev.gbif.org/issues/browse/POR-1811)
* [Regional node contact lists: decide where to display, implement - POR-1584](http://dev.gbif.org/issues/browse/POR-1584)
* [Show additional content on Network page - POR-1516](http://dev.gbif.org/issues/browse/POR-1516)

Other GitHub issues related to this:
* [The GBIF Network page](https://github.com/gbif/portal16/issues/69)
* [Include Funder Information](https://github.com/gbif/portal16/issues/258)
* [GBIF participant page (i.e. country pages)](https://github.com/gbif/portal16/issues/70)

---
![regionalnodes_oldportal_activities](https://cloud.githubusercontent.com/assets/5981100/23170826/eea5aa80-f850-11e6-86be-dc467c8fce1e.png)

---
![regionalnodescontacts_oldportal_africa](https://cloud.githubusercontent.com/assets/5981100/23170828/eea7565a-f850-11e6-9e8d-426ca563ade6.png)

---
![regionalnodescontacts_oldportal_asia](https://cloud.githubusercontent.com/assets/5981100/23170827/eea6d356-f850-11e6-8cfa-92b1ab7dc002.png)

---
![regionalnodescontacts_oldportal](https://cloud.githubusercontent.com/assets/5981100/23170825/eea47976-f850-11e6-9927-0639a197d7fc.png)

**Comment by kbraak** [comment]
As @kcopas points out initial implementation of the regional pages are available via tabs on the GBIF network, i.e. https://demo.gbif.org/the-gbif-network/africa#

What's left to do @andrejjh? How about: 
* a description for each region
* a list of the region's events (meetings, workshops, etc)
* a list of the region's funding opportunities

**Comment by andrejjh** [comment]
I'll ask the Regional representatives about that.
But I'll suggest that all events of interest will (automatically?) be flagged with the appropriate region.
Apart from a list of Funding opportunities, I'd like to see large regional projects/initiatives dealing with biodiversity data.

**Comment by andrejjh** [comment]
Israel not part of Europe, normal?

**Comment by kbraak** [comment]
Thanks @andrejjh, 

I'm bringing your comments to the attention of @burkeker who is implementing this work. He will get back to you next week regarding Israel when he returns from vacation. 

We certainly look forward to more feedback from the other Regional representatives, thanks.

**Comment by kcopas** [comment]
As I also mentioned to @kbraak , there are some small issues, like making sure that out-of-IPBES-regional members (i.e. Israel, Mexico (I think)) appear in the proper GBIF regions. 

Events are already tagged in the content management system but not yet displaying—I would expect that implementation to be relatively straightforward.

Neither funding opportunities nor projects are currently part of the content model, so they will likely need to be deferred, at least for this v1 implementation.

**Comment by kbraak** [comment]
@kcopas @andrejjh As per [Issue POR-2681](http://dev.gbif.org/issues/browse/POR-2681) Israel previously asked to be linked to the GBIF Europe Region - I wonder if this is still applicable?

**Comment by MortenHofft** [comment]
It is possible to add some of this data to the [network pages](https://www.gbif.org/the-gbif-network/africa) but currently there is very little information. We could expand the content model if needed. But for now it seems a content issue.

> African Region
>Below is a list of all participants in Africa including membership status and summary of data published in GBIF.

**Comment by kcopas** [comment]
We've restored the basic functionality (lists and contacts) for each region, while putting the question to the nodes as to what additional content would be appropriate. 

Considered complete in the absence of additional input, I believe.

**Comment by MortenHofft** [comment]
Add UN Regions taxonomy to GBIF.org  [jira](http://dev.gbif.org/issues/browse/POR-2538?jql=project%20%3D%20POR%20AND%20status%20%3D%20Open)

Idea for consideration.
Thinking ahead into the development of regional pages, consider using two regional taxonomies: GBIF administrative regions (complete with its participatory quirks), and UN macro regions (and subregions), listed here: http://unstats.un.org/unsd/methods/m49/m49regin.htm
If justified by use cases, we could use these to allow the user to how they'd like to define the views of GBIF and GBIF-mediated data by region.

**Comment by kcopas** [comment]
If we were to introduce additional regions, it should not simply be UN regions. Instead, we should make use of the synchronized/harmonized UN/IPBES regions and subregions described in this data paper, Brooks et al. (2016) [doi:10.1038/sdata.2016.7](http://dx.doi.org/10.1038/sdata.2016.7). 

We've already used this to provide more consistent assignment of non-Participant countries to GBIF regions. But doing so in any further implementation would permit us to align with the full range of most commonly used intergovernmental regions while maintaining more consistent (and, where possible, dynamic) reporting against the same, as these are the kinds of things for which we're already asked to produce custom downloads and ad hoc reports.

**Comment by kcopas** [comment]
Idea in above comments moved to #706 —separate issue/idea
