### ISSUE TITLE
download page should inform about the download being in process and which mails will be notified

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#298]
**How to download data????**

When i try to download data, is there some error...

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: setebuenavista@gmail.com
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?taxon_key=7952072
Window size: width 1366 - height 659
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T19:14:27.245Z',mode:absolute,to:'2017-02-24T19:20:27.245Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T19:14:27.245Z',mode:absolute,to:'2017-02-24T19:20:27.245Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
@kbraak writes
On the current portal, after triggering a 'download' a notification box appears at the top of the download page with the following text:

> Download running
> The download has been started and is currently being processed.
> Please expect 10 to 15 minutes for the download to complete.
> A notification email with a link to download the results will be sent to the following addresses once ready:
>     email@address

As far as I can see this information is missing from the new portal. It is quite important to the user at it explains how and when they can retrieve the download. 

![screen shot 2017-02-27 at 10 52 36](https://cloud.githubusercontent.com/assets/5981100/23356727/3e50fd6c-fcdb-11e6-96fe-dee1facbcc4f.png)

**Comment by kbraak** [comment]
@MortenHofft IMHO issues such as this that prevent the user from understanding how to download  data successfully should be a release blocker

**Comment by MortenHofft** [comment]
Hi Kyle thanks for your comments - it should of course be there. And is now.
