### ISSUE TITLE
Drupal timeouts

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#3]
Drupal runs a job every 3 hours that leads to timeout on requests. This has been less of an issue in the past as many Drupal pages have been cached. But as we now use it for all omni searches, the timeouts become relevant again.

**Comment by burkeker** [comment]
- [ ] Long cron jobs should be handled better. They include synchronisation of Mendeley references and indexing of resources and nodes.

**Comment by burkeker** [comment]
Cron jobs have been configured to run periodically by periodic system cron, rather than be triggered by http request. There shouldn't be any timeouts from Drupal. If so, please re-open this issue.
