### ISSUE TITLE
/participant/[participantId] for non-country participants

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#305]
https://github.com/gbif/portal16/blob/f2d954dfe1a8f5a60d88651795bb16668902813e/app/controllers/node/key/nodeKey.ctrl.js#L20

I am not sure if there is any discussion about the URL for non-country participants, but IMO we should use /participant/[participantId] in the new site and redirect the /node/[UUID], because the later has caused confusion and is still confusing.

**Comment by MortenHofft** [comment]
Sounds reasonable to me, There is something odd about it saying node in url and participant on title. All in all something to make those pages and the structure more transparent seems useful
