### ISSUE TITLE
Chapter title is covered by tabs

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#306]
https://demo.gbif.org/dataset/8df9af24-1fbd-4699-a545-9a2867ff25fe#description

The anchor point should be adjusted so the chapter title "description" is shown.
![screenshot 2017-03-01 14 49 35](https://cloud.githubusercontent.com/assets/637631/23462540/8b35b898-fe8e-11e6-97fc-942418d920e6.png)

**Comment by MortenHofft** [comment]
odd that it is only the case for the first paragraph

**Comment by MortenHofft** [comment]
fixed
