### ISSUE TITLE
Image styles for various device widths

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#31]
The images served from drupal should accommodate the needs of the data-use page and other places.

http://internal.gbif-dev.org/data-use/page/11343

As the device width changes the banner image may not shown in the best crop. A few more dimensions will offered from the API will improve viewing experiences with proper proportions and resolution.

**Comment by burkeker** [comment]
Now the maximum size of prose image is 1250x275 "masthead_desktop", and an extra style prose_image_for_desktop for the 965x400 cropped version. Committed as https://github.com/gbif/gbif-drupal/commit/77a95133b812f2cc72ddfc56a7c85a12e17ed383

**Comment by MortenHofft** [comment]
the style "prose_image_for_desktop" is not available on all header images. 
NOT on http://demo.gbif.org/data-use/page/151.debug fx
It IS on http://demo.gbif.org/generic/tools/species-population.debug
But it isn't 965x400. instead it is 1920x1040

The style "masthead_desktop" isn't an ideal ratio as we do not use images that wide and narrow anywhere. What we need currently is simply a style that matches that of the data-use/news etc pages. That way the users do not download an image 4 times as big as the one they maximum need for their desktop experience. Later we can consider having dedicated mobile styles, but for now adding a style would be a simple and large improvement.

We could do this through the image cache, but since we have Drupal and the option to select a focus area when cropping it makes sense to use that I would think.

**Comment by burkeker** [comment]
Thanks for this, @MortenHofft. I've cleaned up the styles for portal16 project from the CMS API side following the current usage. As the result, prose_image_for_desktop and focal_point_for_news are confusing and no longer used. Instead we have "header_image" (1170x422) and "inline_header_image"(740x400) with the dimensions specified by you in the template earlier. I've also updated all templates to match the new style keys. The focus and crop works only with specified style, rather then the original.

Please review and when you're happy with the change, close this issue.

**Comment by MortenHofft** [comment]
I trust that you have done the testing. I have looked at a couple of images and it looks just fine. thanks.
