### ISSUE TITLE
Dataset page: Links to "occurrences" and "species" are not working

### ISSUE THREAD

**Issue by cgendreau** [gbif/portal16#312]
Links to "occurrences" and "species" are not working

From the dataset page, if we click on "occurrences" or "species" we get a 404.

fbitem-dataset8d431c96-9e2f-4249-8b0a-d875e3273908
Reported by: @cgendreau
System: Chrome 56.0.2924 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/dataset/8d431c96-9e2f-4249-8b0a-d875e3273908/

Moved from https://github.com/gbif/portal-feedback/issues/125

**Comment by cgendreau** [comment]
Actually, it points to
https://demo.gbif.org/dataset/occurrence/search?dataset_key=8d431c96-9e2f-4249-8b0a-d875e3273908

while it should points to https://demo.gbif.org/occurrence/search?dataset_key=8d431c96-9e2f-4249-8b0a-d875e3273908 (without the dataset/ part)

**Comment by cgendreau** [comment]
From https://github.com/gbif/portal16/blob/master/app/views/pages/dataset/key/metrics/metrics.nunjucks#L69 :
`<a href="../occurrence/search?dataset_key={$ dataset.record.key $}"`

If we land on the page with an address ending with a slash like the one used above, it will resolve the wrong URL.

**Comment by kbraak** [comment]
@MortenHofft IMHO this and other broken links should be labelled as release blockers

**Comment by MortenHofft** [comment]
Hi Kyle - thanks for your comment - this is of course fixed.
