### ISSUE TITLE
Display ORCIDs in accordance with ORCID guidelines

### ISSUE THREAD

**Issue by kbraak** [gbif/portal16#314]
Display the ORCID iD with the iD icon, following [ORCID guidelines](https://orcid.org/trademark-and-id-display-guidelines) to create a consistent user experience and help associate the iD icon with a trusted assertion process (should GBIF begin validating them). This also helps familiarize all researchers with the ORCID iD icon so they recognize it, and are encouraged to register and use their own iD when publishing their own data.

![screen shot 2017-03-20 at 12 31 24](https://cloud.githubusercontent.com/assets/5981100/24098118/34fa308c-0d69-11e7-96cd-f02a3a7f6ab3.png)

**Comment by MortenHofft** [comment]
will be available in next prod build- since we are more or less offline it won't be visible just yet

**Comment by MortenHofft** [comment]
![screen shot 2017-06-21 at 16 00 40](https://user-images.githubusercontent.com/6759267/27388086-ce08d5ec-569a-11e7-9508-a3aa59b1a86a.png)
