### ISSUE TITLE
Contributor's ORCID missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#318]
**Contributor&#39;s ORCID missing**

The contributor&#39;s ORCID is already shown on the current portal, e.g. see Kyle Braak here: http://www.gbif.org/dataset/647ae6f8-8e26-4189-b448-02b45b7ad884

**Related issues:**

https://github.com/gbif/portal16/issues/314 - how to properly display ORCIDs
https://github.com/gbif/portal16/issues/315 - promoting the use of ORCIDs
https://github.com/gbif/portal-feedback/issues/132 - searching datasets by ORCID

-----
fbitem-dataset647ae6f8-8e26-4189-b448-02b45b7ad884
Reported by: @kbraak
System: Firefox 52.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/dataset/647ae6f8-8e26-4189-b448-02b45b7ad884
Window size: width 1219 - height 885
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-20T11:18:44.638Z',mode:absolute,to:'2017-03-20T11:24:44.638Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-20T11:18:44.638Z',mode:absolute,to:'2017-03-20T11:24:44.638Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by rdmpage** [comment]
Am I missing something because I don't see Kyle's ORCID in the old port page anywhere?! It's in the EML, but not the actual web page.

**Comment by kbraak** [comment]
Please see this screenshot of the current portal:

![screen shot 2017-03-21 at 11 51 08](https://cloud.githubusercontent.com/assets/5981100/24144203/bdb24108-0e2c-11e7-9c8c-5e29951a3782.png)

**Comment by rdmpage** [comment]
Hmmm, this is not what I'm seeing in Safari 10.0.2 on my Mac, which looks like this :

![screenshot 2017-03-21 11 02 32](https://cloud.githubusercontent.com/assets/83306/24144694/1843652c-0e26-11e7-83ef-6b701f08917e.png)

Likewise Safari on my iPhone (iOS 10) doesn't show the ORCID, but I do see it in Chrome on my Mac. Maybe time for some browser compatibility checks?

**Comment by MortenHofft** [comment]
it is very well hidden i'm afraid. you have to click the name.

**Comment by rdmpage** [comment]
But not on Chrome!? The details appear by default in that browser.

**Comment by rdmpage** [comment]
Whoa, now when I look at the page in Chrome the details have vanished and I have to click on the name (like Safari)!

**Comment by MortenHofft** [comment]
Hi Kyle - your orcid is now there 
Thanks
