### ISSUE TITLE
Dataset page tidy up

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#32]
Tidy up the dataset page with the following (many of these may come back in different design in the future):
- [x] remove logo
- [x] make “published by … ” one line similar to “collected in” on the occurrence page
- [x] make the title link to the GBIF publisher stub page and remove CC BY NC logo
- [ ]  add a key value pair block similar to occurrence header with:
    i. occurrence records (or equivalent for checklist)
    ii. georeferenced records
    iii. published date
    iv. dataset homepage
    v. download link, linking to source DwC-A if it is a DwC-A dataset
    vi. the license and logo
- [ ] remove the stuff under the map with metadata language etc (for now) and replace it with a “About the dataset” with the description text to be consistent with the occurrence page.  Note the font size on “About the dataset” should be the same as the occurrence page
- [ ] remove Description from the sub-menued block
- [ ] only do a sub-menu layout if there is more than a (?) full page height (on a 15” macbook pro screen) of data, otherwise just print it - a menu is not needed for many of the pages
- [x] remove the data use static block
- [ ] Add a “(Note: section to be revised)” in a subtle text under the Download events and under the map 
- [x] Change the font size of all the headings like “Download events” and “Gbif Registration” to be the same as “About the dataset” on the occurrence page
- [x] perhaps consider a more subtle colour for the registration info - it kinda looks like the most important part of the page when open

On the author stuff at the top:
- [ ]  Make sure all the author roles are present - many show as undefined (bug?)
- [ ] When expanded indent the 1,2,3,4,5 so it is a few pixels right of the first author
- [x] stop the superfix 1,2,3 etc on the author from being part of the <a> - only the name in the header should be part of that
- [x] use the same map base layer and attribution as the occurrence page
- [x] add scale (500m, 1Km etc) to the map, similar to the occurrence detail map
- [ ] adjust the width to be consistent with the occurrence page
- [x] adjust font for paragraph text to be consistent with occurrence page

**Comment by MortenHofft** [comment]
Suggestions for contact area: 
* naturally don't show undefined.
* show name or organisation in bold. Which ever comes first. if neither is specified, then don't show contact at all.
* Make all contacts the same width. Bottom row is wider as seen in screen shot
* If there is a gazillion contacts hide and expand similar to http://devnode-vh.gbif.org:3000/occurrence/1100006114 images. Don't hide only one or a few contacts in the expanded area. It is annoying to press more and get one result. Then we could just have shown it in the first place. * Proper markup for phone numbers so you can actually call them.
* I wouldn't bother making phone and email an abbreviation. Just write phone. as for email, it is hardly an abbreviation, and the title just shows the same anyhow.
* might be nice to keep the email on the same line as the label and wrap it. Or maybe just leave out the label altogether. I would imagine the context and the format was enough information for people to know it was an email.
![screen shot 2016-07-06 at 11 58 24](https://cloud.githubusercontent.com/assets/6759267/16614580/5a0e7a16-4372-11e6-832c-438942fc22ff.png)

**Comment by burkeker** [comment]
- [ ] Related news section style in various devices.
