### ISSUE TITLE
Show verbatim scientific name for higher rank matches

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#321]
**Show verbatim scientific name for higher rank matches**

If the occurrence scientific name cannot be matched to our backbone or just to a higher rank we should show the verbatim scientific name in the header of the record

-----
fbitem-occurrence1438476539

System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/occurrence/1438476539
Window size: width 1616 - height 939
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T09:25:46.284Z',mode:absolute,to:'2017-03-08T09:31:46.284Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T09:25:46.284Z',mode:absolute,to:'2017-03-08T09:31:46.284Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 4ed70d4f-2ae9-4762-ad7f-f9d7bf2bee68
publishingOrgKey: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by MortenHofft** [comment]
@mdoering @dschigel @rdmpage is this something everyone agrees on? It will still show as the backbone name in search. That might seem a bit odd.

**Comment by mdoering** [comment]
We should indicate this is the verbatim name and not a backbone taxon. If it can be distinguished I think this is good!

**Comment by MortenHofft** [comment]
Based on a skype conversation last month with mdoering and thomasstjerne , this is what we now show in cases where the names aren't identical. Keeping the interpreted name in the header, but showing the verbatim name just below.

![screen shot 2017-06-22 at 08 37 20](https://user-images.githubusercontent.com/6759267/27420440-29e3943e-5726-11e7-8bb4-8204970f11dc.png)
