### ISSUE TITLE
Include terms of use.. and guidance on how to comply with them

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#333]
**Include terms of use.. and guidance on how to comply with them**

Include terms of use ([data use agreement](http://www.gbif.org/terms/data-user)) in download dialog and download page. 

The aim is to remind users that they must give appropriate attribution to the author(s) of the data in any publication that uses data downloaded from GBIF.org.

To help users comply with the terms of use, it would be helpful to show them what license(s) are applicable to the records they are about to download. If occurrence records without a license are included in the download, the user should be encouraged to exclude these from their data by filtering them out. Note there are still  141,761 occurrence records without a license. Note https://github.com/gbif/portal16/issues/277 also highlights the need to show the license on the download page.

-----
fbitem-7a5f0274842c6a31410c82371c6295b6c1df2f7e
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/occurrence/download/0063196-160910150852091
Window size: width 1381 - height 1006
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-22T13:22:01.083Z',mode:absolute,to:'2017-02-22T13:28:01.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-22T13:22:01.083Z',mode:absolute,to:'2017-02-22T13:28:01.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
I don't think we should include records without a license in the download. We should simply fix (or delete) the 141,761 occurrence records without a license.

**Comment by MortenHofft** [comment]
Adding terms of use link on the page of the individual download is trivial of course.
cleaning the data is another issue.

as for 
> To help users comply with the terms of use, it would be helpful to show them what license(s) are applicable to the records they are about to download

this is already done if I understand the comment correctly?
![screen shot 2017-03-21 at 09 18 05](https://cloud.githubusercontent.com/assets/6759267/24138143/53e88bc0-0e17-11e7-967e-0c1ef62995a2.png)
it does however show as cc0 if unspecified. this might not be what we want. I tend to agree with Chris that they should be removed of there license cannot be cleaned up, but that is up to @ahahn-gbif  I guess?

btw there are 301,832 occurrences without a license.

**Comment by ahahn-gbif** [comment]
- I agree that records without a license should not be included in downloads. 
- If we go for a default, it should be CC-BY (not CC0), as for the other datasets. This would need a follow-up consultation with checklist publishers, though. Will check how to proceed. 

Concerning the cleaning up, these records should now all be records coming in with checklist datasets (for which mandatory licensing had not been enforced). We have confirmation from Pensoft that all datasets will are CC-BY 4.0 , and with Plazi that all datasets are CC0. If there are others, more checking is needed, otherwise these could be updated.

**Comment by MortenHofft** [comment]
* License added to download page by https://github.com/gbif/portal16/issues/562
* Info about data user agreement and citation guidance added to download page. https://github.com/gbif/portal16/commit/110438e16b126d0843583f3c6bde983da6479c35
* Adding the links to the download page is created as a task to do for comms https://github.com/gbif/portal16/issues/561
* Cleaning dataset licenses is as I understand it a separate issues.
