### ISSUE TITLE
Terms of use and other pages missing from Drupal

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#337]
I would expect a [search for 'terms of use'](https://demo.gbif.org/cms/search?q=terms%20of%20use) to return a result with the terms of use. It doesn't at this point. Trying to use the existing url doesn't work either. It seems that not all content is available through the API. Is terms of use for example exposed at all?

**Comment by kbraak** [comment]
Related issue, is to ensure the terms of use are included in / referenced from download dialog and download page - https://github.com/gbif/portal16/issues/333

**Comment by MortenHofft** [comment]
not relevant anymore as  we moved to contentful
