### ISSUE TITLE
Image requests to Arctos Database frequently blocked

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#343]
GBIF staff can see http://elk.gbif.org:5601/goto/edca543f4345fb14a12134891d421107

Many requests to Arctos Database images are blocked, we receive the error "Your IP or organization has been blocked. You may wish to check your computer for malicious software and alert others who may have accessed Arctos from your IP or organization. Further intrusion attempts may result in more restrictive blocks."

The image server's IP is 130.226.238.222.

I contacted them in October, and some blocking was due to requests to old URLs.  Anything that's not of the format http://arctos.database.museum/media/10006173?open could be an issue.

**Comment by MattBlissett** [comment]
Example collection: https://demo.gbif.org/occurrence/gallery?dataset_key=39f7ffd7-9416-4efb-934a-c81f116893fc

**Comment by MattBlissett** [comment]
Part of the problem is links to an obsolete API, which we shouldn't be accessing, except we have duplicate occurrences.

@cgendreau or @timrobertson100, is it easy to run a deletion on 39f7ffd7-9416-4efb-934a-c81f116893fc? That seems to be the only dataset with old records using their old API.

**Comment by timrobertson100** [comment]
running now

**Comment by MattBlissett** [comment]
We've been unblocked.

We sustain over 500Mb/s, peaking at 1Gb/s, when asking for more and more images on that dataset gallery.  That's impressive (coming all the way from Texas).
