### ISSUE TITLE
Non-country participant list on network page is inaccurate

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#345]
I know this is long-standing and probably will be superseded by another whack at the network page, but the list of "other" associate participants shows 22 organizations, rather than the 40 we still have:
[https://demo.gbif.org/the-gbif-network](https://demo.gbif.org/the-gbif-network)

**Comment by kcopas** [comment]
Hoping I'm not being presumptuous assigning this to you, @thomasstjerne !

**Comment by thomasstjerne** [comment]
It should be corrected in current version on dev
