### ISSUE TITLE
image cache support for DNG format

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#348]
Some of our publishers publish using DNG. The images are fine, but large (14mb fx). The image cache currently returns 500 errors.

https://demo.gbif.org/occurrence/gallery?dataset_key=39f7ffd7-9416-4efb-934a-c81f116893fc

Any suggestions for we should handle these? Even if we get the image cache to work with these they are likely to be very slow. 

If i remove them client side, it will be difficult to show galleries.
In above example it will show 73,121 results and only show 1.

It could also be considered a data issue and we could contact publishers to suggest jpgs to save bandwith for everyone and in addition having the DNGs for those with high res needs

**Comment by MortenHofft** [comment]
Actually it looks like we do support DNGs in the image cache, since one image works that is also a DNG - maybe they just block us because we ask for so many pictures at once?

**Comment by MattBlissett** [comment]
Duplicates #343 .
