### ISSUE TITLE
project status text field

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#349]
In Contentful for projects, the project status is a free text field. I put "In progress", but I get CMS.PROJECTSTATUS.IN PROGRESS on the new portal.

Example:
http://portal.gbif-uat.org/project/1xSwFsED9OQWoqcKY6MaUw/compiling-a-multi-language-gazetteer-for-occurrence-distribution-in-asia

Not sure if we wanted this to be controlled or not.

cc @kcopas

**Comment by MortenHofft** [comment]
Currently i have assumed enumeration, but the contentful content template need to be configured to not allow free text input. but the contenttype is the same, so for structured fields we have postponed setting up the restrictions on the field. An enumeration seems like a good diea i would think? makes it easier to translate it

**Comment by dnoesgaard** [comment]
KC and I just agreed on this list. OK?

1. Approved
2. In progress
3. Complete

Can we change the field in Contentful to an equivalent drop-down?

**Comment by MortenHofft** [comment]
Easily. I can show you later. But it will be overwritten at final export so that is why we have postponed all field restraints. In theory it could be part of the script but that has been decided to be a separate step. It is trivial. I'll be at the office soon.

**Comment by dnoesgaard** [comment]
Ah gotcha.

@kcopas, if we do manual edits/creations of projects in Contentful, just stick to these values (exactly as written, all caps, and we'll be ok:

APPROVED
IN_PROGRESS
CLOSED

/Daniel

**Comment by dnoesgaard** [comment]
(and I fixed the one project that had the issue)

**Comment by MortenHofft** [comment]
I have added the contraint in the contentful content model
