### ISSUE TITLE
Columns on homepage - Chinese 

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#350]
The columns used in the About GBIF descriptor work reasonably well in English and presumably other latin-alphabet languages:

![screen shot 2017-06-09 at 10 22 34](https://user-images.githubusercontent.com/21358085/26967230-c6d3df84-4cfd-11e7-8fbf-690ce3e01f65.png)

However, it doesn't work as well in Chinese:

![screen shot 2017-06-09 at 10 22 43](https://user-images.githubusercontent.com/21358085/26967250-d2445eb6-4cfd-11e7-972b-d78a29a99dd9.png)

This was confirmed by @Maofangisme who kindly provides the translations.

**Comment by MortenHofft** [comment]
I've changed it to be a single column https://github.com/gbif/portal16/commit/2b828c11a970d0277335499cc1ea2db71d24f811

will be in next deploy
