### ISSUE TITLE
project page layout

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#353]
From a conversation with Maheva regardin project pages:
https://demo.gbif.org/project/82632/african-insect-atlas

> * Co Funders are too hidden. Perhaps a full tab for funders.
> * Partners and links should be displayed as on the old site - it looks nicer and takes up less space.
> * General comment: images don't look nice when they are cropped that way. It would be better with ratios as on the existing site as seen here: https://demo.gbif.org/project/82741/capacity-building-and-biodiversity-data-mobilization-to-address-health-and-food-security-priorities-in-benin
> * the side bar we have ion the existing site works well for displaying the co-funders prominently. that could also be an option.

Current site
![screen shot 2017-06-14 at 15 08 21](https://user-images.githubusercontent.com/6759267/27133783-ae7ee680-5113-11e7-9cf5-d81bfdfea4dd.png)

New site
![screen shot 2017-06-14 at 15 10 13](https://user-images.githubusercontent.com/6759267/27133782-ae7d75e8-5113-11e7-8e04-45bdc2e8fc05.png)

That is fine by, me. Personally I like the card links, but if the core users don't, then I'm good with changing it. Should events also be shown as on the old site?

**Comment by MortenHofft** [comment]
@dnoesgaard and @kcopas can you confirm that this is what we should do please

**Comment by dnoesgaard** [comment]
We'll discuss this, align expectations within Comms and Admin, and then get back to ya, yeah?

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/portal16/issues/93

**Comment by dnoesgaard** [comment]
Summarizing the points made at our meeting with Admin yesterday:

Programme page - list of projects
- [ ] (Firefox on Windows) if from lists of projects you go to a project and hit browser back button, you don't go back to list of projects
- [ ] Add Region / call to list of projects (I don't believe we have region, but call will achieve the same
- [ ] Daniel to make that that all project are associated with call)

Project page
- [ ] links on project page - perhaps move to separate tab? or somehow less dominant - perhaps based on number of links, e.g show 2-4 links on main page, move to separate tab? 
- [ ] Lead Participant (or partner) contact details ? should probably be removed / not shown (@kcopas to check with Tim R)
- [ ] co-funders need a more prominent placement than way in the bottom (almost looks like a footer)

@MortenHofft, let's chat when you're back from your vacay...

**Comment by MortenHofft** [comment]
Thanks

programme page first.

back button: this is also a feature/bug of the bootstrap library and can be replicated here: https://www.bootply.com/render/PPzyYOQreX#tab1
or at ALA http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:f2a4e6b4-fc50-4177-8f61-3377ac377af4#classification
I don't like it much either, but since it how the worlds probably most used ui library does it, I would say we can live with it for now.

add region - sounds good. if you add it to all projects in contentful, then it should be trivial. Should we wait till we do the final export though? If now, then it should go into the export script.

calls
is that a new content type then? Lets talk about that one - I'll pop by.

**Comment by MortenHofft** [comment]
Project page
> links on project page.

Sounds fine. but shouldn't we apply that to all pages then? that links is always a separate tab? Or always normal blue links as they are on the current site?

> Lead Participant (or partner) contact details to be removed.

Sure - just tell me what you decide.

> co-funders need a more prominent placement.

Funders too are at the bottom. should we also make those more prominent? Do you have ideas for how it should be shown? Separate tab with all funders? First thing on the page? Previously they were at the header, but that was too prominent I understood, given that it was uncertain funding.
If we give them a more prominent place, we could also consider making them more than just text (fx adding links and logos? That would also make them stand out more. A rough estimate is that [only 50%](https://demo.gbif.org/project/82632/african-insect-atlas) have a link to the funder website. Given the importance of them, it might be worth adding?

**Comment by MortenHofft** [comment]
Summarizing a meeting with @dnoesgaard and Maheva:

Programmes:

* add a region or call column so sort by. Could either be generated from the accosiated calls or from a new field in the contentmodel (free text with a dropdown).
* columns header names are not properly formated (missing from translation file)

Project pages:

* Keep core funders at the bottom, but highlight cofunders and funders by moving them up before the links. First funders, the co-funders then partners (despite there is sometimes an overlap).

* add more spacing between body and the funders, programmes, project id area. This is to make them stand out a bit more.

**Comment by dnoesgaard** [comment]
I've populated all projects with relevant call values, and it looks good. I can't explain, however, the order in which projects are listed on the CESP programme page if you click the Call column:

http://www.gbif-uat.org/programme/82219/capacity-enhancement-support-programme#projects

**Comment by MortenHofft** [comment]
yes that is weird. that ordering doesn't make any sense

**Comment by MortenHofft** [comment]
fixed - it was sorted by id not title.
