### ISSUE TITLE
homepage title "Search" in tab

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#355]
Somehow the homepage title is shown as "Search" in the tab when I browse to demo.gbif.org. It shows "GBIF" while loading but then quickly changes:

![screen shot 2017-06-14 at 16 51 19](https://user-images.githubusercontent.com/21358085/27138843-bf2a9eee-5121-11e7-886d-1efa6c9a176d.png)

**Comment by MortenHofft** [comment]
Yeah - i did that a couple of days ago. But now 90 % of those that were wrong are correct. I'll get the last one fixed, but didn't notice it until after deployment. Thanks
