### ISSUE TITLE
Become a publisher page text 

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#356]
https://demo.gbif.org/become-a-publisher

I have ported the endorsement page.
Some of the content can be edited from Contentful already https://app.contentful.com/spaces/q553fnlofhvs/entries/66rErk6KZ2qw8ioe0QSgao

The rest is hardcoded. Depending on the text needs you have, I will either create a new content model to support the page, or simply add it to the translation file.

So if you update/review the contentful text and create a list of other text changes (field names, descriptions, hint text, error messages etc) i will change those and choose a technology based on what you suggests.

The mail needs wording as well since there is now the option for nodes to endorse directly from the mail.

I will carry over confirmation pages and error pages from the existing version. If you have changes to those just let me know.

**Comment by MortenHofft** [comment]
Full issue here: https://github.com/gbif/portal16/issues/356

**Comment by thomasstjerne** [comment]
The text has now been adjusted according to input from Tim Hirsch. Also som business logic has been added regarding options for selecting a non-country endorsement node.
