### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#357]
Pages that need content

- [ ] https://demo.gbif.org/data-publishing
- [x] https://demo.gbif.org/publishing-guide
- [x] https://demo.gbif.org/become-a-publisher
- [x] https://demo.gbif.org/darwin-core (I pointed the menu to this one - is that correct)
- [ ] https://demo.gbif.org/digitizing-collections
- [x] https://demo.gbif.org/ipt
- [ ] https://demo.gbif.org/collection-management
- [x] https://demo.gbif.org/gbif-software
- [x] https://demo.gbif.org/strategic-plan
- [x] https://demo.gbif.org/terms/privacy-policy
- [x] User & Publisher agreements

**Comment by kcopas** [comment]
Content for https://demo.gbif.org/dataset-classes is complete (with French translation (and translation credit line!)), but it needs an image.

**Comment by kcopas** [comment]
-[ ] Data quality page (http://www.gbif.org/publishing-data/quality) needs to find a home in demo, too.

**Comment by dnoesgaard** [comment]
Digitizing collections and collection mgmt are out for now.

Data Publishing is being merged with Publishing Guide. Will happen first thing post go-live.
