### ISSUE TITLE
Global error handling

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#36]
There should be added a global error handling to app.js. Uncaught exceptions shouldn't kill the server.

https://nodejs.org/api/process.html#process_event_uncaughtexception

**Comment by MattBlissett** [comment]
If something does happen and Node crashes, SystemD should restart it. If that's not happening, let me know.

**Comment by MortenHofft** [comment]
For now we will let the application crash since it takes seconds to restart.
Pros: we won't get caught in a bad state but start anew.
Con: users will loose connection for seconds. The error won't be logged.

@MattBlissett Could you set up SystemD to log the stacktrace from the crash?

**Comment by MortenHofft** [comment]
@MattBlissett has confirmed that crash errors is already logged. Closing issue.
