### ISSUE TITLE
enable translations site-wide

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#362]
We're starting to add translations content not just on the homepage, so it would great to have translations enabled.

**Comment by MortenHofft** [comment]
This is a larger piece of work. There is still coding to do. Not everything are in translation file or contentful. All the menus, terms, filters, etc needs translations. It would be wonderful and satisfying to do this, but requires more than the contentful items being translated. Maybe a fall sprint? 

Once we have released the english version and ironed out the critical bugs, we could list the improvements that we want. Translations is probably high on that list.

Everything is as such in place for it to happen, but still requires a concerted effort and weeks of work i suspect.

For arab and other rtl languages the css is also missing completely. there is no support for that. Based on the static site, it was fairly trivial to add classes to support it, but that was also a much simpler layout.

Accessibility is another issue that we could address. For whom and to which extend should the site be available. Maps for blind for example.
