### ISSUE TITLE
literature styling

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#363]
Ideas for literature styling:

- [ ] for the citation shown in literature (result._gbifDOIs.length > 0), could we float the element right, change the wording to "Data used in study" and make the color lighter, e.g. #aaa ?
- [x] change mention of literatureType _journal_ to "Journal article" 

![resource_search](https://user-images.githubusercontent.com/21358085/27822191-164ccca0-60a5-11e7-92e4-14a5a961fb5d.png)

**Comment by MortenHofft** [comment]
I've updated the translation file to say journal article
https://github.com/gbif/portal16/commit/fd8bff8ce2d7d7c37d8cd4c4dc58d2706b748a15

sure we can right flow it. How do you imagine it should work when there is more than one DOI?
![screen shot 2017-07-04 at 11 27 35](https://user-images.githubusercontent.com/6759267/27824188-d81bdc4e-60ab-11e7-8e7f-d38696bdd279.png)

**Comment by dnoesgaard** [comment]
Maybe we could put the list of DOIs in kind of drop-down box, if there's more than one? Is that doable?

**Comment by MortenHofft** [comment]
sure - but it might be a somewhat off behaviour to link to another page from a dropdown? Or maybe not if it looks enough like a menu.

**Comment by dnoesgaard** [comment]
maybe you're right. we could just start with the wording and leave it at that for now?

**Comment by MortenHofft** [comment]
I agree it isn't too pretty and also not scalable - what if there is 500 dois. But i see that it is nice to have our DOI shown. Maybe a different solution altogether. I just chose this because it was easy and wasn't a terrible solution for now. I'll update to "Data used in study" then

**Comment by dnoesgaard** [comment]
Will revisit this at a later stage then :)

**Comment by MortenHofft** [comment]
updated GBIF DOIs to data used in study https://github.com/gbif/portal16/commit/94bad44d548411f4b5d47f6c2362aa57a0e3f4eb
