### ISSUE TITLE
dataset registry history info

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#378]
Prompted by [actual usage](https://github.com/gbif/portal-feedback/issues/239)

We recently added a crude breakdown of the processing history. 
https://demo.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a

example: 
```
Failed Attempts Since Last Successful Crawl 27
Last Failed Attempt 6 July 2017
Crawling Completion Reasons 100% Abort
Crawls In Total 27
```

I just took a guess on what could be relevant and what the fields meant. If this is of any interest, and it seems it is, it would be nice if someone that knows crawling states/API better could confirm or suggest changes.

I might not show that info in the most appropriate way. Could you @jlegind possibly confirm if it makes sense or if I have misunderstood things in the way it is summarised?
http://api.gbif.org/v1/dataset/84806e86-f762-11e1-a439-00145eb45e9a/process?limit=1000

**Comment by MortenHofft** [comment]
@timrobertson100 you mentioned today that these counts was wrong. Could you possibly summarize your findings here?

**Comment by timrobertson100** [comment]
No, not wrong.  Just that the publisher was surprised to see [67% normal, 33% not modified](https://www.gbif.org/dataset/bcbfd319-8813-4b6d-b529-07dc5a6ccf56#registration) and didn't understand why.  Perhaps we should simply state last successful crawl date (success being normal or not modified), and then a "show history" link which lists a table of the crawl history, date and result?

**Comment by MortenHofft** [comment]
![screen shot 2017-11-28 at 10 32 28](https://user-images.githubusercontent.com/6759267/33312205-7bb350f0-d427-11e7-8c81-44f544341a88.png)
I've extended the dates with more elaborate info. For further details i think that the static site with tools to support publihsers seems like the perfect place for these more detailed views.
