### ISSUE TITLE
Search specification

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#38]
The search specification is the objective for the milestone and is defined as follows.

The search API provides a single entry for discovery of content within the CMS.  Specifically it supports the following features:

1. Full text search using the ```q``` parameter (e.g. ```?q=Argentina```).  Only one ```q``` parameter should be supplied, and multiple will provide inconsistent behaviour.  If not specified it becomes a wildcard search (e.g. all results that match other query parameter criteria) 

2. Paging over search results using ```limit``` and ```offset``` parameters (e.g. ```?limit=10&offset=10```).

3. Sorting using the ```sort``` parameter (e.g. ```?sort=created```).  The list of fields available for sorting are ```[relevance, created, modified, title]```.  The default sort mode if not specified is ```relevance```.

4. Reversal of sort ordering by the inclusion of the ```sort-descending``` parameter (e.g. ```?sort=created&sort-descending``` to return the newest items first).

5. Restriction to content types by using the multi-valued ```type``` parameter (e.g. ```?type=news&type=event```).  Multiple values are logically OR'ed together.

6. Restriction of items that are associated with controlled vocabulary tags by using the multi-valued ```tag``` parameter (e.g. ```?tag=Invasive&tag=conservation```).  Multiple values are logically OR'ed together.

7. Selection of facet counts in the response using the multi-valued ```facet``` parameter.  At this stage only ```type``` and ```tag``` are supported.  (e.g. ```?facet=type&facet=tag```).  If not specified no facets will be present in the response.

The response format will be of the form:
```
{
  "offset": 20,
  "limit": 20,
  "endOfRecords": false,
  "count": 212,
  "results": [
     ... results go in here ...
  ],
  "facets": [
    {
    "field": "type",
    "counts": [
      {"name": "news", "count": 207},
      {"name": "event", "count": 12}
    ],
    "field": "tag",
    "counts": [
      {"name": "Invasive", "count": 1},
      {"name": "Conservation", "count": 2}
    ],
  ]
}
```

Example URLs that demonstrates all functionality:

- http://cms.gbif-dev.org/api/v1/search?q=Argentina
- http://cms.gbif-dev.org/api/v1/search?q=Argentina&limit=10&offset=10
- http://cms.gbif-dev.org/api/v1/search?q=Argentina&limit=10&offset=10&sort=created&sort-descending
- http://cms.gbif-dev.org/api/v1/search?q=Argentina&type=news&type=event
- http://cms.gbif-dev.org/api/v1/search?q=Argentina&type=news&type=event&tag=Invasive
- http://cms.gbif-dev.org/api/v1/search?q=Argentina&type=news&type=event&tag=Invasive&facet=type&facet=tag

**Comment by timrobertson100** [comment]
Following investigations of the _out-of-the-box_ capabilities of the Drupal RESTful module we are not going to implement the specification as detailed above.  It would be considerable customisations to do so, for little benefit.

We will use the default behaviour, including sort, paging etc with only the following modifications:

- [ ] Add "label" to each of the facets
- [ ] Rename "filter" to "id" in the facets
- [ ] Rename the facet tag fields to be consistent and prefixed with ```category_``` (e.g. ```category_data_type```) which will be handled on outgoing and the incoming search filters
- [ ]  Remove the escaping of the \" \" around the values in the JSON
- [ ] Remove the field_featured_search_terms:name from the facets
- [ ]  Remove self
- [ ] Rewrite the above specification in Markdown (as a comment in this issue) to document the API behaviour

**Comment by burkeker** [comment]
### Search behaviour
Drupal has been using ?q= for URL handling, hence it's so called "clean URL" feature. For example, http://cms.gbif-dev.org/api/v2/search is essentially the rewrite of http://cms.gbif-dev.org/?=api/v2/search. Therefore, to indicate the string for searching, we only need to add it to the end of endpoint:
- http://cms.gbif-dev.org/api/v2/search/bid, where "bid" is the string to search for.

#### Paging
Paging of the results is done using "page[number]" and "page[size]" parameter, where page[size] is the number of result to show per request:
- http://bko.gbif.org/api/v2/search/bid?page[size]=5&page[number]=2


#### Sorting
Results can be sorted using the available properties. For example, to sort by entity_id:
- http://bko.gbif.org/api/v2.0/search/bid?page[size]=5&sort=entity_id

To sort descending by entity_id, add an hyphen to the property:
- http://bko.gbif.org/api/v2.0/search/bid?page[size]=5&sort=-entity_id

By default the result is sorted by relevance.


#### Filtering
Available properties can be used for filtering. For example, to get news type:
- http://bko.gbif.org/api/v2.0/search/bid?filter[type]=news

Multiple filters can be applied. They work using _AND_ conjunction:
- http://bko.gbif.org/api/v2.0/search/bid?filter[type]=news&filter[category_topic]=968&filter[language]=pt

Multiple filters of the same field is **NOT** supported at the moment:
- http://bko.gbif.org/api/v2.0/search/bid?filter[type]=news&filter[type]=event

**Comment by burkeker** [comment]
The version number 'v2' is for now only to avoid breaking UAT which uses v1. Later we'll update the version as v1 when releasing new UAT instance.
