### ISSUE TITLE
Update intro description on dataset citation page

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#380]
Note to self (and @dnoesgaard) to de-Dangli-cize @MortenHofft's starter on pages like https://demo.gbif.org/resource/search?contentType=literature&gbifDatasetKey=84806e86-f762-11e1-a439-00145eb45e9a

 Starter version is:

> We do our best to find literature citing GBIF downloads. When a paper cite using a DOI we can track it to the individual datasets and publishers. This list only shows usage known to GBIF. The data might have been filtered further after download.

This summary should encapsulate the literature tracking programme and link across to all peer-reviewed citations and, in the absence of a more general starting place, a relevant example showing a publisher's citation list (and vice versa, publisher-to-dataset).

**Comment by dnoesgaard** [comment]
Oh, we had actually removed that bit a while ago. Maybe it reappeared when @MortenHofft rolled back some things after his vacation? See #205

**Comment by MortenHofft** [comment]
and gone it is - i suspect i never removed it first instance i'm afraid

**Comment by dnoesgaard** [comment]
So I started this and realized I couldn't make just one line. Instead I did this: https://demo.gbif.org/literature-tracking (work in progress)

Idea: Above search results for literature, simply include a line saying, e.g.

[Details about literature, how it's discovered and linked to GBIF-mediated data](https://demo.gbif.org/literature-tracking)

and link this line to the page, I'm working on?

**Comment by kcopas** [comment]
that page is looking good, bubba...

**Comment by MortenHofft** [comment]
Sounds good to me, I've inserted the text again, changed it and linked it. I changed the sentence to `Read more about literature, how it's discovered and linked to GBIF-mediated data.` because i felt it made more sense in the context, but that can be changed back [here](https://github.com/gbif/portal16/blob/master/locales/server/en.json#L2434) if you disagree
