### ISSUE TITLE
GBIF network page - a few issues

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#381]
https://demo.gbif.org/the-gbif-network
(was a small thing but decided to expand this to include more issues)

- [x] Switching from global to regions and in between regions works great, but if you switch back to global from a region, the maps doesn't change.
- [x] the map view of Asia should be zoomed out a little - at least to show the 1 voting participant we have
- [x] Israel shows up in the Asian region, should be in Europe (not sure if this is a general issue)
- [x] Affiliates are not shown anywhere

(@kcopas, feel free to weigh in here)

**Comment by thomasstjerne** [comment]
@dnoesgaard can you explain a bit what you mean by affiliates? Are you referring to the "Participant organisations"?

**Comment by dnoesgaard** [comment]
http://www.gbif.org/participation/participant-list#affiliate

They're Type=Other and Participationstatus=AFFILIATE in the API...

**Comment by MortenHofft** [comment]
When arriving at https://demo.gbif.org/the-gbif-network the list of all participants is missing. Wouldn't it make sense to show them all? Or have we decided not to?

**Comment by dnoesgaard** [comment]
No, I agree - it would make sense.
