### ISSUE TITLE
Show verbatim scientific names for occurrences in tables etc which have TAXON_MATCH_NONE or TAXON_MATCH_HIGHERRANK

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal16#400]
Extracted from the comment thread on #341

**Comment by dgasl** [comment]
I understand "closed" means fixed in this case. Right?

But how long does this take to go live in portal site?

Thanks

**Comment by MortenHofft** [comment]
Typically within a couple of days. At times within hours.
