### ISSUE TITLE
dead link "Learn more" about download formats

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#404]
https://demo.gbif.org/occurrence/download

@kcopas and @dnoesgaard would you like to be able to write more here and if so where? a FAQ? a link to a downloads page with an anchor? Something else? How much space do you need. If one sentence is enough, then we can do it inline.

If nothing to link to i will simply remove it.

![screen shot 2017-08-03 at 11 29 08](https://user-images.githubusercontent.com/6759267/28915309-02e92ff8-783f-11e7-9ec6-715ffc4360f6.png)

**Comment by dnoesgaard** [comment]
I've added some text and an anchor here:

/gbif-software#downloads

It's very simple, but at least it allows to expand easily, if need be. So my suggestion is to replace the "learn more" link with the above.
