### ISSUE TITLE
Further enhancements to literature search

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#405]
I would like to request the addition of two new fields for literature:

- peer_review
- open_access

The values for these should be derived from tags in Mendeley using the same name followed by a colon and boolean, e.g.

2017; BR; GBIF_used; Taxonomy; open_access:false; peer_review:true

Tasks necessary

- [x] implement tagging of papers from now on 
- [x] fix crawler/index
- [x] tag papers retrospectively (@dnoesgaard)

and when all of the above are done:

- [ ] add facets to search page (or not, depending on what we agree on)

**Comment by dnoesgaard** [comment]
@kcopas, I've tagged this one _impact medium_  as the impact right now might not be crazy, but eventually it'll become really important. Do you agree?

**Comment by kcopas** [comment]
Probably right. It reflects a change from the current Drupal implementation/integration (which shows only peer-reviewed), but does not represent a loss of functionality per se.

However, peer-reviewed uses remains our primary means of quantifying and communicating about the literature tracking programme, so it will be important and timely to add this facet relatively soon, imho.

**Comment by MortenHofft** [comment]
Once enough tags have been added for this to be interesting then poke Federico he can easily add it to the index.

**Comment by dnoesgaard** [comment]
Ok, I've got a fairly straight-forward way of adding these tags now, and about 2000 papers have already been retagged. Can we go ahead and add them to the index, please?

Again, the fields are

open_access
peer_review

with values true or false, e.g.

> 2016; CA; CA_biodiversity; DNA; GBIF_VIP; GBIF_used; US; US_biodiversity; biodiversity_science; gbifDOI:10.15468/dl.jfbe7h; open_access:true; peer_review:true; phylogenetics; species_description; taxonomy

I'll work on the remaining 3000 or so papers...

**Comment by dnoesgaard** [comment]
(ping @fmendezh)

**Comment by dnoesgaard** [comment]
95% of papers in Mendeley have now been retagged...

**Comment by dnoesgaard** [comment]
As mentioned in our chat, we have agreed to add facet(s) for these new fields. @MortenHofft you are free to do this in whatever way is easier for you.

**Comment by MortenHofft** [comment]
Please inform me what the text should be

![screen shot 2017-10-11 at 17 47 53](https://user-images.githubusercontent.com/6759267/31451425-5f81b1ec-aeac-11e7-8995-23d8c4c1abf5.png)

```
"peerReview": {
      "title": "Peer review",
      "description": "Has this been evaluated by others working in the same field"
    },
    "openAccess": {
      "title": "Open access",
      "description": "We consider an item open access when there are no access restriction. Neither login or payment."
    },
```

building to dev and UAT now.

**Comment by dnoesgaard** [comment]
We prefer the facets without the explainers for now, if that's ok with you. If anything, we can add faq links at a later stage. This isn't the right place to define these concepts.

**Comment by kcopas** [comment]
I don't think we need explanations for either of these in context. I could envision adding a help item to the Open Access label, which could pass through to a more detailed explainer in a long-planned and -deferred item on 'Open Science'—but that's an improvement that's easily added later (provided we implement the inline help link), not a requirement for now.

Small tweak: imo the peer review label should be 'Peer-Reviewed'.

TUSIND TAK! 
(YES, I KNOW I'M YELLING!)

**Comment by dnoesgaard** [comment]
Yes, tusind tak from me also :)

**Comment by MortenHofft** [comment]
It is live - i'll close then. Just reopen if you still believe there is work to be done.
