### ISSUE TITLE
events add to calendar

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#406]
on search and individual events there is a non functional button
https://demo.gbif.org/resource/search?contentType=event
https://demo.gbif.org/event/83360/gb24-24th-meeting-of-the-gbif-governing-board

An endpoint is now available to generate the calendar files (ask @fmendezh for details)

I imagine a drop down with the types for the buttons and a subscribe button top right when on the [event page](https://demo.gbif.org/resource/search?contentType=event)

![screen shot 2017-08-04 at 08 48 00](https://user-images.githubusercontent.com/6759267/28957313-a456be0c-78f1-11e7-9f87-d36be6af6651.png)

If the calendar endpoint isn't ready, then the buttons should be temporarily removed

**Comment by thomasstjerne** [comment]
For now added as webcal link, i.e. when clicked in chrome default behaviour is adding to google cal, whereas Safari asks to open iCal, etc. 
So, no dropdown at the moment
