### ISSUE TITLE
Map interactions

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#439]
**Map interactions**

I find the occurrence search a nuisance on the maps.  To get a mouse scroll wheel to enable zoom rather than page scroll, requires a map click.  This first click though starts a search.  I often find clicking to take control of the map does searches I don&#39;t intend (which pop up 5 secs later).

I&#39;d suggest considering alternatives.  Perhaps ignoring the first click, and also changing the cursor to something that gives a clue that further clicks will issue a search, or perhaps putting the search behind a button you explicitly enable. 

Haven&#39;t thought about the implications of mobile on this, but on a desktop I do this on almost every map view

-----
fbitem-dataset4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Window size: width 1490 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-30T13:02:26.585Z',mode:absolute,to:'2017-06-30T13:08:26.585Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-30T13:02:26.585Z',mode:absolute,to:'2017-06-30T13:08:26.585Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
search is now a separate tool
