### ISSUE TITLE
sort by year, recent first

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#445]
**sort by year, recent first**

When papers citing a dataset are displayed, sorting by year is preferred, most recent first, but all equal with a year - data of publication is not important. Within each year, alphabetically by the last name of the first author.

Alternatively, we could sort in the classic bibliographic way, i.e alphabetically by the first and the following authors, then chronologically for possible multiple publication for the same groups of authors.

Option 1 makes more sense to me.

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
Reported by: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/resource/search?contentType=literature&gbifDatasetKey=6ac3f774-d9fb-4796-b3e9-92bf6c81c084
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-08T12:07:59.085Z',mode:absolute,to:'2017-06-08T12:13:59.085Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-08T12:07:59.085Z',mode:absolute,to:'2017-06-08T12:13:59.085Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dschigel** [comment]
@dnoesgaard won't it make more sense and more tidy to display recent first (year level only)? Order of addition to Mendley seems to make only procedural sense to us, not external users? Take a look on my example linked in the issue above - 2017, 2016, 2017, 2015, 2017 etc.

**Comment by dnoesgaard** [comment]
I asked for the current sort order to be able to see new literature, so the list is more dynamic, i.e changes every time you visit it. I do agree that it looks a bit silly to have 2015 items suddenly appear among new items.

We could get around it by sorting based on year and _then_ by data added? That way we would always have papers by year, but within a year by when it was added. It would mean that a paper from 2015 discovered in 2017 would make the top of the 2015 papers, but I can live with that.

1) is that possible, @MortenHofft ?
2) would you agree with the approach, @dschigel ?

Alternatively, if we can't agree, we should opt for the more expensive solution, i.e. a user-controlled search order drop-down.

**Comment by dschigel** [comment]
On 2. yes, great idea.

**Comment by MortenHofft** [comment]
Is on UAT with [this build](https://builds.gbif.org/job/portal16/1279/)

https://www.gbif-uat.org/resource/search?contentType=literature

Please test to see if it what you had imagined

**Comment by dnoesgaard** [comment]
Yup, looks good to me.
