### ISSUE TITLE
literature indexing - count issue

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#451]
The number of papers in the ES index vs what we show in literature search varies just a bit, but enough to annoy me:
 
https://demo.gbif.org/api/resource/search?contentType=literature
("count": 4952)
 
http://cms-search.gbif.org:9200/literature/_search
("total": 4979)

Which papers are leaving out and why?

**Comment by MortenHofft** [comment]
It isn't a wrapper query issue
http://cms-search.gbif.org:9200/_search?q=(contentType:literature) = 4966
http://cms-search.gbif.org:9200/literature/_search = 4976

**Comment by MortenHofft** [comment]
Seem to be solved. I'm guessing it had to do with the non-atomic build that you fixed the other day @fmendezh ? I'm closing. Please reopen if necessary
