### ISSUE TITLE
Implement CMS search

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#46]
As per the milestone

**Comment by burkeker** [comment]
Inititial Faceted search available for CMS search. Issues to fix:
- [ ] Some of the selected UI don't work, e.g. Language: Undetermined -> Not specified
- [ ] Proper name format for catetory: Remove “category” and capitalise
- [ ] Sort by number, then label
- [ ] Some of the de-selecting UI don't work, e.g. http://internal.gbif-dev.org/cms/table?q=africa&category_data_type=834 Category data type is filtered, but the X is not present to remove it
- [ ] Timeout for the slow backend = 5 secs
- [ ] Add a “spinner” (or just “loading…”) when the results are loading

**Comment by burkeker** [comment]
Facets are sorted by the count, than name, except category_country, which is sort by name first, given the amount, then the count.

**Comment by burkeker** [comment]
All above issues addresed. Pushed to UAT.
