### ISSUE TITLE
Information facet cleanup

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#47]
Please remove the following from the UI (not the CMS API) following a discussion with Kyle C:

- [x] Tags
- [x] Data type
- [x] Informatics

Please rename "Undetermined" to "Unspecified" in the Language facet

**Comment by MortenHofft** [comment]
> Please rename "Undetermined" to "Unspecified" in the Language facet

The cms search hasn't been made fully translatable yet. I will look at this later

**Comment by burkeker** [comment]
The CMS facets are fully translatable and the 3 facets are hidden. Closing issue. "Undetermined" had been replaced with "Not-specified" following an instruction on Skype. Will keep it for now.
