### ISSUE TITLE
Open Street Map incorrect labelling of Falkland Islands (Malvinas)

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#476]
GBIF have generated base maps from Open Street Map in WGS84 and 2 polar projections.  In doing so we were careful to label _Falkland Islands (Malvinas)_ correctly.  GBIF used the pre-generated Mercator projection tiles, but overlooked that the labelling is incorrect.

Task: Regenerate the Mercator tiles correctly

**Comment by MattBlissett** [comment]
Fixed by a style change:

![Falkland/Malvinas](https://tile.gbif.org/3857/omt/6/21/42@1x.png?style=osm-bright)
