### ISSUE TITLE
Newsletter subscription success page broken

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#478]
After clicking "subscribe" on https://www.gbif-uat.org/newsletters I'm sent to http://subscribed.

(IE Windows, Firefox Linux)

**Comment by dnoesgaard** [comment]
Should be fixed now, although since relative links aren't supported I'll have to change again once we switch demo -> www

**Comment by MortenHofft** [comment]
thanks @dnoesgaard . This should of course be moved out of that mad mimi iframe soon: https://github.com/gbif/portal16/issues/100
but for now there is little else to do.

**Comment by MattBlissett** [comment]
Just a reminder -- did you update the URL?

**Comment by dnoesgaard** [comment]
I did...now.

**Comment by dnoesgaard** [comment]
(thanks)
