### ISSUE TITLE
Final menu tweak(s)

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#483]
Content on the [publishing quick guide](https://demo.gbif.org/publishing-guide) has been updated. It currently appears in the menus as the destination for 'Share > Publishing guide' (3rd item in the menu). 

However, I would like to propose that the menu slot the link to this page into the first position, slightly changing the label to 'Publishing data'. This is more verb-oriented, an active statement—rather than the stationary noun implied by both 'Data publishing' and 'Publishing guide'.

Once this change is made, the third item presently on the Share menu ('Publishing guide') can simply be removed.

**Comment by kcopas** [comment]
This doesn't appear to be done. It's an important bit of clean-up.

**Comment by MortenHofft** [comment]
Looks correct on https://www.gbif-uat.org/ as far as I can see. 
We haven't done a prod build since. But soon :)

**Comment by kcopas** [comment]
Sorry, didn't realize there was no prod build. 

However, 'Publishing data' should link to /publishing-data (click the link—it's 404, going to /publishing-guide), and 'Data publishing' (now second in the list) should be removed.

Sorry to be a pest!
