### ISSUE TITLE
http://www.gbif.org/newsroom/news/rss gives 404

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal16#499]

**Comment by kcopas** [comment]
Yup—@dnoesgaard and I just waiting on a redirect to add it under RSS feeds on the newsletters page...

**Comment by dnoesgaard** [comment]
I know this is in place for events, but is it for other content (news, data use)?

@fmendezh, @timrobertson100 ?

**Comment by dnoesgaard** [comment]
What is the endpoint for news RSS?
