### ISSUE TITLE
Update default dataset citation format on dataset page

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#5]
http://dev.gbif.org/issues/browse/POR-2590

**Comment by MortenHofft** [comment]
Awaits clearance on the citation format - currently we show the user provided citation. I guess this is an issue for @ahahn-gbif for now. Once a decision have been made we can start implementing it

**Comment by MortenHofft** [comment]
@kbraak as I understood you the other day it has been decided that we use the GBIF generated citation. Is that correct?

If so the decision remains where to generate it. I would think that it should be a part of the API response.

**Comment by MortenHofft** [comment]
blocked by https://github.com/gbif/registry/issues/4

**Comment by MortenHofft** [comment]
is solved in the api on dev and will be solved on the portal once released
