### ISSUE TITLE
reduce number of contentful calls

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#508]
reduce number of contentful calls
candidates

* notifications
* urlAlias
* projects and programmes
* resources (tricky as it is also used for previews)

Secondly they should be passed through varnish

**Comment by MortenHofft** [comment]
We still get extra bills as times, but I'm not convinced that it is still the website doing the majority of those calls.

@timrobertson100 If we want to reduce number of calls it might be an idea to track nr of calls  from indexing and backup?

**Comment by timrobertson100** [comment]
Thanks- the costs are fine at the moment but I'm tracking the billing. If this changes we can reopen and consider less frequent crawling.
