### ISSUE TITLE
Handle RSS feeds

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#509]
The following RSS feeds are currently 404s and [used a fair amount](http://elk.gbif.org:5601/goto/f791f4abb52cd27b390fd16565061728):

http://www.gbif.org/newsroom/archive/rss
http://www.gbif.org/newsroom/events/rss

Can we please add routes for them in the newsroom?

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/portal16/commit/35b44bef9ee61d289f3214c81f624fffb98c6078
