### ISSUE TITLE
Enable push notifications instead of polling

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#513]
Currently we ask for new notifications on pageload and every second minute.
That isn't a really good solution. It would be nicer if the server pushed updates. This could also be used for automated status messages about system stability

**Comment by thomasstjerne** [comment]
@MortenHofft tested this and found problematic performance issues.

**Comment by MortenHofft** [comment]
The issue was that having just a few hundred concurrent users that each had a socket open would completely kill express as it tried to push to them all. Given that we do not need instant push and that polling performs much better we decided on sticking with that.
