### ISSUE TITLE
Need to show authorities for GBIF taxon concepts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#528]
**Need to show authorities for GBIF taxon concepts**

We list the classification and synonyms but don't state which datasets underpin this.

-----
fbitem-species5749074
Reported by: dhobern@gbif.org
System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/species/5749074
Window size: width 1897 - height 924
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T05:56:29.049Z',mode:absolute,to:'2017-08-21T06:02:29.049Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T05:56:29.049Z',mode:absolute,to:'2017-08-21T06:02:29.049Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
See also extensive comments on https://github.com/gbif/portal-feedback/issues/367

**Comment by mdoering** [comment]
An issue that has also been raised externally. Would be good to get sth done soon.
