### ISSUE TITLE
italicize scientific names

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#54]
@rdmpage
Scientific names should be italicized. Because it is correct.

**Comment by rdmpage** [comment]
@MortenHofft It's a small thing but it will have an impact on how experts will view the site. Put another way, it shows that GBIF cares about representing the subject matter correctly.

**Comment by mdoering** [comment]
The GBFI API allows you to request a ParsedName object that has the individual name parts needed to render it nicely for any name usage like this:

http://api.gbif.org/v1/species/118637812/name

**Comment by timrobertson100** [comment]
For first milestone, we need this for titles of pages at the very least.

**Comment by MortenHofft** [comment]
this has been implemented for species pages, featured search results and occurrences pages. For lists of occurrences it isn't as we would need to look up each name. we could consider this, but it seems less important in those cases (say occurrence search table where you have the full taxonomic breakdown). Now that we have a way to do so, we can expand the usage of it as needed. 

I will close and we can reopen if we overlook important places or someone disagree the decision to not show it in e.g. tables.
