### ISSUE TITLE
a few directs from MoU letter

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#541]
I was just looking at the latest participant to whom we sent out a welcome to GBIF letter. I found these links that needs to be redirected (ref gbif/comms#3):

/orc/?doc_id=2961&l=en -> /document/80667/rules-of-procedure-of-the-gbif-governing-board
/governance/standing-committees#nodes -> /contact-us/directory?group=nodesCommittee

Not sure how anchors are handled, but hopefully there's a solution...

**Comment by thomasstjerne** [comment]
Depends on #548

**Comment by thomasstjerne** [comment]
Anchors are ignored by the webserver. So the redirect will be from the whole page:
/document/80667/rules-of-procedure-of-the-gbif-governing-board
/governance/standing-committees

If we at some point need to have redirects from two anchors in the same page, we will have to come up with some solution

**Comment by dnoesgaard** [comment]
Just discovered that there's a error here. To be clear, these are the redirects needed:

1)
FROM: /orc/?doc_id=2961&l=en 
TO: /document/80667/rules-of-procedure-of-the-gbif-governing-board

2)
FROM: /governance/standing-committees#nodes
TO: /contact-us/directory?group=nodesCommittee

**Comment by MortenHofft** [comment]
the redirects are added. The server need to be restarted for it to be visible on the website.

**Comment by dnoesgaard** [comment]
Any idea when that might happen?

**Comment by dnoesgaard** [comment]
No 2 (/governance/standing-committees#nodes) still isn't working. Is the anchor the problem?

**Comment by MortenHofft** [comment]
there are several problems. One is that anchors are not send to the server and I just blindly copied the redirect without thinking.
Another is that you might want several redirect on the same page with diff queries and the code doesn't allow for that.

**Comment by MortenHofft** [comment]
in general : URL redirection of old style orc links.
this seem to have been an issue previously as well http://dev.gbif.org/issues/browse/POR-2516
