### ISSUE TITLE
uat site indexed by google

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#542]
While Googling GBIF Mali I noticed this hit:

![screen shot 2017-08-30 at 15 27 29](https://user-images.githubusercontent.com/21358085/29874749-047e5c94-8d98-11e7-832f-f67b288a687b.png)

The UAT site shouldn't be indexed, or..?

**Comment by MortenHofft** [comment]
No I don't think it should either. The old UAT site was indexed as well. There is mixed opinions on whether it should be.
