### ISSUE TITLE
Add page for 'GBIF network webinar'

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#543]
Request's come down to create a central location for information on the webinars to-date. Probably a combination of linking to events and surfacing the archived recordings. Intro text also needed.

Should be completed within the next two weeks, well ahead of GB24. We also need to consider preparing summary statistics on the webinars.

Ready…go!

**Comment by dnoesgaard** [comment]
I already did this: https://www.gbif.org/webinars

Let me know if it needs more work...
