### ISSUE TITLE
Facebook sharing - old app?

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#552]
Noticed some odd behavior when people used the share-to-Facebook button on a [news item](https://www.gbif.org/news/52tjjGyuzSE8ESqEOu4eMu/job-opportunities-for-software-developers):

[Example](https://www.facebook.com/maheva.bagard/posts/10156596597664745) (need to be friends with Maheva)

![facebook](https://user-images.githubusercontent.com/21358085/30421812-3dcc8f96-993e-11e7-92c6-57c7a3801d62.png)

I'm guessing someone has "claimed" the gbif.org domain in an app and this adds this tag to posts?

Any idea?

**Comment by MortenHofft** [comment]
the facebook account used is the one used for the old site as well. Not sure why it was ever set to point to drupaledit. I have updated it.
