### ISSUE TITLE
Clarify handling of Kosovo

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal16#558]
- [x] Determine what should happen from Tim Hirsch
- [ ] Update portal frontend and country enum
- [x] Update geocoder
- [x] Update registry country enum
- [x] Add XK to directory API

**Comment by thomasstjerne** [comment]
We will include Kosovo in the geocoder. And we should not raise the coordinateCountryMismatch issue for occurrences in Kosovo.
@MattBlissett can you look into this?

**Comment by MattBlissett** [comment]
This is now ready for the portal to show the page https://www.gbif.org/country/XK/summary

**Comment by MattBlissett** [comment]
It also needs to show on the search facet dropdown, @MortenHofft .

**Comment by thomasstjerne** [comment]
The XK code should be rocognised by the directory:
http://api.gbif.org/v1/directory/participant/?country=XK

**Comment by MattBlissett** [comment]
It's now returning no results rather than an error, the same as e.g. http://api.gbif.org/v1/directory/participant/?country=BZ

**Comment by thomasstjerne** [comment]
Occurrence api also throws an error
http://api.gbif.org/v1/occurrence/count?country=XK

**Comment by MattBlissett** [comment]
This is fixed, and also the vector tile server.
