### ISSUE TITLE
redirect link in download email

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#559]
Please change url included in download email:

> For information about download formats please visit
 >   http://www.gbif.org/faq/datause

should be https://www.gbif.org/faq#dataUse

Additionally, please add redirect

**from**: /faq/datause
**to**: /faq#dataUse

Thanks.

**Comment by MortenHofft** [comment]
https://github.com/gbif/gbif-configuration/blob/master/portal16/common/redirects.json#L2055 will be available on next restart
