### ISSUE TITLE
Add list of datasets on the project page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#56]
The dataset API supports listing of datasets by project code.  Here is an example:

http://api.gbif-dev.org/v1/dataset/search?project_id=BID-AF2015-0122-FEDE

The project page should list the datasets associated using this API - perhaps a simple table, with Title, Publishing institution, Type, and Record count? If you have thoughts on what you'd like to see, please comment @kbraak

**Comment by burkeker** [comment]
Done in dev. Will check again when the API is in production.

**Comment by burkeker** [comment]
This is relevant to http://dev.gbif.org/issues/browse/POR-3129.

**Comment by timrobertson100** [comment]
You can issue a facet search in production to find examples:
  http://api.gbif.org/v1/dataset/search?facet=project_id&limit=0

and then take an example:
  http://api.gbif.org/v1/dataset/search?project_id=AA003-AA003311F

Would that suffice?

**Comment by burkeker** [comment]
Prompted by AH. Thought for the record attach the screenshot here.

![screenshot 2017-01-23 12 50 44](https://cloud.githubusercontent.com/assets/637631/22203020/25aa988a-e16b-11e6-9e00-514de0178996.png)
