### ISSUE TITLE
info about data user agreement in download dialog

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#561]
excerpt from https://github.com/gbif/portal16/issues/333 by kbraak

> **Include terms of use.. and guidance on how to comply with them**
Include terms of use (data use agreement) in download dialog and download page.
The aim is to remind users that they must give appropriate attribution to the author(s) of the data in any publication that uses data downloaded from GBIF.org.

If comms agree that it should go into the occurrence download tab, a natural place could be the dialog as Kyle suggests. 
![screen shot 2017-09-26 at 18 32 46](https://user-images.githubusercontent.com/6759267/30872048-2213821e-a2e9-11e7-9095-558ca5e18bda.png)

If you believe that these links belong here, then let me know what the new text should read. Thanks

I have added it to the download page already as `Make sure to read the datause agreement and citation guidelines.`
![screen shot 2017-09-26 at 18 35 41](https://user-images.githubusercontent.com/6759267/30872208-904d19c0-a2e9-11e7-9e25-295d63458dc7.png)

**Comment by dnoesgaard** [comment]
Pop-up text:
To promote transparent science and credit data publishers it is important to cite data correctly. You can do so by including the [recommended GBIF citation](https://www.gbif.org/citation-guidelines) in your work, which you will receive together with your requested data.
If you are analysing the data you will download, please consider referencing this citation in your Materials and methods section.
---
This could be simplified and bulleted, along the lines of

yes, this is free but don't forget to
- read the use agreement
- cite as recommended in guide

**Comment by MortenHofft** [comment]
the chance of someone actually reading would probably be higher with your simplified version. Let me know if I should replace it.

**Comment by dnoesgaard** [comment]
I'll work on it some more and let you know :)

**Comment by dnoesgaard** [comment]
I've simplified and updated the translation for the **Free of cost – not free of responsibilities** box...

**Comment by dnoesgaard** [comment]
(can't close the issue)
