### ISSUE TITLE
Port the data trends from GBIF.org to portal16

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#57]
In the not too distant future we wish to revise our trends/analytics section.  However, in this phase we simply aim to port the existing static pages available under http://www.gbif.org/analytics to the portal16 project.

The section comprises of the ability to select global, "country about", "publishing country" and FAQ and all this needs migrated in this iteration.  The text was reviewed and should remain as it is.

It comprises of static HTML using images that are provided by Drupal.  We will continue to use the same images for the time being and @burkeker can give examples of how to construct URLs for Drupal sourced images for the new site.  When we get an image cache that does on-the-fly resizing, we will use that but for now will simply replicate the current functionality and use the (insanely) large images.  

The existing implementation can be found in https://github.com/gbif/gbif-drupal/tree/master/sites/all/modules/custom/gbifs/gbif_analytics and the HTML used Bootstrap2 so should be relatively easy to port.

This does not require translation.  In this phase we simply wish to port existing functionality, and would revise the concept when internationalising.

As it is first contribution, please provide this as a pull request for review by @MortenHofft 
(CC @burkeker for information)

**Comment by kbraak** [comment]
@timrobertson100 @burkeker 

Can you please confirm whether the [Global data trends FAQ](http://www.gbif.org/analytics/faq) has been ported over to the new portal yet? I looked but can't find it anywhere, e.g. https://demo.gbif.org/analytics/global I suspect this issue should be reopened therefore.

In the future, however, I can imagine the Global data trends FAQ becomes part of a broader GBIF.org FAQ - see my suggestion here please: https://github.com/gbif/portal16/issues/309 

It also looks like users can't easily link out to National data trends from the [Global data trends](https://demo.gbif.org/analytics/global) page. How about just linking to the [GBIF Network page](https://demo.gbif.org/the-gbif-network), which apparently replaces the [National data trends](http://www.gbif.org/analytics/country/about) page? Thanks for your help.

**Comment by timrobertson100** [comment]
Thanks @kbraak - confirmed that they appear unported.
A single FAQ seems sensible to me.
