### ISSUE TITLE
Sync (or explain) different numbers of publishers 

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#571]
Ideally, we should show the same numbers of publishers wherever that total is given. If that's too tricky, we should either a) adjust labels so they explain the reason for any disparity or b) add an FAQ item to explain the disparity.

Right now we show three numbers:

- [Home](https://www.gbif.org): currently 1,106
- [GBIF Network](https://www.gbif.org/the-gbif-network): 1,254
- [Publisher search](https://www.gbif.org/publisher/search): 1,403 (total endorsed)

**Comment by MortenHofft** [comment]
Yes that is confusing. 

**home page vs search**
They used to be the same, but we were directed that homepage should (as on the previous site) be the number of publishers that have actually published and not all publishers. I can revert to all publishers again? I can see how active publishers it is the more intersting number though.
Better would probably be to include some more filters to publisher search so that we can link to publishers that have published > 0 datasets.

**Comment by MortenHofft** [comment]
**search vs network page**
From briefly looking it seems that the number on the network page is the the number of publishers endorsed by countries only. So a publisher endorsed by a non country participant would not count. @thomasstjerne you know the reasoning and implementation.

**Comment by dnoesgaard** [comment]
Showing all publishers would be the correct solution, as it wouldn't be fair to exclude someone who's just been endorsed but just haven't publish their first dataset.

That being said, there are almost 300 "inactive" publishers in the registry, and nearly 200 of these have been in there for more than a year (and 100, more than 5 years). Perhaps a clean-up is in order?

**Comment by thomasstjerne** [comment]
- [Home](https://www.gbif.org): currently 1,106 - Number of publishers with at least 1 dataset 
- [GBIF Network](https://www.gbif.org/the-gbif-network): 1,254 - Number of country and non-country participant  endorsed publishers (affiliates have their own tab and is currently not included under the "Global" tab)
- [Publisher search](https://www.gbif.org/publisher/search): 1,403 (total endorsed)

If the affiliates get included under the global tab, the numbers on Publisher search and GBIF Network page should be in sync.

But it was decided to exclude the publishers with no dataset from the home page count before the portal release. So please make an agreement on this with TH, before we change it back.

**Comment by thomasstjerne** [comment]
The above will unfortunately not fix it.

The network page will only get another 18 publishers by adding those endorsed by OBIS.

The network page does NOT show former participants, and therefore publishers endorsed by these is not in the count.

E.g. this publisher, endorsed by a former participant: https://www.gbif.org/publisher/6c821c6d-1936-41a0-8dd9-74e2c4ab38bd is not included in counts

**Comment by dnoesgaard** [comment]
We have discussed this further and have agreed on the following action points:

- the number of publishers endorsed by current participants is not really useful. Endorsement is a one-time procedure and an endorsed publisher can be relevant not matter the status of their endorsing entity. So, for the network page we should show all publishers.
- on the homepage, can we change "Publishers" to "Publishing institutions" and add a help-link to "what-is-a-publishing-institution" to explain the count

Please let me know if anything is unclear :)

**Comment by MortenHofft** [comment]
> the number of publishers endorsed by current participants is not really useful. Endorsement is a one-time procedure and an endorsed publisher can be relevant not matter the status of their endorsing entity. So, for the network page we should show all publishers.

@thomasstjerne could you look at this part please?

**Comment by MortenHofft** [comment]
>on the homepage, can we change "Publishers" to "Publishing institutions" and add a help-link to "what-is-a-publishing-institution" to explain the count

I'm a bit sceptical of the explainer. I find that that area is getting increasingly cluttered. First with the species explainer link and now the publisher one. Tim Hirsch mentioned at some point that we should remove publisher from that list. Is that still a valid option?

If I'm the only one, then sure. But doesn't it look wrong to you? Or make the species one a count and a question mark link as well?

![screen shot 2017-10-10 at 16 35 57](https://user-images.githubusercontent.com/6759267/31392305-36951554-add9-11e7-878c-e346e12e6ffd.png)

**Comment by dnoesgaard** [comment]
I see your point, and I tend to agree. Let me toss it around the office tomorrow and see what happens.

**Comment by dnoesgaard** [comment]
Sketch for my own use:
![new_publisher_count](https://user-images.githubusercontent.com/21358085/31429720-109e9712-ae6f-11e7-9ff1-e66790416262.png)

**Comment by dnoesgaard** [comment]
Change of plans. Leave out the explainer. So only change: "Publishers" -> "Publishing institutions"

![counts on homepage2](https://user-images.githubusercontent.com/21358085/31431131-190d4fde-ae73-11e7-81cd-29d29180b98c.png)

Revisiting the species count is a can of worms that we'll open at another time. Or not.
