### ISSUE TITLE
Add occ metrics tab for species pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#590]
from http://dev.gbif.org/issues/browse/POR-1444?jql=project%20%3D%20POR%20AND%20status%20%3D%20Open

Expose basic breakdown
Occ breakdown for that species by basis of record, country and maybe even the identified rank

**Comment by thomasstjerne** [comment]
For species with synonyms, it would also be useful to add a breakdown of name usages (i.e. count of occurrences using the variuous synonyms ).
Only relevant for taxa at species rank or below
