### ISSUE TITLE
Show alert on dataset page whenever indexing is off

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#6]
http://dev.gbif.org/issues/browse/POR-2148

**Comment by simoncha** [comment]
Seems that indexing is off this week ...
Such a feature would have prevent me to bother Kyle about http://www.gbif.org/dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531

**Comment by kbraak** [comment]
Every time we turn off indexing for maintenance or dedicated crawling of eBird, publishers write to helpdesk or comment in GitHub expressing confusion and frustration. Here is another [recent example](https://github.com/gbif/ipt/pull/1286#issuecomment-280856775) of such a case. 

An alert explaining that indexing is turned off coupled with information about how GBIF indexes datasets is gravely needed. This will not only improve the publisher's experience on GBIF.org, it will also alleviate a lot of load on the GBIF Helpdesk. Thanks.

**Comment by dgasl** [comment]
I absolutely agree.  

And it would be so useful If this info is also available through the api

Thanks a lot

**Comment by peterdesmet** [comment]
I assume when indexing is turned off, it affects all datasets? Therefore, I would opt for a general warning banner at the top of the website if important services are down, and not just on specific dataset pages:

> We are experiencing ... Check the status of our services here.

That banner should link to a http://status.gbif.org, similar to https://status.github.com/

**Comment by dgasl** [comment]
In the mean time, which is the best and fastest way to know when indexing is turned off?
Perhaps you could notify us via [Twitter](http://twitter.com/gbif) using #nextgbifindexing hashtag ?

Something like twitting "@gbif indexing is off: #nextgbifindexing 2017-04-05T12:00:00+0000"

So we could use twitter api to know, and not wasting time checking our datasets again and again.
By the way ... is indexing turned off right now?

**Comment by MortenHofft** [comment]
There is now a system health page, api and an option for comms to do notifications on the site see more at the issue https://github.com/gbif/portal16/issues/216

On dataset pages, the crawling info is shown at the top (instead of the bottom) if you are a trusted contact for the dataset. Along with some more details. It also shows if crawling is off.

This will show if you are logged in and is a trusted contact. This means that it will show if your account email or Orcid is matching a contact on the dataset. Or for the installation, host, endorsing node or publisher.

![screen shot 2017-11-30 at 09 01 52](https://user-images.githubusercontent.com/6759267/33420043-5ec7e820-d5ad-11e7-8229-404038ecc099.png)

![screen shot 2017-11-30 at 09 06 05](https://user-images.githubusercontent.com/6759267/33420127-bde01422-d5ad-11e7-8be3-35f21393cf23.png)

**Comment by peterdesmet** [comment]
Really nice! Question: my account email is different from my dataset emails, so I would rely on my ORCID to see trusted information... but an ORCID cannot be added to a profile yet?

**Comment by MortenHofft** [comment]
yes it can, but this is only on UAT currently. Will be deployed to prod when it isn't a friday :)

**Comment by simoncha** [comment]
Crawling info seems a nice feature :)

I tried to log in with the email gbifprovider@mnhn.fr which is the technical email provided in the 37 datasets https://www.gbif.org/publisher/2cd829bb-b713-433d-99cf-64bef11e5b3e are hosting, but had no success requesting a password.

Is it too early ? Or still Friday ;-) ?Should I use a different procedure than "forgot your password" ?

All the best

**Comment by MortenHofft** [comment]
Hi @simoncha 
I don't see any account created with email gbifprovider@mnhn.fr ? Are you sure you have registered?

**Comment by MortenHofft** [comment]
@simoncha The systems shows as having sent a reset link to the mail. Let me know if you still experience issues. If so I will create a bug report.

**Comment by peterdesmet** [comment]
I'm logged in, I have connected my ORCID to my account and I am viewing a dataset with my ORCD ([this one](https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e))... but I don't see the extra crawling metrics.

Also, you mention:

> On dataset pages, the crawling info is shown at the top (instead of the bottom) if you are a trusted contact for the dataset. Along with some more details. It also shows if crawling is off.

I don't see this crawling info at the bottom either (for other datasets or when I'm logged out).

**Comment by MortenHofft** [comment]
in that case something is radically wrong or we are misunderstanding each other.

**Comment by MortenHofft** [comment]
This is what I see visiting your dataset without being logged in. You do not see that?

![screen shot 2017-12-18 at 15 12 01](https://user-images.githubusercontent.com/6759267/34110098-e99faf30-e405-11e7-8389-f68a59e8b601.png)

**Comment by peterdesmet** [comment]
I’m sorry: yes, I do see that information. I was confused with “instead of the bottom”, where I only saw the citation. Didn’t notice it above the citation. My bad, no bug.
