### ISSUE TITLE
Literature search

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#60]
The CMS API and the search functionality should expose the literature information from the Mendeley tracking.  
- [x] Create content type for the Literature in Drupal
- [x] User interface supports faceted search

Just to note, further: the paper is in our Mendeley library (GBIF_discussed, GBIF_author, but not GBIF_used). I know it will be a while before we have the literature in as actual drupal objects, but I would hope that we could link to it here as a bit of recommended/related reading.

**Comment by burkeker** [comment]
- [ ] Mendeley tags have to be imported/merged with core Drupal taxonomy, in order to support faceted search.
