### ISSUE TITLE
Orphaned dataset from Italy?

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#601]
I'm thinking that [this dataset from the University of Trieste](https://www.gbif.org/dataset/859c6946-f762-11e1-a439-00145eb45e9a) isn't part of @kbraak 's watchdog project because there is no national node, but it looks like the endpoint is missing.

Thought to ask now, ahead of a Lifewatch-hosted meeting I'm attending in Italy in late November.

Thanks
KC

**Comment by MortenHofft** [comment]
moved here as Andrea has access to that repository https://github.com/gbif/portal-feedback/issues/545 - this repo is really intended for the website issues.
