### ISSUE TITLE
regional activities overview (restore old portal functionality)

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#602]
from http://dev.gbif.org/issues/browse/POR-1812?jql=project%20%3D%20POR%20AND%20status%20%3D%20Open

Restoring old portal functionality, regions
http://www-old.gbif.org/participation/participant-nodes/nodes-committee/regional-activities/
key elements
upcoming regional meetings
past meeting events and reports
"sense of regular regional activities", e.g. annual regional meeting
importance:
continuing growth and importance of regional activities need to be reflected in the portal, as this development is to be encouraged and supported
give credit to i.a. hosts for the contribution
To do: decide where a page like this could be placed. Link from http://www.gbif.org/capacityenhancement/regionalcollaboration?
This links to other issues around restoring OCR searches, filters and navigation. How to display documents and information about past events? Send to saved search, or enter one by one? Needs to be consistent with other areas of the portal. This should echo the layout decision for http://www.gbif.org/governance/governingboard#meetings

@ahahn-gbif I see this idea is from 2014 - is it still a priority?

**Comment by ahahn-gbif** [comment]
To be discussed further with the Participation group, but yes - regional pages are still needed. Minimum level: a list of GBIF regions, each with its membership (countries and international organizations) and regional representatives (contact persons), as well as an option for regions to advertize / link to ongoing/upcoming activities and meetings.

**Comment by ahahn-gbif** [comment]
also see issue #293
