### ISSUE TITLE
Show type status in occurrence search as default under basis of record

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#604]
The type status is an important property distinguising specimens. It would be better to show it below the basis of record in the same column and turn it on by default

from http://dev.gbif.org/issues/browse/POR-1964?jql=project%20%3D%20POR%20AND%20status%20%3D%20Open

**Comment by thomasstjerne** [comment]
The type now has a prominent position in the header above the map.
In the body, terms are group by their group as exposed here: http://api.gbif.org/v1/occurrence/term/

![isotype](https://user-images.githubusercontent.com/1666484/31376284-b539cd08-ada4-11e7-99e0-db1f08479aa5.png)
