### ISSUE TITLE
Create site menu (version 1)

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#61]
The site needs a menu:

- [x] Propose a structure based on current thinking of the target pages (@kcopas)
- [x] Implement the proposal for the menu linking to real or stub pages

**Comment by kcopas** [comment]
Proposed site map:
[GBIF.org-nav_v4.xlsx](https://github.com/gbif/portal16/files/519715/GBIF.org-nav_v4.xlsx)

Will be supported with updated '[content inventory](https://docs.google.com/spreadsheets/d/15ies1njgmrQAQ58JCu43ku6_Om2wui04iLGvtDDbdKk/edit#gid=0)' that reflects current status of content and priority for launch, along with other details.

**Comment by timrobertson100** [comment]
After meetings we identified the following pages.  Can you please take a pass over this @kcopas and revise for a first implementation, so we can then see how it looks?  It will surely change again, but I expect you will immediately want to make edits - if you could propose those, we'll then implement it for first demo.

I wonder if literature is in the right place for example, and you might suggest different grouping of the Inside GBIF.  If it grows much more, it does warrant a categorised mega-menu (like the tools).

1. Get Data
  1. Occurrences
  2. Species
  3. Datasets
  4. Publishers
  5. Trends (link to global trend page)
  6. Citation guidance

2. Share
  1. Publishing in GBIF
  2. Dataset classes
  3. Step by step publishing guide
  4. Endorsement
  5. Darwin Core
  6. Digitizing collections
  7. Data papers
  8. Citizen science

3. Tools
  1. Publishing
    1. The IPT
    2. Data validator
    2. Suggest a dataset
    3. Collection management tools
  2. Developers
    1. The GBIF API
    2. ROpenSci
    3. The GBIF.org software
    4. The Atlas software (by ALA)
  3. Labs
    1. Species populations over time
    2. Species name matching   

4. Inside GBIF
  1. What is GBIF?
  2. The GBIF Network
  3. Become a member
  4. Literature
  5. Capacity enhancement programme
  6. BID programme
  7. BIFA programme
  8. News
  9. Featured data use
  10. Events
  11. Contact us
  12. Directory of contacts
  13. Newsletters and lists

**Comment by timrobertson100** [comment]
- @kcopas and I chatted and agree we consider where we want the R resource to go.  I propose it is really to direct folk to the RGBIF work, and we should link to a page describing the best ways to use GBIF with R, credit to Scott and link out to that

- GitHub would be mentioned on the GBIF.org software page I think, so not needed in the menu

- Added MAXENT

- Suggested that we do need a mega menu for the Inside GBIF.

@MortenHofft could you please start with this, use your judgement and then we can do a review?  See also #82. 


1. **Get Data**
  1. Occurrences
  2. Species
  3. Datasets
  4. Publishers
  5. Trends _(link to global trend page)_
  6. Citation guidance
2. **Share**
  1. Publishing in GBIF
  2. Dataset classes
  3. Guide to publishing
  4. Endorsement
  5. Darwin Core
  6. Digitizing collections
  7. Data papers
  8. Citizen science
3. **Tools**
  1. Publishing
    1. The IPT
    2. Data validator
    3. Suggest a dataset
    4. Collection management
  2. Developers
    1. The GBIF API
    2. RGBIF (rOpenSci) 
    3. The GBIF.org software
    4. The Atlases (ALA)
    5. MAXENT Modelling
  3. Other
    1. Species populations 
    2. Species matching
    3. Tools catalogue
4. **Inside GBIF**
  1. About
    1. What is GBIF?
    2. The GBIF Network
    3. Become a member
    13. Directory of contacts
    12. Contact us
  2. Info
    8. News
    4. Literature
    14. Newsletters and lists
    9. Featured data use
    10. Events
    11. Awards
  3. Capacity
    1. Capacity Enhancement Programme 2016
    2. BID programme
    3. BIFA programme

**Comment by MortenHofft** [comment]
menu has been added https://github.com/gbif/portal16/commit/2bd0650c3039bd6f784f29007910968b8469a471
config here: https://github.com/gbif/portal16/blob/2bd0650c3039bd6f784f29007910968b8469a471/app/models/menu.json
translations here: https://github.com/gbif/portal16/blob/2bd0650c3039bd6f784f29007910968b8469a471/locales/server/en.json#L1649

somemenu items needs proper links. this is the case where none was defined

**Comment by kcopas** [comment]
Would like to fine-tune the nav for the demo in Brasília if possible. Most would be tweaks of the tools sub-items (remove the the's, moving Living Atlases up in the sort). I'm also wondering about the reintroduction of 'capacity enhancement', given what we know about the lack of traffic to that portion of the current site (do people really know what it means? If they do, it seems they don't want to see it). I'd spell them out here now but would be inclined to get a quick read from @thirsch, too. 

Also, we lost Taxonaut in the transition—recognizing that it's relatively new, should that also find a place in the Developers? 

And what about GBIF Dataset Metrics, the 1st Ebbe Nielsen Winner—should that have a place?

**Comment by timrobertson100** [comment]
Thanks Kyle.  

Can you suggest a group name for the Capacity Enhancement section best?  It was the best I could come up with (note that it is not clickable, and "Capacity Support" is the name of the programme we run this year.

I think it is too early to feature Taxonaut.  I will write to him and explain what we'd like to do and get the code into GBIF repositories first.  That is not to say you can't present it, but I think it might be surprising not to have that communications first but for the item to appear in the menu.  It's on my list of TODOs... 

The dataset metrics EN prize is a plugin that only works for the old site.  I really don't think it is something we'd want to promote in the new one given it won't work.  We aim to encapsulate those ideas into the new dataset page as time allows.  I've suggested to the original authors they consider a contribution, and they have interest but no time to do it.  It is also what they now do as private contractors, so would likely ask for a contract.

**Comment by kcopas** [comment]
Adjustments, s.v.p.

Under 'Share'
+ 'Publishing' --> 'Data publishing'

Under 'Tools'
+ 'Publishing' --> 'Publishers'
+ 'Publishers > The IPT' --> 'IPT'
+ 'Developers' --> 'Users'
+ Changes and new sort order under 'Users'
    + 'The GBIF API' --> 'GBIF API
    + 'The GBIF.org software' --> 'Web application'
    + 'RGBIF (rOpenSci)' --> 'rgbif'
    + 'MAXENT'
    + **Move** 'The Atlases (ALA)' to 'Inside GBIF > Programmes + Projects' (see below)
+ 'Other' --> 'GBIF Labs' — seriously. We need something that prompts curiosity for these experiments, which we may or may not keep running. In the absence of a better suggestion, let's make it a working title for now.
+ 'GBIF Labs > Species populations' --> '[Something better ;-)]'

Inside GBIF
+ 'Capacity enhancement' --> 'Programmes + projects'
+ 'Capacity enhancement > Capacity support (2016)' --> 'Capacity enhancement'
+ 'Capacity enhancement > BID programme' > 'BID: Biodiversity Information for Development'
+ 'Capacity enhancement > BIFA programme' > 'BIFA: Biodiversity Information Fund for Asia'
+ 'Capacity enhancement > The Atlases (ALA)' > 'Living Atlases'

I know it will change more, but let's see how this looks.

**Comment by MortenHofft** [comment]
I will close. It has gone through a couple of iterations. f further changes is needed it can be reopened.

**Comment by kcopas** [comment]
Sorry, can you change 'Programmes + projects > Capacity support (2016)' to '.. > Capacity enhancement', please? Had it above, but it probably just wasn't clear.

Thx.

**Comment by timrobertson100** [comment]
Done
