### ISSUE TITLE
search catch all

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#616]
Examples of searches not returning expected results:

[search on specific DOI](https://www.gbif.org/resource/search?q=%2210.1111~2Fplb.12639%22&contentType=literature) (am expecting paper entitled "How much do we know about the frequency of hybridization and polyploidy in the Mediterranean region?")
[search for simple, but specific term](https://www.gbif.org/resource/search?q=%22zika%22&contentType=literature) (am expecting papers about Zika)

**Comment by MortenHofft** [comment]
Could you when possible also link to the item that you expect in there? Fx the title of above item you expect. That makes it easier to evaluate. Currently it could be because it wasn't in the index (i trust that it is, but just to be sure)

**Comment by dnoesgaard** [comment]
Sure, will do.

**Comment by MortenHofft** [comment]
Found.
https://www.gbif.org/resource/search?q=%22https:~2F~2Fdoi.org~2F10.1111~2Fplb.12639%22&contentType=literature

but would be nice if the `10.1111/plb.12639` alone also worked

**Comment by dnoesgaard** [comment]
Yes, and the other two results seem to be included because of a shared DOI prefix, which seems a bit _too_ fuzzy, at least in this case.

**Comment by dnoesgaard** [comment]
Here's another example of search being a little too fuzzy:

[searching for "broad-nosed weevil"](https://www.gbif.org/resource/search?q=%22broad-nosed%20weevil%22) (I'm guessing the hit is based on "evil")

**Comment by MortenHofft** [comment]
> searching for "broad-nosed weevil" (I'm guessing the hit is based on "evil")

I guess this one brings up the issue of wether we would rather not show anything at all when there is no perfect match vs always showing our best matches.

I understand this example as a case of "don't show me results that aren't a perfect match"? At least not if quoted?

**Comment by MortenHofft** [comment]
Thinking about the DOI search. Searching free text for DOIs doesn't go well with fuzzy search.

**Comment by MortenHofft** [comment]
@dnoesgaard  All of the above cases work now (assuming that we agree on what we want) - could you please test as well. It is all too easy to develop blind spots

**Comment by dnoesgaard** [comment]
I'm quite happy with the way search works now. I haven't seen any unexpected results since this was assigned to me. @kcopas, did you have any comments?

**Comment by MortenHofft** [comment]
I do - the literature is taking too much attention now i would say (when there is no search query). But I can tweak that i think
