### ISSUE TITLE
Content item for the data validator

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal16#618]
To be displayed here:
https://www.gbif-dev.org/tools/data-validator/about

**Comment by dnoesgaard** [comment]
You can use this one: 5n0ZOctI1as04aUCgyYqsC

**Comment by dnoesgaard** [comment]
My first draft for the *About* page is ready. For now, only in GBIF-DEV space.

(also accessible via [/about-data-validator](https://www.gbif-dev.org/about-data-validator))
