### ISSUE TITLE
Login and registration

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#619]
**ORCiD login perhaps postponed**
ORCiD has been suggested as something we should integrate with - among other things for login.
But it is being questioned if we should [postpone the ORCiD login](https://github.com/gbif/portal16/issues/297) until we can do more with it.

**Other logins like Facebook**
But for convenience a Facebook and Github Login fx might still make sense. Is this something that we should go forward with @kcopas and @timrobertson100 ? 

**State**
Technically it is all the same - and is largely ready. So it is really a question of what we want. 

**Why**
I personally think of it as a casual user convenience. Github as a chance to autofill the Github username on feedback. But other than that we probably cannot use that information for much. Perhaps a picture of the user for future public profiles? Do we want to see facebook on GBIF.org?

![screen shot 2017-10-19 at 08 45 54](https://user-images.githubusercontent.com/6759267/31757602-f82c8860-b4a9-11e7-83ed-fbb76c41bef7.png)

**Comment by MortenHofft** [comment]
Quoting @kcopas and @dnoesgaard freely from memory

> Sure do it. Not essential and no one have asked for it, but might be convenient for some.

I'm personally in favour because I appreciate it myself as I can never remember all those passwords. And for users that aren't using the site daily I believe that is a nice service. And it was all prepared anyhow with the intention of doing the ORCiD logins.

**Comment by dnoesgaard** [comment]
Btw, if we allowed logging in via Github, the credentials could be applied when reporting issues too (I assume)...

**Comment by MortenHofft** [comment]
Perhaps - would be nice. At the very least we can autofill contact

**Comment by timrobertson100** [comment]
On the registration and log in I'm inclined to think it useful to log in / create an account with FB, GH, Google, ORCID etc purely for convenience reasons (note GBIF still need a country though).  Adding a "Did you know that you can connect your account to FB, GH, ORCID etc and log in using those credentials?" seems reasonable too.  I don't see a reason why ORCID should be treated differently to GH.  

The [point made on the other thread](https://github.com/gbif/portal16/issues/297) about strategic thinking is valid, and something we've also discussed here.  I understand that more to be a concern if GBIF overly promote it though - as in "why did you strongly recommend me to do that?" - but for accounts... it's pretty standard now.

**Comment by dshorthouse** [comment]
What happens when a user logins with multiple OAuth2 providers? I assume those would all be treated as separate accounts because there's no way to determine if a FB account holder is the same as a GH account holder. As has happened to me when doing this, you'll invariably receive support requests to "merge" accounts.

What makes you think GBIF wouldn't overly promote it?

If there's ever any intention to have a user's profile page made public, you'll have to think very carefully about what OAuth2 provider can give you want you want & reduce, if not eliminate, the need for custom fields for a user to maintain his/her account profile on GBIF.

**Comment by timrobertson100** [comment]
> What happens when a user logins with multiple OAuth2 providers?

GBIF accounts require a unique password.  If a user tries to create an account using a provider presenting an email already associated it would inform them the email is already in use and an "I've forgotten my details" options would be presented.  This would allow the reset password email be sent and info that the account is linked to e.g. a GH identity.  If they have set it up to use a different email then a new account would be created - that seems unavoidable and people can already register with different emails.

> you'll invariably receive support requests to "merge" accounts
Yes although I don't foresee that as much of a burden (currently 2 SQL statements) and I imagine a fairly rare occurrence.  This seems unrelated to OAuth2 though as the same can happen today.

> If there's ever any intention to have a user's profile page made public, you'll have to think very carefully about.. 

Can you provide some more information on your concerns here please? We'd have to think carefully about any profile info made public and I can't think of much that a G!, GH etc account would provide beyond name and email that would be used.

**Comment by dshorthouse** [comment]
> Can you provide some more information on your concerns here please? We'd have to think carefully about any profile info made public and I can't think of much that a G!, GH etc account would provide beyond name and email that would be used.

That's largely my point. You don't get anything useful from G!, GH. But, you do get potentially a lot of meaningful information from ORCiD.

`curl --header "Accept:application/orcid+json" https://pub.orcid.org/v2.0/0000-0001-7618-5230`

**Comment by timrobertson100** [comment]
Thanks @dshorthouse.  I am missing something here still - can you elaborate on why you feel that is a reason not to let people use ORCID for providing an authentication service though?

**Comment by dshorthouse** [comment]
Actually, my argument is the opposite - to use ORCiD exclusively - because you get lots of potentially useful information from which you can populate a profile, keep it up-to-date, and make use of the ORCiD for future enhancements (when and if we get a DwC-A extension for agents & their actions that would potentially also indicate one's ORCiD). You don't get the same from other providers, which means one's GBIF profile would be dependent on which authentication service a user chooses to employ.

**Comment by timrobertson100** [comment]
(accidental close there from iPhone)

Thanks @dshorthouse, I understand your point now and sorry for the confusion.

If someone had used another identity provider, that would not preclude them for later linking their ORCID identity.  Using ORCID exclusively is worthy of consideration, but like the other thread - we need a strong reason to promote it which we don't yet have the tooling for. I get where you are coming from and thanks for the input!

**Comment by MortenHofft** [comment]
Github and facebook login has been added. We are in dialog with ORCiD about ORCiD membership and pricing
