### ISSUE TITLE
show open access / peer review on literature items

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#620]
Idea: show the [OA logo](https://en.wikipedia.org/wiki/Open_access#/media/File:Open_Access_logo_PLoS_white.svg) on literature items that are openAccess=true

E.g.

![screen shot 2017-10-20 at 13 14 46](https://user-images.githubusercontent.com/21358085/31818492-b4d6821a-b598-11e7-884a-f31228006135.png)

We could also include peerReview=TRUE - here stolen from PLOS One:

![lit-oa-pr](https://user-images.githubusercontent.com/21358085/31818677-7810310e-b599-11e7-8deb-6f12765b8596.png)

**Comment by MortenHofft** [comment]
I only did the openaccess one (top mock). The other felt a bit cluttered when there was also DOIs, keywords, etc.Just reopen if you feel that it is a shame that peer review isn't there in the format of your last mock

**Comment by dnoesgaard** [comment]
How about simply adding a (perhaps green) &#x2714; in front of the OA symbol for peer-review?

**Comment by dnoesgaard** [comment]
![screen shot 2017-11-01 at 14 32 27](https://user-images.githubusercontent.com/21358085/32277043-858a1918-bf11-11e7-842d-110defe2cec1.png)

is it too much?

**Comment by MortenHofft** [comment]
I've added chips instead. That is what we use elsewhere I remembered

**Comment by dnoesgaard** [comment]
ah ok cool...

btw I think the OA logo needs to be aligned with the text somehow. looks a bit odd.

**Comment by MortenHofft** [comment]
I think I'll just remove it then. no need to have it twice. thanks
