### ISSUE TITLE
Update species names

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal16#631]
So there seems to be a logical flaw in the update routine (the fuzzy matching is too forgiving). I don't know exactly what is happening behind the scenes, so this has somewhere from minimal to big impact.

2014: COL first lists Atriplex northusana as a species 
http://www.catalogueoflife.org/annual-checklist/2015/details/species/id/15adc98e2ea27307681beae3478f2495
2015: GBIF imports the record and gives it an accepted status. A species "homepage" is generated.
2016: The name gets removed and changed (for whatever reason). ITIS and COL change the name (and the way that COL works, it also gives a new species ID to Atriplex northusanum Weim.
Source: http://onlinelibrary.wiley.com/doi/10.1002/fedr.19120112104/full
The old record can not be found any more in these databases! (you can grab the problem by the roots here)
However: https://www.gbif.org/species/7977331
Only updates the references and lists the 2015 COL dump still as a primary source, although this dump is outdated and contains potentially invalid names that have been corrected in the past.
BUT the fuzzy matching routine matches all new names to the existing old species "homepage"...

Ways to prevent this:
- If a new COL version gets released the new lists get prority over already existing names from the same data source.
- Give me a red fat warning at the top of the page. It is not realistic to expect ppl to check every name in the reference list for mismatches.
- Majority vote. If the majority of references cites a different name, update the species backbone, or give me a visual warning if there is a mismatch in the "reference" list.
- Disable fuzzy matching completely. (It causes more harm than good.)

Thanks for reading this late night gibberish!

Summary:
Name changes in databases are not updated in GBIF consequently. GBIF retains the old legacy dataset and lists the new name as fuzzy match to the old name, although the old name does not exist in any database any more except GBIF. The longer this goes on the more errors will accumulate. This is a systematic error and can not be fixed individually.

TLDR: If a species name is no longer listed, but was listed before in the same dataset, some action must be taken.

**Comment by MortenHofft** [comment]
closed as duplicate
