### ISSUE TITLE
Data repository

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#633]
Implement a front end for the data repository

* What are the endpoints 
    * search: freetext, user filtered
    * get and get file
    * create - what is the format

**Comment by MortenHofft** [comment]
```
GET -> List: http://api.gbif-dev.org/v1/data_packages/
params: q, offset, limit, user, fromDate, toDate, tag (it can be specified multiple times)
```

**Comment by MortenHofft** [comment]
From Tim Robertson

**flow**
```
#New upload
Instructions: Upload a minimum of one file.

… Drag drop or file upload 

# Basic information
Title: [… ] required
authors: 
  [family name, given names] [affiliation] [ORCID optional]  x +
  (In order of citation priority)
Description 
  [
     MD based rich editor
  ]
Citation: [ prefilled ] 
  Instructions: Use the default (reset link) or write a custom format
License:
  [ x ] CC0 
  [  ] CC-BY 
  [  ] CC-BY-NC

[Publish]
```

**fields**
```
Title: 
  Counts by country for redlisted plant species

Files: 
  counts.csv
  process.R
  occurrence.txt

Authors:
  Tim Wilkinson - IUCN - ORCID_XYZ
  Steve Bachman - Kew Gardens - ORCID_XYZ

Description:
Based on a GBIF download (doi:…) we ….
This is documented in the process.R

License:
CC-BY
```

Suggests to take cues from https://zenodo.org/deposit/new

**Comment by MortenHofft** [comment]
Required fields as described by metacite 
https://schema.datacite.org/meta/kernel-3.1/example/datacite-example-full-v3.1.xml

![screen shot 2017-11-03 at 11 52 01](https://user-images.githubusercontent.com/6759267/32370460-6f41f978-c08d-11e7-80eb-f289013819c6.png)

Notice that this also means that asking the client to generate the metadata becomes somewhat complicated when DOI is unknown.

**Comment by MortenHofft** [comment]
Based on our conversation. Is it correctly understood that there will be API changes and creating is now the following?

```
POST http://api.gbif-dev.org/v1/data_packages/
params: file, fileUrl (accepts http(s), ftp(s), hdfs), data_package
file and fileUrl can be repeated

data_package is JSON containing the data package definition:
{
  "title":"Test Title",
  "description":"Test Description", //optional
  "publisher":"Nature",
  "publicationYear": 2018,
  "creators": [
    {
      "name": "firstname lastname",
      "affiliation": "BGBM",
      "identifier": "23450987/2345", //always an orcid for us
    }
  ]
}
```

**Comment by MortenHofft** [comment]
From conversation

POST is synchronous in the sense that it won't return with a status or key until everything is uploaded. If the user is pointing to a large external file this means that the session will hang. But it doesn't matter if you close it since the upload will continue. But you won't know what the DOI is until the POST endpoint returns a result. If the user uploads or points to a large file this could take hours or more.

This is a temporary solution that is expected to work well for now. At some point the API might return a job-id or key that can be used to check the status. It might also send mails at some point.

**Comment by MortenHofft** [comment]
https://github.com/gbif/portal16/issues/633#issuecomment-341675030 confirmed by Tim

**Comment by MortenHofft** [comment]
It has been decided to keep the name `dataPackage` and use that JSON to create both the Datacite metadata and the dataPackage info. This means that if we in the future decide to allow those to be different we will then introduce a new field or file for the Datacite metadata.

**Comment by MortenHofft** [comment]
@fmendezh a summary of our talk
the API will return plain text for errors with a descriptive error message in english. This will be displayed as is to the user as an explanation when errors occurs.

**Comment by MortenHofft** [comment]
Currently the API do not expose citation, authors, license or an download-all-files-url
I guess this is something we will add before going live?

**Comment by MortenHofft** [comment]
Regarding citation - this is from datacite and seem to be inline with what we do for datasets

> In keeping with this approach, the following is the preferred format for rendering a DataCite citation for human readers using the first five properties of the schema:
>`Creator (PublicationYear): Title. Publisher. Identifier`
>
>It may also be desirable to include information from two optional properties, Version and
ResourceType (as appropriate). If so, the preferred form is as follows:  
>`Creator (PublicationYear): Title. Version. Publisher. ResourceType. Identifier`

**Comment by timrobertson100** [comment]
Looking at examples from [the Arctic Data Centre](https://search.dataone.org/#view/doi:10.18739/A2KV9G), [Zenodo](http://www.nature.com/nm/journal/v6/n1/full/nm0100_100.html?foxtrotcallback=true) and [Nature](http://www.nature.com/nm/journal/v6/n1/full/nm0100_100.html?foxtrotcallback=true) it looks like the [DataCite recommended guidelines](https://www.datacite.org/cite-your-data.html) make good sense.  For GBIF that would mean:

> Hendrix H., Reading N., Michell M. (2017): Observations while touring with the Jimi Hendrix Experience. GBIF. doi:10.10101/dp.123456.

I'd suggest we follow that up with the author affiliations list similar to a paper does so that it is prominent on the page.

**Comment by MortenHofft** [comment]
Summary of a conversation with @ahahn-gbif and @jlegind

**So far it looks good**
The autogenerated citation format is good. And the overall flow of searching and uploading and seeing uploads is fine as well. 

**Modelling provenance**
But there is a desire to link an uploaded archive to the datasets that have contributed data. And a need to have a `replaces this doi` or is derived from x. Basically some way to model the relations. This would also allow us to give proper credits to datasets in cases where the upload in case is a archive derived of datasets in GBIF.

We therefore propose to extend the API with additional files describing relations. The exact formats and names and how many is still to be decided. But could be an additional file a la
```
derrivedFromFile: datasets.csv

uuid;records //both uuid and DOIs should be supported
83e20573-f7dd-4852-9159-21566e1e691e;2393
...
```

Next step would be to look at existing standards from Datacite and see how they fit our needs.

**Comment by MortenHofft** [comment]
**Editing deposited data**

> NB this can be considered version 2

It seems reasonable to be able to edit parts of an upload.

* Files (add only)
* Authors, description, title (add and remove)
* License (only to more relaxed)

Once doing an edit, there should be an option to describe your changes and the reason.

Edits will trigger a new minor version of the dataset. This will go into the citation. The history of the edits should be available in the API.

Aside from the change history it might make sense to add an upload date to the files and a modification date to the metadata.

**Comment by MortenHofft** [comment]
**Replace upload with newer version**
Update on relations. From [Datacite Kernel 3.1](http://schema.datacite.org/meta/kernel-3/doc/DataCite-MetadataKernel_v3.1.pdf) which is the one we use.

This seems to be for cases where the files need to change

```
IsNewVersionOf  

indicates A is a new edition of B, where the new edition has been modified or updated.

<relatedIdentifier relatedIdentifierType="DOI" relationType="IsNewVersionOf">10.5438/0005
</relatedIdentifier>

Use for a version making previous version(s) obsolete.
```

It has the counter tag `IsPreviousVersionOf`

**Comment by MortenHofft** [comment]
**Copys for having a reference to verbatim crawls before processing**
`IsIdenticalTo` is the related identifier seemingly

> indicates that A is identical to B, for use when there is a need to register two separate instances of the same resource

**Comment by MortenHofft** [comment]
**Derrived products**
`IsDerivedFrom` This seems to be the most useful for us and one we could use to model the relationship between a custom upload by - say Jan - and the datasets it is complied of.

**Comment by MortenHofft** [comment]
@fmendezh should we perhaps keep the original file name and seperate it from the url where it can be downloaded from?

```
checksum : "9102844c536821b9cc03ce13d113997c"
fileName : "http://api.gbif-dev.org/v1/data_packages/10.5072%2Fdp.tkllai/gbif-observations-dwca.zip"
size : 184095285
```

Basically I'm thinking that `http://api.gbif-dev.org/v1/data_packages/10.5072%2Fdp.tkllai/gbif-observations-dwca.zip` isn't really a filename, but the url/path. In the download API we call it `downloadLink`.  So I suggest:

```
downloadLink : "http://api.gbif-dev.org/v1/data_packages/10.5072%2Fdp.tkllai/whatever-you-want-it-to-be"
fileName : "gbif-observations-dwca.zip"
```

**Comment by MortenHofft** [comment]
Uploads as they would look now if creators, license and citation was in the API.

![upload](https://user-images.githubusercontent.com/6759267/32559461-7bcb379a-c4a7-11e7-9349-65a4c74b039b.png)

**Comment by MortenHofft** [comment]
Based on the Datacite documentation I suggest this format for the dataPackage json

```
POST http://api.gbif-dev.org/v1/data_packages/
params: file, fileUrl (accepts http(s), ftp(s), hdfs), relatedIdentifiers (csv file as alternative to filling the form), dataPackage
file and fileUrl can be repeated

dataPackage is JSON containing the data package definition:
{
    "title": "Test Title",
    "description": "Test Description", //optional by Datacite required by us
    "license": "some license",  //optional by Datacite required by us
    "citation": "something", //optional by Datacite will be autogenerated if not filled,
    "creator": [
        {
            "name": "firstname lastname",
            "affiliation": ["BGBM"], // 0-n
            "identifier": "23450987/2345", //always an orcid for us
            "nameIdentifierScheme": "ORCID", //defaults to ORCID
            "schemeURI": "http2://orcid.org" //default
        }
    ],
    "relatedIdentifiers": { //could be one long list with relationType in the object or splitting per types as keys . here split per key
        "IsDerivedFrom": [ //this could be a very long list
            {
                "relatedIdentifier": "http://something/1234"
                "relatedIdentifierType": "URL | DOI | ..." //see docs for options
            }
        ],
        "IsIdenticalTo": [...],
        ...
    }
}
//always filled by backend: publisher, publicationYear
//filed by backend if not provided: citation
```

**Comment by MortenHofft** [comment]
This is mostly implemented, but final testing is blocked by API issues https://github.com/gbif/data-repo/issues/2 https://github.com/gbif/data-repo/issues/3 and https://github.com/gbif/data-repo/issues/4 labelling as blocked
