### ISSUE TITLE
Redirect from old data validator to new

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#634]
I've just archived the Contentful item that previously appeared here:
https://www.gbif.org/tool/81281/darwin-core-archive-validator

If you would be so kind, please redirect that URL to the new validator, located at:
https://www.gbif.org/tools/data-validator

**Comment by MortenHofft** [comment]
Hmm - if it is to be considered as the new one it would make sense just to update the content i would guess. I think Thomas intended to use the tools item. But I see that there is no content on https://www.gbif.org/tools/data-validator/about nor on https://www.gbif-dev.org/tools/data-validator/about - so perhaps something is missing implementation. Let me check

**Comment by MortenHofft** [comment]
@kcopas I'm un-archiving it as it seems better than having nothing and the content doesn't strike me as being critically wrong. If so please re-archive it

**Comment by MortenHofft** [comment]
ahh - https://www.gbif.org/tool/81281/darwin-core-archive-validator is not archived. I suspect the wrong item was archived

**Comment by kcopas** [comment]
Suspicion's correct—sorry, I was obviously flagging at day's end. Old tool now archived, for realz. I can see that you republished the new item—tak.

**Comment by MortenHofft** [comment]
@kcopas Instead of 

* creating a new tools item about the validator
* archiving the existing tools item about the validator
* redirecting the old url to a new content item

wouldn't it make better sense to simply update the text in the original item? Then we wouldn't have two items and redirects. If you agree, I will copy the content from the new one into the old one and discard the new one instead.

**Comment by kcopas** [comment]
Perhaps, but I feel I'm coming into this quite late in the process, and I don't know the underlying logic of what's gone on before.

As you can see, @thomasstjerne has done (what I presume is) some custom development to make the tool show up with a Contentful 'About' page that @dnoesgaard authored. This is the new work.

The old page is a 'standard' tool page—nothing more, nothing less.

Given all this, I suspected that it may in fact be simpler to create a redirect, rather than reauthor and replace. 

I'll defer to others as to the best course of action, but meanwhile, I probably need to hold the news item that was a few minutes away from going live.

**Comment by MortenHofft** [comment]
I'll remove the new one then and keep the old.

This is to avoid proliferation of content items and redirects when it is indeed the same item and should seem like so to the end users.
