### ISSUE TITLE
User download list

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#64]
If a user is logged in, they need to be able to see a list of their downloads, as per current GBIF.org

**Comment by kbraak** [comment]
I'd like to propose that a user should be able to indicate that they have used/cited a particular download in a journal article. 

I'd also like to propose that users have the possibility to manage their own list of downloads. As long as a download hasn't been cited in a journal article, they should be able to delete unused or duplicate downloads themselves. This will allow GBIF to free up disk space. Of course the DOI for the download will still resolve to a page explaining the user has deleted the download.
