### ISSUE TITLE
confirm domain ownership to Facebook

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#645]
Facebook is implementing restrictions on what level of control you have over the stuff you post. If you confirm ownership of your domain name, you will retain full control of posts linked to this domain. I've requested that our FB page is associated with the gbif.org domain, but to confirm this one of the below two options is required:

1) a TXT record in the DNS of gbif.org

```@ IN TXT facebook-domain-verification=6z4d6a8uxbgxx69n273nnqwa81mjn2```

2) HTML verification file accessible from gbif.org website

This [file](https://gbif.box.com/s/0c02vwon5p5995i4zhcfqh3nq5du2p9g) must be accessible by visiting http://gbif.org/6z4d6a8uxbgxx69n273nnqwa81mjn2.html

Let me know if you need additional details.

**Comment by dnoesgaard** [comment]
[Info from Facebook](https://www.facebook.com/business/help/247886969033572)

**Comment by MortenHofft** [comment]
I opt for the DNS one if it is easy @MattBlissett because then i don't have to do something specific for prod builds (since the file shouldn't be on uat/dev I assume. Or adding it to the build for prod only?

**Comment by MattBlissett** [comment]
Done, please check if it works.

**Comment by dnoesgaard** [comment]
Thanks. Verification done. Fairly sure you can remove the record again...
