### ISSUE TITLE
Dataset registration information not displaying as expected

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#648]
Hi @peterdesmet I moved your issue here. It seemed like it deserved an issue of its own.

----

I'm logged in, I have connected my ORCID to my account and I am viewing a dataset with my ORCD (this one)... but I don't see the extra crawling metrics.

Also, you mention:

On dataset pages, the crawling info is shown at the top (instead of the bottom) if you are a trusted contact for the dataset. Along with some more details. It also shows if crawling is off.

I don't see this crawling info at the bottom either (for other datasets or when I'm logged out).

**Comment by MortenHofft** [comment]
The ORCID part should be fixed and in production. I'm still not sure about the other part. Could you send me a screenshot of what you are seeing / or description of what you expect seeing please?

**Comment by peterdesmet** [comment]
Hi @MortenHofft there are still 2 issues:

1. The ORCID part does _not_ seem fixed in production as far as I can see.
2. Basically a question: what (crawling) info is publicly available for a dataset? In other words: what is a non-logged in, non-trusted contact supposed to see on a dataset page regarding crawling?

**Comment by MortenHofft** [comment]
1. Damnit! I don't get it. I'll look again.
2. the things in the bottom from here https://github.com/gbif/portal16/issues/6#issuecomment-352436360 will be available to everyone on every dataset. So the only difference when logged in is:
  a. It is in the top of the page.
  b. you are allowed to start a crawl
  c. It links to the crawl history
  d. it shows if crawling is currently off
  e. shows a visual breakdown of crawl attempts (red/green grid)

**Comment by MortenHofft** [comment]
This bug hasn't been successfully replicated. it works in tests. it works for other real users accounts. Further investigation is needed.

**Comment by peterdesmet** [comment]
This issue has been resolved for me. Thanks a lot!
