### ISSUE TITLE
Page for download

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#65]
Implement the equivalent of http://doi.org/10.15468/dl.hl8mg4 

Note, that it checks if the file is available, and if so the download link is shown.
- [ ] Add NFS mount for the downloads folder
- [ ] Implement page

**Comment by kbraak** [comment]
Ideally we will begin maintaining a list of 'isCitedBy' relationships for the download hence we plan to monitor its usage in journal articles. Therefore I'd like to propose that if we know the download was used in a journal article that we provide a link to the article from the download homepage. 

Special care should be taken to ensure that a download that has been cited gets protected against routine cleanup/deletions.

**Comment by MattBlissett** [comment]
We already have an NFS mount to the downloads folder, where occurrence-ws runs.

The current portal calls that service to test if the download exists: https://github.com/gbif/portal-web/blob/master/src/main/java/org/gbif/portal/action/occurrence/util/DownloadsActionUtils.java#L92

**Comment by MortenHofft** [comment]
closed with https://github.com/gbif/portal16/commit/e81a8f068a7d89c74b49cc9adb2b2f8c961929bf and https://github.com/gbif/portal16/commit/fa5cf58bb7ee2a58a3507e46ed2b5fd54bc47d01

**Comment by MortenHofft** [comment]
More changes than I expected had to be done on this page. I couldn't get myself to reproduce errors. For some see below picture explaining the changes.

![downloadkey_improvements](https://cloud.githubusercontent.com/assets/6759267/22920605/36de6c58-f296-11e6-9aac-a18df1109adb.jpg)
