### ISSUE TITLE
add image cache to System health

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#656]
We just had a problem with the image cache and no images were shown on gbif.org. It would be nice to 1) make sure alerts to system admins are working and 2) if possible,  add the service to the system health overview.

**Comment by MortenHofft** [comment]
We have a lot of systems that aren't tested for on the health pages. What we have now is the front end trying to compensate for a missing status endpoint by building its own with the most critical and presumed fragile endpoints. But to do it proper with access to all relevant info it should be done in e.g. Nagios.

**Comment by MortenHofft** [comment]
image cache added as a separate system. I'm afraid that the backends can fail in many ways the front end won't detect and that is likely to always be the case. 

Best thing is probably to:
* add additional testing when it happens (if it is something that can be tested for by the frontend)
* use the functionality in contentful to do a custom warning to the users

**Comment by MortenHofft** [comment]
closing in favour of https://github.com/gbif/nagios-configuration/issues/2
