### ISSUE TITLE
Species detail page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#66]
The species detail page discussions have included:
1. Consider carefully top of fold information for accuracy (e.g. marine, non-marine etc)
2. Use e.g. IUCN Redlist, CITES etc APIs to bring in accurate information on official species status
3. Consider if we want to show species images from checklists or occurrence images 
4. Do not include harvested wikipedia info, but consider showing Wikipedia info in branded iFrame (@MortenHofft has ideas to use a pane sliding in from right)

DH and others will be keen to see iterations early to help offer direction

**Comment by dnoesgaard** [comment]
The names of higher taxonomic levels (family and up) shouldn't be italicized, right?

<img width="783" alt="fabaceae" src="https://cloud.githubusercontent.com/assets/21358085/21042587/a711df2e-bdf2-11e6-9b62-bb9f17eec87b.png">

**Comment by mdoering** [comment]
Indeed not

**Comment by mdoering** [comment]
Still to be done:
- [x] display species descriptions
- [x] show image gallery

We do not want wikipedia descriptions for the backbone, but the ones coming from Plazi or Pensoft journals are well curated and received information. I would suggest to modify the clb-ws to exclude wikipedia datasets for backbone extensions. Or maybe remove wikipedia datasets alltogether from CLB?

As for images we face similar issues. I would say we should show all images but the wikipedia ones. Again we can modify the clb-ws to ignore those datasets or remove them completely

**Comment by kbraak** [comment]
Related outstanding issue showing taxonomy hierarchy - https://github.com/gbif/portal16/issues/281 Also part of this blocker @MortenHofft?

**Comment by mdoering** [comment]
See also #338 and #137

**Comment by mdoering** [comment]
A nice example of species descriptions we have indexed: http://www.gbif.org/species/8585062#description

**Comment by mdoering** [comment]
Working on gbif/checklistbank#27 to filter backbone extension data

**Comment by thomasstjerne** [comment]
The Species detail page have been reworked and the issues reffered to in this thread arwe closed. I am closing this, but new issues targetting the current version of the page are welcome.
