### ISSUE TITLE
Add up citations and activity from earlier versions of a dataset

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal16#660]
for example:
https://www.gbif.org/dataset/830c7b08-f762-11e1-a439-00145eb45e9a 
is the old version of 
https://www.gbif.org/dataset/0b94e07b-898e-47fc-b95f-31a5538f326b

We correctly show that the old deleted dataset has a new version. However, the citations and activity is not transferred to the new dataset.

If the API could be queried like 
http://api.gbif.org/v1/dataset?duplicateOfDatasetKey=840ebec6-f762-11e1-a439-00145eb45e9a
We could add the citations and activity from ealier version to the current.

**Comment by MortenHofft** [comment]
Adding them seems nice, but I'm not keen on doing a front end merge from two endpoints. If we are certain that the activities should be merged this should be done in the database shouldn't it? and the activity perhaps removed from the the old one.

**Comment by MattBlissett** [comment]
Closing in favour of https://github.com/gbif/portal-feedback/issues/4102
