### ISSUE TITLE
Fix usability bugs in CMS facet filters

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#67]
@MortenHofft / @burkeker - please can you complete this issue text?

**Comment by MortenHofft** [comment]
example: http://internal.gbif-dev.org/cms/search?q=argentina&type=tool 
should show applied filters
![screen shot 2016-10-14 at 15 26 16](https://cloud.githubusercontent.com/assets/6759267/19389027/99285948-9222-11e6-9ca2-c52bcdc19851.png)

**Comment by burkeker** [comment]
I think eventually we should force Drupal to export the facet property regardless the count of result. I've tried workarounds that don't further engineer facet info handling. Will find a way to fix it once for all.

**Comment by burkeker** [comment]
The merging of resource type and content type into one facet didn't cover the case when there is no content type facet returned from the CMS API. Fixed as https://github.com/gbif/portal16/commit/421d0e31b8877b2f2caaa8feaa103f6c53f2b85c.

At the same time, earlier we saw sometimes country filter label are shown as not translated for a query like cms/search?q=frog&category_country=us :
![country not translated](https://cloud.githubusercontent.com/assets/637631/21524140/26a871a0-cd14-11e6-975c-7d6bce9d9da1.png)

There are two issues behind this: 1) The API side didn't return country code after parsing filter params, and 2) keys in translation file is case-sensitive. Both are addressed at https://github.com/gbif/portal16/commit/855a2abd8624fd7a87b02b6a1275f6c9d8118797 and https://github.com/gbif/gbif-drupal/commit/0b36294dfddcce238fc6321b06f85a78ad47dc66

![country translated](https://cloud.githubusercontent.com/assets/637631/21524468/8b1db42c-cd16-11e6-927f-8d8ef615778a.png)
