### ISSUE TITLE
Data papers page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#68]
GBIF is the top resulton a google search for "Data paper", and but our page is not very appealing http://www.gbif.org/publishing-data/data-papers
- [ ] Wireframe / create a visual for a cleaner data paper page
- [ ] Implement the required CMS content type to support the wireframe
- [ ] Implement the page

**Comment by kbraak** [comment]
Kindly take note of this [related IPT issue](https://github.com/gbif/ipt/issues/1171#issuecomment-252904312). Here I suggest the new page would benefit from having an overview of tools that can be used to create data papers such as the [Arpha writing tool](http://arpha.pensoft.net/) by Pensoft plus a list of journals where data papers can be published.

**Comment by kcopas** [comment]
Defer to @timrobertson100 and @dnoesgaard, who will take lead on this page.

**Comment by timrobertson100** [comment]
@dnoesgaard 

Please see https://dl.dropboxusercontent.com/u/608155/transient/data-papers.html which I threw together using Stackedit.io.  This basically pulls together the logos of the publishers (3 missing) and then takes the text content from http://www.gbif.org/publishing-data/data-papers.

When you click to view the journals it would list the table of journals per publisher (like on http://www.gbif.org/publishing-data/data-papers) expanding like other sections we have on the new site.

With correct logos, what do you think as the content for a first implementation, which we could then refine later?  

We should add text about the functions that the IPT offers to aid authoring, and the Arpha writing tool makes sense to mention too I think.

**Comment by dnoesgaard** [comment]
@timrobertson100,

First of all, thanks for getting the ball rolling on this one.

Could the table of journals be like the one with projects on http://demo.gbif.org/programme/programme/bid?

Is the "Most recent papers" directly fed from Mendeley?

**Comment by timrobertson100** [comment]
Hi Daniel.

Layout would be consistent with the rest of the site, so I was thinking
that kind of table yes.
I was thinking it could be hidden, and then with the "downward arrow more"
button you click and it expands, which Morten has used elsewhere on the
site (although I can't seem to find one).

I was just playing to see if the logo mashup would be of interest or not.
I'm honestly not sure if it works or not...  Morten / Burke would help on
the visual aspects though

**Comment by dnoesgaard** [comment]
@kbraak I wanted to include information about arpha, but when I played around with it, it seems it only supports one journal (Biosciences) when you import metadata from an IPT - is that correct from your understanding?

**Comment by dnoesgaard** [comment]
Correction: Biodiversity Data Journal is the name of the journal, not Biosciences...

**Comment by dnoesgaard** [comment]
@kcopas I'm happy with this one now. As per @kbraak and others, I've included information on the Arpha writing tool as well as the SiBBr "NephilaPaper" tool...

**Comment by dnoesgaard** [comment]
I made the decision to remove the "Recommends GBIF" column, as per comments from Donald et al. The rest, I feel, are fine for (at least) Release 1.

APC and Impact factor rarely change, so keeping the table up-to-date shouldn't be time-consuming.
