### ISSUE TITLE
registration - better feedback on taken username/email

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#683]
users do not get any useful feedback if the username/email they are trying is already taken

**Comment by MattBlissett** [comment]
Bonus feature: if the user is using the "register" form rather than "login", but puts in a correct user and password, just log them in.

(The user who found the problem has very poor English.)

**Comment by MortenHofft** [comment]
Regression error - broken by https://github.com/gbif/portal16/commit/885bed6cde7affe5322bafc889567725b56c2afc#diff-12a60a0ad8e80231a56d73cac8ac436eR180
