### ISSUE TITLE
Google indexing don't follow their own documentation

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#685]
despite their documentation Google do index pages that arent listed in the sitemap as is clear from the link below.

![screen shot 2018-02-22 at 01 24 52](https://user-images.githubusercontent.com/6759267/36513356-84d3bf22-176f-11e8-9d8d-1d04aefedf22.png)

@MattBlissett i still think we should remove it from search. Let me know if you can think of an easy client way to do so. I guess removing search from indexing is one option, but I'd rather not. Is filtering the API very time consuming?

**Comment by MattBlissett** [comment]
Try http://api.gbif-dev.org/v1/organization?isEndorsed=true

**Comment by MattBlissett** [comment]
Reopening, since changes to the portal will still be needed.

**Comment by MortenHofft** [comment]
this is done
