### ISSUE TITLE
The GBIF Network page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#69]
We wish to create an appealing page that captures a summary of what is going on in a region.

Early thinking is to have a page including:
1. Hero text with (e.g.) "GBIF is a network of institutions, systems and people.  Together we have connected X datasets covering Y species and Z evidence based occurrence records.  The network of people provide..." etc
2. A clean map with layers of e.g. occurrence data, locations of installations, locations of participant orgs, locations of institutions where there have been papers written, boundaries of voting / non voting participants.  Toggle controls to switch on and off
3. A tab view, allowing a selection of region (Asia, Africa, Europe etc) whereby on each tab we have a table of participants to click through to participant page (e.g. country page) and showing the key info about the region - e.g. the regional contact person, latest news, latest events etc (whatever is easily possible)

The intention is to capture required functionality like a map of participation, and also to give any visitor the impression that _something_ is going on near them.  It would replace the list of countries on the country page, and data trends entry points on current site.

**Comment by kbraak** [comment]
What about representing some participants like OBIS as the global network they are? Is there a plan to make a dedicated network page for them in the new portal? 

I ask because there is an [outstanding IPT issue](https://github.com/gbif/ipt/issues/986) to enable associating a dataset to a network. Of course associating a dataset to a network is still a manual process for now. It would be nice to either close this issue or plan its implementation in the future. Thanks.

**Comment by timrobertson100** [comment]
There will be a heavy revision of Network pages in 2017 so please keep it open.  
It is likely that this will include a revision of the network API.

On the initial implementation of this page the Organisation participants will simply be listed, and will link to pages similarly sparse to how they are today (i.e. no regression).

**Comment by kcopas** [comment]
Early white board sketch of proposed page:
[https://www.flickr.com/photos/polymetis/shares/9QMZzS](https://www.flickr.com/photos/polymetis/shares/9QMZzS)

**Comment by MortenHofft** [comment]
Descriptions is in contentful, but needs filling

**Comment by dnoesgaard** [comment]
Noticing a few issues that need to be addressed (#381)

**Comment by MortenHofft** [comment]
Signed of by Tim Hirsch with a few lingering comments captured in seperate GH issues
