### ISSUE TITLE
occurrence page shouldn't show invalid multimedia items as images

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#693]
prompted by https://github.com/gbif/portal-feedback/issues/1209

the occurrence page doesn't check well enough if a multimedia item is displayable as an image and instead shows as failed. Perhaps it should display more clearly as badly mapped or alternatively not at all

**Comment by MortenHofft** [comment]
@MattBlissett do you mean embedding linked html pages in an iframe!?

**Comment by MattBlissett** [comment]
No! Isn't that blasphemy‽

Just that it could be clearer what the box of multimedia is.  For multimedia, the identifier probably isn't the most interesting thing, so perhaps:

```
This occurrence has external multimedia:
* <Still image> of <description> by <creator>, CC-BY
* <Video> of <description> by <creator>, All rights reserved
```

where those lines are links.

**Comment by MortenHofft** [comment]
ahh. the table is really just one example of all the extensions. So they are all treated equally. But we could change that. The idea was to have a fallback for all extensions - simply showing a table with the fields.

**Comment by MortenHofft** [comment]
There are still improvements to be made, but the issue of showing non images as images is a  duplicate of https://github.com/gbif/portal16/issues/676
