### ISSUE TITLE
occurrence search map filter

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#704]
The new map filters has some bugs and feature regressions
* When drawing a polygon the directive should automatically add
`has_coordinate=true`
* It shouldn't be possible to choose both the rectangle drawing tool and the polygon drawing tool at the same time
![screen shot 2018-03-22 at 15 08 26](https://user-images.githubusercontent.com/6759267/37775311-f05fdf76-2de2-11e8-90ba-69ac8a4b3e53.png)
* it should be possible to deselect the tools (in case i selected two or want to pan instead)
* the resulting WKTs should respect the right hand rule : Closed by https://github.com/gbif/portal16/commit/cc4c1347ad309e1a70c3f7ce7eab77389abdd0fd
* When the user choose `No preferences` in the filter the geometry query is erased, but the map isn't updated to reflect it.
![screen shot 2018-03-22 at 15 12 48](https://user-images.githubusercontent.com/6759267/37775597-a60c552a-2de3-11e8-864f-96171f273ee2.png)
* Drawing a polygon should set the include suspicious flag. else doing a refresh will change the filters.
* starting a drawing, but then selecting the trash can doesn't stop the drawing. instead drawing will do unexpected zooms
* Pressing delete didn't use to delete everything. It is useful to be able to delete a single geometry on the map.
* Deleting single geometries using the checkboxes below the map doesn't work either
* We used to be able to edit geometries. Personally i liked that feature.

**Comment by MortenHofft** [comment]
the delete button now edits instead

**Comment by MortenHofft** [comment]
https://www.gbif-staging.org/occurrence/charts?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-18.50626%209.77973,43.03617%209.77973,43.03617%2057.63346,-18.50626%2057.63346,-18.50626%209.77973))
looks like this
![screen shot 2018-03-23 at 16 37 25](https://user-images.githubusercontent.com/6759267/37838555-83940d3c-2eb8-11e8-9edb-f135505ad6dd.png)

notice that has_geospatial_issue=false isn't true

**Comment by thomasstjerne** [comment]
> the delete button now edits instead. sometimes if you click enough it will delete though
No, but edit is enabled and triggered if the user points close to the edge of a polygon. 
Now I disabled the snap function while in delete mode.

Regarding has_geospatial_issue=false, I can´t reproduce it. When I follow the link, the checkbox isn´t checked. @MortenHofft Can you reproduce the steps that ended up with this state?

**Comment by MortenHofft** [comment]
Sure. click include coordinates. click include suspicious coordinates. draw a polygon. voila.
