### ISSUE TITLE
Data repository UAT not working as expected

### ISSUE THREAD

**Issue by jlegind** [gbif/portal16#705]
Trying to upload to the data repo (https://www.gbif-uat.org/data-repository/upload) using the following files fails.
* [GBIF_interpreted_species_names.txt](https://github.com/gbif/portal16/files/1840898/GBIF_interpreted_species_names.txt)
* Metadata section completed
* Author: Jan Legind + ORCID 
* License: CC0
* Related identifiers: [related_identifiers.txt](https://github.com/gbif/portal16/files/1841129/related_identifiers.txt)

> The upload failed 
> Unknown error occurred

**Comment by MortenHofft** [comment]
@fmendezh i get this error from the API `The orcid 0000-0002-4953-5220 does not exist`

1) it does exist. It is mine.
2) the error message isn't returned as an object as other errors are, but instead as a string. This seem to be recurring. that errors are sometimes strings sometimes objects.

**Comment by MortenHofft** [comment]
closing in favour of the issues created in the data-repo
