### ISSUE TITLE
Unhandled promise failure

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#711]
https://github.com/gbif/portal16/blob/58fcc84142a3099a7e7fa65685624cf63ca4c6ab/app/controllers/api/dataset/taxonomy/taxonomy.ctrl.js#L51

**Comment by MortenHofft** [comment]
Same here
https://github.com/gbif/portal16/blob/58fcc84142a3099a7e7fa65685624cf63ca4c6ab/app/controllers/api/dataset/taxonomy/taxonomy.ctrl.js#L62

**Comment by thomasstjerne** [comment]
https://github.com/gbif/portal16/blob/58fcc84142a3099a7e7fa65685624cf63ca4c6ab/app/controllers/api/resource/search/resourceSearch.ctrl.js#L86
