### ISSUE TITLE
taxonomy breakdown sunburst doesn't cancel old requests it seems

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#714]
Was seen in prod when:
changing filters 10 times in rapid succesion.
The sunburst would then redraw. wait 10 seconds redraw again. wait 5 seconds the redraw again. and at the same time show a message that it failed (also after completion)

<img width="521" alt="screen shot 2018-03-27 at 15 15 06" src="https://user-images.githubusercontent.com/6759267/37969810-05b1914c-31d2-11e8-9ce2-5c95c0320737.png">

**Comment by thomasstjerne** [comment]
It cancels requests properly - but it seemed that canceled requests triggered the error message.

![cancelled](https://user-images.githubusercontent.com/1666484/38235756-7d05f35a-3722-11e8-9436-09d962cfd5f1.png)
