### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#72]
To include info on the various helpdesks etc users should use to ask for help
- [ ] Detail the page content in comments below
- [ ] Implement page

**Comment by kcopas** [comment]
[Current page](http://www.gbif.org/contact/contact-us) is extremely minimal.

> For general inquiries, email info@gbif.org.

For press and media inquiries, email communication@gbif.org.

For technical issues relating to publishing or use of data, email the GBIF helpdesk.

For other contacts in the Secretariat and GBIF advisory committees please refer to the Directory of Contacts.

You can find contacts for GBIF delegations and nodes staff for your own country on the Participant pages, which you can access from here. <

Propose bumping up the presentation and content.

**Comment by MortenHofft** [comment]
https://demo.gbif.org/contact-us there is a page, but it should be in the menu and the article format might not be ideal for the purpose.

**Comment by kcopas** [comment]
@kcopas to get a photo of our red cube to replace the hero image. 

Don't think we should present ourselves as pigeons (but maybe that's just me…)

**Comment by MortenHofft** [comment]
I still believe there is work to do on this page, but it is hardly a blocker i would say. Please change it back if anyone disagrees.

**Comment by MortenHofft** [comment]
suggestion for a people photo http://dev.gbif.org/issues/browse/POR-1944?jql=project%20%3D%20POR%20AND%20status%20%3D%20Open
