### ISSUE TITLE
Create network items in Contentful (similar to what we do for participants)

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#747]
I have created it in dev space and an example item for OBIS

content type
https://app.contentful.com/spaces/qz96qz790wh9/content_types/network/fields
OBIS item
https://app.contentful.com/spaces/qz96qz790wh9/entries/7okaKTs6hao0MaeIOo6Aoo

but for some reason it isn't indexed properly. Fede is aware of that and is looking into it.

Once this works we should repeat it in prod and decide on what fields we need in collaboration with coms

**Comment by dnoesgaard** [comment]
Have more or less duplicated the model from the DEV space now. Example item:
https://app.contentful.com/spaces/uo17ejk9rkwj/entries/56QA7KTXh6QAqm0Ak8e0Uw

**Comment by dnoesgaard** [comment]
Is there anyway for me to preview the content? Perhaps on staging?

**Comment by MortenHofft** [comment]
try uat after this build https://builds.gbif.org/job/portal16/1762/
