### ISSUE TITLE
Add the v2/map api layers

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#75]
When the new maps are ready show them on the various detail pages
- [ ] Create demo of how to use the layers in leaflet
- [ ] Create CartoCSS for the colouring
- [ ] Implement new maps
- [ ] document v2 in developer maps API docs

**Comment by MattBlissett** [comment]
@MortenHofft, the maps aren't yet ready for production use, I need to add monitoring, automatic deployments, a dev and UAT server etc.

But they are ready for fiddling with — URLs should now be stable, and the bugs shouldn't have much effect on using the tiles.

I think I'll put the majority of information specific to projections on https://tile.gbif.org/ui/ , and reference it where necessary from the APIv2 page.

**Comment by MattBlissett** [comment]
Other existing documentation:

* https://api.gbif.org/v2/map/demo.html
* https://api.gbif.org/v2/map/debug/ol/ (this is the fanciest I got with OpenLayers).
