### ISSUE TITLE
Country reports, phase 2 (scoping): reorganization of information on the country pages

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal16#757]
### Context: 
In the present shape, country reports are 8-page pdf documents linked from a country page like https://www.gbif.org/country/DK/summary via the "Country Report" download button, top right (e.g. https://www.gbif.org/sites/default/files/gbif_analytics/country/DK/GBIF_CountryReport_DK.pdf). The reports were designed as a prototype version, based on a community consultation and prioritization process for information elements that should be contained. Since the time the reports were designed, most information elements that are included in the pdf document have now also become available in the web pages. Not all information in the report had been by user demand and needs to be reproduced in this form; especially the charts on pp. 4-6 were added to gauge interest in this kind of information. In addition, the generation of these reports in pdf format proved to be forbiddingly expensive in terms of work time required. The last available round of reports is from Dec 31, 2016. Based on the experiences with the prototype version, the next version of country reports is no longer to be document-based, but to be integrated with the site itself, making relevant elements downloadable where indicated.

**Community consultation** result summary report ("Summary report: consultation on GBIF national reporting service", 02-09-2015): https://gbif.app.box.com/file/289723305589

**Target audiences and use scenarios**, i.a.:
- Node managers to provide as handouts to their own constituency, to explain network engagement and activities, as well as return on investment (here esp. usage related data)
- Secretariat staff to bring to meetings as an "extended visiting card", demonstrating our state of information about a country, and providing clues on worthwhile discussion subjects
- hand-outs for workshops, both for participants from member- and non-member countries, to support engagement and outreach

**Immediate tasks:**
- [X] remove the "Country Report" button from the country page (all tabs)
- [X] tab "publications": change the default for the list from "about" country to "from" country

### Basic decisions (up for review):
_"CR#' refers to the page in the current country report pdf document, as do the quoted headers for each point._

- **integrate the elements that are considered core information relevant to a country into the summary tab of the country**  (https://www.gbif.org/country/DK/summary). Ensure that the page is printable.

1. "Data availability in [country]", occurrence counts per kingdom (CR1): use the **kingdom** breakdown counts and icons presently at tab "Data about" underneath the map, and add then to the summary tab (close to "data about [country]" map) - _please verify that 'data about [country]' is what the report really intends in this place_. Add _a link_ to the "Data about" tab, where the breakdown counts for lower groups of taxa are given - priority 1
2. "Access and usage" (CR1): numbers on researchers from Denmark contributing to articles citing GBIF use [summary count of number of articles in reporting period and total number of articles since 2008] - priority 1
3. "Data mobilization" (CR1): add chart Fig.2: Number of records published by institutions in [country], categorized by kingdom (= chart 1 on tab Data Publishing > Number of occurrence records > Records by kingdom) - priority 1
4. "Access and usage - web traffic on (...)" (CR2): basic decision: provide only a limited set of parameters, offer access to Google Analytics on request to those with an interest in more detail (add a line "Want to know more? Request access to GoogleAnalytics _here_"). Omit the Google Analytics numbers and chart from the upper section of the report page, but consider how to include a table equivalent to Table 2: comparative view of web traffic for GBIF.org from users worldwide, from [country] and to the country's national portal (where available). NB: this last section had been added on request, but not been made use of in the present country reports. - priority 2
5. "Access and usage - data downloads on GBIF.org (...)" (CR3): add content for both items to the summary tab: a) number of download requests from [country] in the last calendar year, and percentage compared to total downloads; b) Fig.4 number of occurrence records downloaded via gbif.org published by institutions in [country] over time (last calendar year) - priority 1
6. "Access and usage - Recent peer-reviewed articles (...)" (CR3): add 3 most recent to the summary page, and follow with a link to "more". The link leads to the "publications" tab for the country, showing the full list. Additional general requirement: the default for the filter at https://www.gbif.org/country/[countryCode]/publications should be set to "from", not to "about". - priority 1
7. "Data availability - Change over time (...)" (CR4, fig.6): add a link to the graphic "species count by kingdom" from tab "Data About" (NB Figure 5 from the CR is already covered under point 3, above) - priority 1
8. "Data mobilization - most recent datasets (...)" (CR6): include the top 3 most recent into the summary tab, and add a "see all" link that filters all datasets from publishers in [country] (link in the CR) - priority 1
9. "Data mobilization - Newest publishers (...)" (CR6): include the 3 most recent in the summary tab, but filter for only those that are already publishing datasets. Add a "see all" link that filters for all publishers from [country] - priority 1
10. "Data mobilization - Data sharing with country of origin (...)" (CR7). Add figure 13 of the CR, which is presently showing at bottom of the charts on the Data Publishing tab (Data sharing with countries of origin). Consider how best to include the counts on number of countries covered (presently showing above the "data from" map, but without a link), and especially the number of contributed occurrences and concerned datasets. Link to the tables on the Data publishing tab (countries and areas; datasets) - priority 1
11. "Data mobilization - Top data contributors" and "- Top datasets contributing _about_" (CR7): 
Add tables of top contributing countries and occurrence counts and top contributing datasets with occurrence counts, both with a link to "see all", referring to the tables on the Data about tab. For tables with record counts, consider supplying a printable or downloadable version ("download csv" or similar).

- **enrich with additional features / information that were not yet available at the time of the initial consultation / report generation, to produce a new and improved version / demonstrate added value** - _sequence indicates priority_

1. translation (or option for ~)
2. projects: top 5 (?) projects that the country is involved in, e.g. from the context of BID, CESP, BIFA, ALA collaboration, etc
3. data use stories - feature stories on data use, relevant to the country (collapse in view and print if no items are available). Possibly use the boxes with just the image and header line, as on the website(?)
4. dataset statistics (most indicative to be decided)
5. regional level involvement / information: regional membership, regional projects and activities
6. news and events relevant to the country (collapse if unavailable) - this will need checking whether a print-friendly version is possible, in the sense of the amount of text needed to still make it meaningful in print.
7. people? _This will need more scoping, and is pending the implications of privacy requirements_

**in future** (not yet available), consider:
1. highlighting data gaps / mobilization opportunities

- **enrich the "Data about" and "Data publishing" tabs where needed, and ensure that the summary page links to/from the relevant sections, so that the information can be pulled together easily**

1. "Data availability" for selected taxonomic groups in [country] (CR4): Extend the "by kingdom" counts that are currently shown on these tabs underneath the maps to include the selected taxonomic groups. Suggestion: keep the kingdom counts and icons as well, and add the lower groupings alongside, with some visual distinction between the two levels (color variation on icons like inversion or different color) - priority 1
2. same section, percentage changes: still needs decision. Is this information useful, especially given very variable absolute numbers?

- **to be retired or referred:**

1. "Access and usage" (CR1): global chart on the left - undecided, but likely better placed in a central location, and just referred to
2. "Access and usage" (CR2): top section (table 1: top five cities by number of sessions in [country], fig. 3: Number of sessions by week originating in [country] - most likely to be retired and replaced by a reference to GoogleAnalytics access
3. "Data availability - Change over time in records about (...)" (CR5-6): do not include in the summary, just maintain in the data publishing and data about tabs as-is. Consider a reference from the summary page, pointing explicitly only at the first two (occurrence records per kingdom over time, and number of species with records per kingdom over time). Plans on including these graphics at a higher "summary" level should first evaluate the audience, as these graphs were not originally included by request, but out of opportunity.
4. "Global overview" (CR8): this area of information does not have a natural place in the country pages. If the summaries on access and usage, data availability, data mobilization per country and recent news can be linked from elsewhere, then the summary tab should contain a link. This need further scoping, since the old country landing page linked in the report no longer exists.

- **Related open questions:**
1. web traffic values from Google Analytics: automation of number retrieval and possibly storage for reporting (GA API access?)
2. can we still provide snapshot versions for a fixed time period (esp. calendar year)? We would consider it a feature that the reports are more dynamic and up-to-date in principle, but some use cases will still require information focused on a fixed reporting period.

**Comment by ahahn-gbif** [comment]
For complete overview of the country report data sources, see https://www.gbif.org/country-report-data

**Comment by kcopas** [comment]
This looks great, Andrea—thanks. Two questions only.

1. Can we ask Mélianie to review this proposal before we put anything in motion?
2. Recognizing that it's well down on the overall priority list, where can we capture the discussion about a proper data usage db that records long-term data on downloads etc. for use in the various comparative charts and tables where we already make use of them, e.g. bimonthly PPT updates?

**Comment by thomasstjerne** [comment]
We need to clarify which taxonKeys are associated with:
- Flowering plants (49 ?)
- Gymnosperms (194,244,228, 78) ?
- Ferns (59 ?)
In the current backbone. Suggestions in parentheses, but probably incomplete.

**Comment by ahahn-gbif** [comment]
If we go for accepted classes/names, I think we need (@mdoering @MattBlissett: double-check, please?)
- Flowering plants: 
Magnoliopsida (220)
Liliopsida (196)
-- I would be a bit careful about the p.p. synonyms of phylum Tracheophyta in this context --
- Gymnosperms:
Cycadopsida (228)
Ginkgoopsida (244)
Pinopsida (194)
Gnetopsida (282)
- Ferns
Polypodiopsida (7228684)
Equisetopsida (246)
Marattiopsida (7228682)
Psilotopsida (7219203)
-- this is excluding the related Lycopodiopsida: 245 --
-- if we need to include synonyms, then also:
Polypodiophyta (7473139)
Pteridophyta (59)
