### ISSUE TITLE
Species trends over time tool

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#76]
Develop replacement for http://gbif.github.io/species-population/frontend/dist/ as a tool in GBIF.org

**Comment by MortenHofft** [comment]
implementation started with https://github.com/gbif/portal16/commit/724d1f30af8c256599e3f3b3e5b6564d51331068

issues and ideas

* [ ] there seem to be cross origin issues with tiles on dev
* [ ] parameterize endpoints
* [ ] charts need to reflect drawn polygon
* [ ] disable hexagon selection when drawing
* [ ] only allow one polygon?
* [ ] notify users on invalid polygons. What is an invalid polygon according to SOLR?
* [ ] either change SOLR to accomodate Leaflet and MapbBox drawing tools across dateline or create shared classes to use across maps when compossing queries
* [ ] draw selected hexagon. could probably be done many ways - but API changes might be necessary. the mapbox feature doesn't provide a geometry to draw.
* [ ] tracking ideas for GA?
* [ ] disable min years when drawing and add explanation
* [ ] link to cms article explanation. suggested endpoint tools/species-population/about
* [ ] style charts
* [ ] better chart library. 
  * [ ] possibly overlay the two charts and have a dual y axis. 
  * [ ] hover info. 
  * [ ] year selector on chart - as alternative to the year slider on the map.
* [ ] adjust year extent based on years of data - requires API changes
* [ ] show regression errors

**Comment by MortenHofft** [comment]
WKT standard says that polygons (that enclose something and not exclude) should have their coordinates ordered counter clockwise.

BUT js libraries do not convert that way - they keep the order that they are drawn in.
https://github.com/mapbox/wellknown
https://github.com/arthur-e/Wicket

Secondly the WKT standard says no coordinates outside the 180 longitude bounds. That isn't adhered to either. And it is unclear how to handle dateline wrapping without accepting it. Leaflet and Mapbox instead allow for breaking that rule. 

@fmendezh and I have decided to follow those conventions and handle it in the API.
That should make it easier for API users. The downside is that for now it won't be possible to do queries for polygons with holes in them. Neither do everything-but-this-area queries.

How to handle it internally in the API is still up for discussion

**Comment by MortenHofft** [comment]
The Mapbox function queryRenderedFeatures isn't stable.
it snaps to the wrong zoom level it seems. clicking next to the yellow hexagon will match a polygon on another zoom level. Zooming slightly more in and it wont appear.

![screen shot 2016-12-16 at 13 47 28](https://cloud.githubusercontent.com/assets/6759267/21263366/9a8d1706-c396-11e6-97c4-25952f6a5b09.png)

It doesn't seem to be in our end, but will investigate more before filing issue with Mapbox

**Comment by timrobertson100** [comment]
That might also explain some slowness on hover over for mousemove - if it is keeping polygons from non visible zooms ganging around

**Comment by MortenHofft** [comment]
> The Mapbox function queryRenderedFeatures isn't stable.

https://github.com/gbif/maps/commit/7302b84e718f285c23823da6e793070671ec2b9f 
the api now returns 204s instead of empty 200s when there is no data. That seems to solve it.

**Comment by MortenHofft** [comment]
closed as of https://github.com/gbif/portal16/tree/2d78e600271eaca254018395926be27008de0e60

There is still many ideas for improvements. these will be captures in a separate issue
