### ISSUE TITLE
Change email subscription form

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#763]
We're using the occasion of GDPR to switch email service providers from MadMimi to MailChimp, which means that we need to swap out the form embedded on the newsletters page:
https://www.gbif.org/newsletters

I've got a new MailChimp sign-up form here:
http://eepurl.com/du73YP

But unfortunately, it doesn't seem so simple as changing a source URL in the current code:
> <iframe src="https://madmimi.com/signups/302099/iframe" scrolling="no" frameborder="0" height="735" style="max-width: 600px; width: 100%;"></iframe> 

@thomasstjerne and @MortenHofft, I'm sending you admin invitations to the MailChimp account in the hope that you can get to any necessary source.

**Comment by MortenHofft** [comment]
simply replaced with a iframe as before. I think we should replace it with a custom form instead. But this is better than a wrong form as same as before
