### ISSUE TITLE
occ map coordinate popup has confusing beahviour

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#765]
https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&taxon_key=2972841&geometry=POLYGON((2.62916%2048.59526,18.36703%2050.45403,7.94373%2055.93384,2.62916%2048.59526))&geometry=POLYGON((9.41045%2044.80176,16.26117%2044.49212,15.22986%2048.39408,9.41045%2044.80176))

no matter how many times i click "Yes hide them" the popup lingers.

The behaviour of this popup has changed.
It used to only show if you looked at the map and hadn't specified anything about geometry or weather to include/exclude suspicious data. Not it simply shows always and you cannot close it.

**Comment by MattBlissett** [comment]
For what it's worth, I don't get the popup at all with that query on Firefox.

**Comment by MortenHofft** [comment]
Thanks - I have a feeling it is erratic and depends on how you navigated there
