### ISSUE TITLE
popup wont disappear

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#771]
arrive by 
https://www.gbif.org/dataset/dc0f5f98-630c-42e1-a129-286b744d6b3e click taxonomy
https://www.gbif.org/species/134997452?root=true

the popup insists on being there. This is a new bug

it is also weirdly off to one side.

**Comment by thomasstjerne** [comment]
Due to https://github.com/gbif/portal16/commit/57721011b40ff87fc3d11ec221c43d42f24f1133#diff-d1bf411ebb5a9eb9f9552bcdb733d362

**Comment by MortenHofft** [comment]
this is till the case

**Comment by thomasstjerne** [comment]
Not if a root is selected in the popup as intended.
