### ISSUE TITLE
Show content type on homepage cards

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#779]
To give people a clearer understanding of what we're featuring on the homepage, I suggest adding a little card type indicator to the corner - much like what we're doing in search results, e.g.

![gbif-cardtypes](https://user-images.githubusercontent.com/21358085/40774876-02e70532-64c7-11e8-8b22-5771ac4ca5bf.png)

- For the automated cards, the type would be based on the content
- for the manual features, we can add a new field that has this info

Thoughts?

**Comment by MortenHofft** [comment]
sure - we had it in the past, but I removed it for some reason. probably simply beacuse i found it prettier. I can readd it.

**Comment by dnoesgaard** [comment]
Ok cool, couldn't remember. Let me know if I should add a field to the features content model in Contentful...

**Comment by dnoesgaard** [comment]
Hey @MortenHofft - wanted to revisit this idea as it's becoming more relevant with blog posts, etc. appearing on the home page.

For the items shown automatically, the type is derived from, yes, the content type, but for the items represented by features, we need a field in the content model. If so, how do you prefer we handle this, also thinking about translations...?

**Comment by MortenHofft** [comment]
Yes the contenttype will of course need to change - I have done so to get it closed.
