### ISSUE TITLE
Directory of contacts

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#78]
The directory of contacts should provide a simple way to get an overview of the various committees etc, and to find the contact details for the people with dedicated GBIF roles.

Suggest drawing user UX / layout guidance from the GBIF directory.

**Comment by burkeker** [comment]
The demo of this page has done and issues reflected during the demo has been addressed, too. Please re-open if there is still any outstanding issue.

**Comment by dnoesgaard** [comment]
We just noticed this in the directory, not sure where the error is:

<img width="949" alt="demo_gbif_org_directory_contact-us_executive_committee" src="https://cloud.githubusercontent.com/assets/21358085/20710563/57466ab4-b63b-11e6-83f4-8fb56824b42e.png">
