### ISSUE TITLE
country/area clarifications

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#782]
In the bottom of data use items (and others, perhaps?), can you please reword these:

Researchers country -> Country or area of researcher
Country coverage -> Country or area of coverage

Thanks!

**Comment by dnoesgaard** [comment]
![climate_change_-_a_double-edged_sword_for_invasive_species_](https://user-images.githubusercontent.com/21358085/40783101-b6a5b036-64e1-11e8-8c57-81a6ac3f6782.png)

**Comment by MortenHofft** [comment]
sure they ought to be taken from the same translation anyhow - thanks
