### ISSUE TITLE
Setup production infrastructure for portal16 to go live

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#80]
**CMS things:**
<s>
- [x] Set up new development CMS server (devcms-vh.gbif.org)
  - [x] Make mapping through Varnish (cms-api.gbif-dev.org) 
  - [x] Check development configurations correct
- [x] Set up new UAT CMS server (uatcms-vh.gbif.org)
  - [x] Make mapping through Varnish (cms-api.gbif-uat.org) 
  - [x] Check development configurations correct
- [ ] Set up new Production CMS server (prodcms-vh.gbif.org)
  - [ ] Make mapping through Varnish (cms-api.gbif.org) 
  - [ ] Check development configurations correct
- [ ] Set appropriate caching and access rules in Varnish
</s>

- [ ] Set up things for Contentful-based CMS.
  - [x] Set up servers (ES, monitoring)
  - [ ] Set up regular content crawls
  - [ ] Anything else?

**Image things:**
- [x] Set up and document Thumbor server
  - [x] Make mapping through Varnish
  - [ ] Set appropriate caching rules in Varnish (e.g. may actually want to cache errors for a short time, to avoid hammering clunky image servers)
  - [ ] Improve logging of Thumbor, preferably to ELK installation.

**Varnish etc. things:**
SSL to API
- [x] Enable SSL access to api.gbif-dev.org, on a separate server (only APIs), api2.gbif-dev.org
  - [x] Buy and set up SSL certificate (using Letsencrypt temporarily)
- [x] Enable SSL access to api.gbif-uat.org, on a separate server (only APIs), api2.gbif-uat.org
  - [x] Buy and set up SSL certificate (using Letsencrypt temporarily)
- [x] Enable SSL access to api.gbif.org, on a separate server (only APIs)
  - We already have an SSL certificate

SSL to website(s)
- [x] Enable SSL access to demo.gbif-dev.org, on a separate server (only websites)
- [x] Enable SSL access to demo.gbif-uat.org, on a separate server (only websites)
- [x] Enable SSL access to demo.gbif.org, on a separate server (only websites)

HTTP/2
- [x] Enable HTTP/2 access to api.gbif-dev.org
- [x] Enable HTTP/2 access to api.gbif-uat.org
- [x] Enable HTTP/2 access to api.gbif.org
  - **Potential blocker** HTTP/2 in Varnish 5 is not yet ready for production use.  It doesn't support RST, which is how the browser says it's no longer interested in a response, e.g. because the map has been zoomed in before it has fully loaded. The next Varnish release is due in March. We could wait until then (and it might not have full support), do without HTTP/2, or use an alternative HTTP/2 implementation.

**Comment by MattBlissett** [comment]
HTTP/2 is not ready in Varnish 5.0. The next Varnish release is to be in March 2017.

I'll leave the HTTP/2 support enabled on api2.gbif-dev.org and api2.gbif-uat.org for the moment — when the browser sends an unsupported request, Varnish simply crashes and restarts.

The Varnish 5 configuration isn't completed yet, a few parts are still commented out. Once it's completed, we should get the user-facing bits of the portal to use the secure APIs, so we can see they're working before moving the portal to HTTPS.

- [ ] Migrate remaining parts of our Varnish configuration to Varnish 5
- [ ] Load test Varnish 5 server
- [ ] Load test Varnish 5 server through Hitch

- [ ] Switch off Varnish's HTTP/2 support

**Comment by kbraak** [comment]
@MortenHofft is it safe to assume this issue should be labelled a release blocker?

**Comment by MattBlissett** [comment]
I also want to
[ ] Permit access using TLS1.0, to be roughly equivalent in security to a site like amazon.com.
At present, it's more strict, which blocks users with particularly old browsers.

**Comment by MattBlissett** [comment]
HTTP2 is now enabled for demo.gbif-dev.org, api.gbif-dev.org, demo.gbif-uat.org and api.gbif-uat.org, and also the relaxed HTTPS configuration.

@MortenHofft, could you 

- [ ] Configure the UAT portal to use (at least) images and map tiles from api.gbif-uat.org

so we can better test it.  (Including removing using the `{a-e}-api` hostnames).

Tomorrow, I'll enable HTTP2 on demo.gbif.org, with the relaxed HTTPS configuration.  I'll only enable it on api.gbif.org once we've seen that Varnish doesn't crash.

The logs in Kibana have a `httpversion` field: http://elk.gbif.org:5601/goto/5d50ce3893b32139cc2f4b81ebca3a9b

If Varnish crashes, it will show up in `journalctl -xn 100 -u varnish` on a Varnish server. It will restart automatically.

**Comment by MattBlissett** [comment]
@fmendezh, could you update this with what's needed for the Contentful CMS to go live.  Just some Elastic Search servers like develastic-vh?

**Comment by MattBlissett** [comment]
The three new servers for ElasticSearch on CMS content are now ready: ElasticSearch 5.2.2 installed, and monitoring in Ganglia and Nagios.

The nice names are:
- cms-search.gbif-dev.org
- cms-search.gbif-uat.org
- cms-search.gbif.org

(The real names are devcmssearch-vh.gbif.org etc)

**Comment by KeithUSF** [comment]
Regarding the "image things / caching" bullet point, will this include tweaking Varnish/Thumbor to check for http 304 responses?

**Comment by MattBlissett** [comment]
Hi Keith — could you give an example? Are you seeing many requests for the same image from thumbor-vh.gbif.org / 130.225.43.57?

Thumbor is supposed to cache images for a month. I haven't investigated whether it issues a conditional GET when images expire from the cache; if not it would be particularly nice for the museums serving 100MB TIFFs.

**Comment by KeithUSF** [comment]
I think you can ignore this, sorry. It appears that Thumbor **is** caching on your end (refreshing the page didn't result in a Thumbor image request). Right above a Thumbor 200 response there was a Googlebot-Image 304 response, which got me worried. That and the fact that our logs look like this:
`2017-09-15 04:15:13 #.#.#.# GET /img/248198.jpg - 80 - 130.225.43.57 Thumbor/6.3.2 - 200 0 0 1731`
`2017-09-15 04:15:15 #.#.#.# GET /img/293045.jpg - 80 - 130.225.43.57 Thumbor/6.3.2 - 200 0 0 2886`
`2017-09-15 04:15:16 #.#.#.# GET /img/275000.jpg - 80 - 130.225.43.57 Thumbor/6.3.2 - 200 0 0 4586`

... 16 additional requests ...

`2017-09-15 04:15:22 #.#.#.# GET /img/261589.jpg - 80 - 130.225.43.57 Thumbor/6.3.2 - 200 0 0 10062`
`2017-09-15 04:15:23 #.#.#.# GET /img/239527.jpg - 80 - 130.225.43.57 Thumbor/6.3.2 - 200 0 0 11013`
`2017-09-15 04:15:24 #.#.#.# GET /img/263374.jpg - 80 - 130.225.43.57 Thumbor/6.3.2 - 200 0 0 11575`

and that last column is the time taken (ms). But I assume the increased response time is due to servers being in different continents.  Thanks for the quick response!

**Comment by MattBlissett** [comment]
No problem.

If this is a Linux server, something like
```
grep 130.225.43.57 logfile | cut -d ' ' -f 5 | sort | uniq -c
```
would show duplicate requests for the same file.

I think people like scrolling through pages like https://www.gbif.org/occurrence/gallery?publishing_org=253fc67c-c7fb-4c85-88f5-43ac6d9dc8a9 , which can cause a lot of requests to a single server the first time.

Do let us know if bandwidth or server load becomes a problem.
