### ISSUE TITLE
Create generic content entries

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#82]
The menu links to generic content entries which need drafting.  They should be created as stubs, with correct URL mapping, so the content team can complete the pages autonomously.

The following are proposed URLs which can be revised if desired.  We (@MortenHofft and @timrobertson100) have considered and _deliberately_ chosen a URL strategy that does not directly mirror a multi-level menu.  This is because we have menu groupings whereby the group may not have a page so `parent1/parent2/child` may only have `child` with no `parent1` or `parent2`.  Imposing a URL structure that implies this is not intuitive to the user.  Secondly we expect the menu will change around and thus URLs change.  Instead, we choose concise, visually attractive (e.g. for search results) URLs.

All of these should be generic content entries:
- [x] http://gbif.org/publishing (a page that introduces what publishing in GBIF actually means)
- [x] http://gbif.org/publishing/dataset-classes
- [x] http://gbif.org/publishing/endorsement  (placeholder - see #81 )
- [x] http://gbif.org/publishing/darwin-core
- [x] http://gbif.org/publishing/digitizing-collections
- [x] http://gbif.org/about (linked to menu item `What is GBIF?` and likely from homepage)
- [x] http://gbif.org/citizen-science
- [x] http://gbif.org/membership (linked to menu item `Become a member`)
- [x] http://gbif.org/governance
- [x] http://gbif.org/awards 
- [x] http://gbif.org/citation-guidelines

**Comment by burkeker** [comment]
All stubs are in place. Go to http://drupaledit.gbif.org/admin/content and filter by type = generic and start to fill in. Please still work from the address above.

For now they are draft to prevent external access, but their status will be changed to published once deployed to cms.gbif-dev.org so on the new site they are indexed and searchable.

- [ ] include cms.gbif-dev.org in the cron jobs.
- [ ] tweak deployment to automatically publish all generic nodes.

**Comment by burkeker** [comment]
@kcopas @dnoesgaard just to get your attention here that those stubs are in place. This issue will be closed after verifying daily sync and deployment are functioning well.

**Comment by MortenHofft** [comment]
Seem to work fine - will close
