### ISSUE TITLE
license isn't prominent on checklist images on species pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#827]
e.g. https://www.gbif.org/species/100324419

**Comment by thomasstjerne** [comment]
If the images are clicked, they show up in a lightbox with the license in the caption

**Comment by kcopas** [comment]
Sorry, fwiw, but the caption as it stands is contradictory—(c) is different from CC whatever. We need to spell out the specifics, either through regular characters or CC glyphs.

Something like this for the latter? 
https://github.com/cc-icons/cc-icons
