### ISSUE TITLE
Drafting: Publishing page 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#83]
A page linked from the menu describing what data publishing in GBIF actually means.

Blocked by #82

**Comment by kcopas** [comment]
Expand overview available [here](http://www.gbif.org/publishing-data/summary)

**Comment by timrobertson100** [comment]
Could well be publishing, and classes of data should be merged.  I just felt with only the classes of data, something was missing...

**Comment by dnoesgaard** [comment]
New publishing guide in place (/publishing-guide) with links out to relevant tools and docs.
