### ISSUE TITLE
Drafting: Darwin core

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#84]
A page linked from the menu describing what Darwin Core (standards in general?) is.

Blocked by #82

**Comment by kcopas** [comment]
Should we be publishing the new pages, or simply adding content?
[http://www.gbif.org/publishing/darwin-core](http://www.gbif.org/publishing/darwin-core)

And should we start creating pages for any of these items that are translated? The text of this page, for instance, is available in French, Spanish and Portuguese.

**Comment by kcopas** [comment]
Note to self and @dnoesgaard : probably should add a brief intro here that references Biocase, Tapir and any other standard currently in use, without additional comment (esp. if we can link to something else)

**Comment by kcopas** [comment]
@burkeker @MortenHofft, when @dnoesgaard and I add content to the stubs listed as portal16 issues, do you want us to publish them? Just checking…

**Comment by MortenHofft** [comment]
Better check with Burke but I would assume not. It will show up anyhow. See http://demo.gbif.org/generic/publishing/darwin-core for example

**Comment by kcopas** [comment]
Add literature reference/citation to [Darwin Core: An Evolving Community-Developed Biodiversity Data Standard](http://dx.doi.org/10.1371/journal.pone.0029715)

**Comment by kcopas** [comment]
Page needs graphics for visual relief/impact, but content is live.
