### ISSUE TITLE
Drafting: Digitizing collections

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#85]
A page linked from the menu describing collections digitization.

Blocked by #82

**Comment by kcopas** [comment]
New content: one of the next explainers, to be written by @smasinde and y.t. 

Will rely heavily on linking out to more detailed resources elsewhere, like those produced by e.g. [iDigBio](https://www.idigbio.org/wiki/index.php/Digitization_Resources)

**Comment by kcopas** [comment]
Please remove this page from the main navigation for the 14/8 launch—content is not complete and Siro's gone. 

We'll unpublish it and pick it up again as and when necessary.

**Comment by MortenHofft** [comment]
captured by https://github.com/gbif/portal16/issues/411
