### ISSUE TITLE
234,987,629 records at time of download?

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#856]
https://github.com/gbif/portal16/blob/15c4d88d79f7be5bad60d4497a7e7c0ddaf5ebe1/app/views/pages/occurrence/download/key/occurrenceDownloadKey.nunjucks#L250

This number, showing when hovering over individual datasets on download pages, appears hard-coded for some reason?

**Comment by MortenHofft** [comment]
clearly an oversight - thanks
