### ISSUE TITLE
Drafting: Citizen science

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#86]
A page linked from the menu describing Citizen science in GBIF.

Blocked by #82

**Comment by kcopas** [comment]
Mine. Will highlight present understanding of #citsci contributions to GBIF-mediated data and (more importantly) direct individuals interested in sharing data to possible solutions (iNat/iNat projects, national platforms, etc.)

**Comment by kcopas** [comment]
First draft live. Needs review and refinement, from y.t. and others…
