### ISSUE TITLE
Drafting: Living Atlases

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#87]
A page linked from the menu describing what The Atlas project (by ALA) is.

**Comment by kcopas** [comment]
Per @timrobertson100: we will create a “programme” entry for the Atlases, using a content model that serves as an umbrella entity over projects (the same that currently serves BID, BIFA and the CEP sections). 

We'll create a project for each partner involved (GBIF.es, GBIF France, NBN etc), and create entries for the events that have happened, link out to their installations etc.  Once the basics were in place we’d work with the groups directly to complete a summary of their status, and ideally their roadmap. This approach  will help demonstrate the capacity enhancement and knowledge exchange underway and this is directly addressing what GBIF France requested.

It would appear in search, and initially under our new menu structure linked under the tools section we’ve identified as needed.  We might revise this as content fills out and it might end up under the Inside GBIF section, or both – we’re in these kind of discussions with the comms team now so too early to decide definitively.

**Comment by timrobertson100** [comment]
Much can probably be reused from here on the summary info, and these resources should probably be linked for download (with attribution to the ALA for the Infrastructure, and GBIF Belgium/Spain/France + maybe more? for the KTD)

[KTDfinal_en (1).pdf](https://github.com/gbif/portal16/files/528063/KTDfinal_en.1.pdf)
[ALA Infrastructure Implementation - overview (24 6 16) - final (1).pdf](https://github.com/gbif/portal16/files/528064/ALA.Infrastructure.Implementation.-.overview.24.6.16.-.final.1.pdf)

**Comment by kcopas** [comment]
Link existing CE support project, [Encounter Bay](http://www.gbif.org/project/2015-ala-internationalization)
[News item on GBIF.es launch](http://www.gbif.org/page/62250)
[Very early (2011) training press](http://www.gbif.org/resource/81804)

Do we need to do any clean-up to tighten materials on key earlier projects and events, like
1. ALA-INBio mentoring project, 2012 [news item](http://www.gbif.org/page/165) or [event](http://www.gbif.org/event/59870) (check with mraymond on project description and/or report?)
2. [ALA Workshop](http://www.gbif.org/event/59934), July 2014
3. [GBIF/ALA workshop, Paris](http://www.gbif.org/newsroom/news/new-national-data-portal-in-france) (May 2015)
4. CoopBioPlat workshop, Madrid: [Oct 2015 news item](http://www.gbif.org/page/82594) or event](http://www.gbif.org/event/82290); also linked to Encounter Bay (see above)
5. BGBM workshop to investigate use of ALA components for BGBM projects (Nov 2015)
6. GBIF France workshop on spatial components (Feb 2016)

Note also connection to Symbiota (Northern Arizona University), which received a NSF grant to implement/integrate ALA Spatial portal components into [their software](https://github.com/Symbiota) 

Also: [original Brazilian portal](https://portaldabiodiversidade.icmbio.gov.br/portal)

**Comment by kcopas** [comment]
Is the overarching NBN Atlas one project or four/five? I think I know this, but I'm just asking...

**Comment by timrobertson100** [comment]
Tricky one to answer actually... Architecturally speaking it is 1 backend system and data management practice, but will be presented as ALS, ALW, ALE to the user.  I don't know if there will be an ALUK or not.

**Comment by kcopas** [comment]
Agreed. This is what I wanted to dig up, make sure I didn't dream it or something stupid like that: NBN's take on it all

[**NBN Atlas – the name**](https://nbn.org.uk/news/nbn-atlas-brief-update)
The new Atlases will all have the pre-fix “NBN” to ensure consistency of branding and strengthening of the NBN name.  Therefore, the various portals will be known as follows:

+ NBN Atlas – the overarching Atlas and underlying database
+ NBN Atlas England
+ NBN Atlas Northern Ireland
+ NBN Atlas Scotland
+ NBN Atlas Wales

The project on GBIF should thus be "NBN Atlas", with links to each of the four nations' sites, no?

**Comment by timrobertson100** [comment]
I'd agree that was best.  1 project, and 4 links and description of their
set up, roadmap, they can describe their approach, funding etc etc.

+1

**Comment by kcopas** [comment]
Can I ask: is "Atlases" the label? My gut instinct is that this will be poorly understood unless you already know what you're looking for, and that something like 'Living Atlases' might be preferable. 

That approach would also make the ALA homage a bit more explicit and (hopefully) clearer. For thought and later discussion...

**Comment by timrobertson100** [comment]
It's not settled, and the ALA folk should be involved in the decision.  I
am sure they are open to suggestions.

**Comment by kcopas** [comment]
John LaSalle gave 'Living Atlases' the thumbs-up at GB23. Do we need to check in with anyone else—@davemartin maybe? 

Will hold off updating the title of this issue until resolved…

**Comment by timrobertson100** [comment]
DJM says: "if John’s happy, I’m happy"

**Comment by kcopas** [comment]
+1

**Comment by DaveMartin** [comment]
Hi – not sure why I’ve received this message, guess someone has got me confused with another Dave Martin

 

This is Dave Martin in the Isle of Man – Dave Martin@manx.net

**Comment by djtfmartin** [comment]
Just to say thanks @kcopas @timrobertson100. This is all sounding really great :)

**Comment by DaveMartin** [comment]
Hi – not sure why I’ve received this message, guess someone has got me confused with another Dave Martin

 

This is Dave Martin in the Isle of Man – Dave Martin@manx.net

**Comment by cgendreau** [comment]
Sorry @DaveMartin, indeed the message was intended to @djtfmartin. I changed the original message. Do you want me to delete your answers above? (so you won't receive more notifications).

Sorry about that

**Comment by DaveMartin** [comment]
Thanks Christian – if you can easily do so, it might be best to delete any mention of my name – also so its clear that the Dave Martin they were intended for didn’t get them!

 

Thanks again & kind regards / Dave (IOM)

**Comment by kcopas** [comment]
Deep background, discovered by chance in the comms section of [Box.com](https://gbif.box.com/s/xqrpt4jxy1wui6f85xfozbsghclnj29u)

> Australia Government Awards $30 million to Develop System to Manage Australia’s Biological DiversityDataCanberra, Australia, 25 May 2009.
> The Australian government announced on 12 May the award of $30 million for the Atlas of Living Australia (ALA) for work during 2009-2011. 
> Commonwealth Scientific and Industrial Research Organisation(CSIRO) Group Executive for Agribusiness, Dr Joanne Daly, said, “the funding will help develop the Atlas of Living Australia into a world-class research tool.”  Hosted by CSIRO and in collaboration with partners in government, museums and the universities, the program is developing a biodiversity data management system which will link Australia’s biological knowledge with its scientific and agricultural reference collections and other custodians of biological information.
> “To have integrated information on all Australian species, including data on specimens held by Australia’s natural history collections and data from field observations of living organisms is a very valuable research tool,” Dr. Daly said.  “The funds will allow CSIRO and our partners to support the management and integration of biological data from all areas of research from molecular to ecological,” Daly continued.ALA was established by the Australian government in 2007 as a collaboration between Australian government agencies, museums and universities with government funding totaling $8.2 million for the period 2007-2011.  
> The goal of the project is to build web infrastructure to link information from institutions and agencies throughout Australia on all species found inthe continentand its surrounding waters. This will be a foundational resource for research, policy and education.In particular the ALA will allow researchers to understand the variation in biodiversity across the landscape and to use this information for the benefit of conservation and agriculture.
> The ALA will also support Australia's biosecurity response to new pests, weeds and diseases, particularly as species distributions alter under climate change.The ALA will use web technologies to allow users and experts to add to existing information and to improve the quality of the data and tools.The new $30 million ensures that ALA can deliver a comprehensive set of tools for managing distribution data, descriptions, images, literature and molecular data for any species.  These systems will assist Australian researchersin responding rapidly to new discoveries and tobase planning and policy decisions on the fullest available scientificdata and will feed directly into international networks and projects such as GBIF and EOL

**Comment by kcopas** [comment]
The programme/project complex for Living Atlases is stubbed out and (I hope) ready to share provisionally with the actual participants (Participants) for refinement, once we can get it to display on demo.

**Comment by dnoesgaard** [comment]
@kcopas - this one is done, right?
