### ISSUE TITLE
Glossary candidates

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#872]
Hi @kcopas - I've compiled a list of words that appear frequently in the translations. I thought it might make for candidates for a glossary. I've removed very common words. It might still need some pruning. I got the impression that you were looking at building a glossary file - this might be useful.

|candidates for glossary|crude count in translation file|
|-----------------------|----------------|
|name|79|
|species|50|
|occurrences|37|
|Data|35|
|dataset|35|
|record|34|
|participant|26|
|ID|25|
|issues|24|
|type|23|
|coordinates|22|
|contact|22|
|organization|22|
|download|22|
|committee|21|
|unknown|20|
|publisher|20|
|published|19|
|backbone|19|
|Nodes|17|
|gbif|17|
|location|16|
|accepted|15|
|Name|15|
|Verbatim|15|
|chair|15|
|charts|15|
|key|14|
|value|14|
|extension|14|
|interpreted|14|
|terms|14|
|ingestion|14|
|password|14|
|Participant|13|
|network|13|
|Governing|13|
|representative|13|
|email|13|
|search|13|
|parent|12|
|issue|12|
|feedback|12|
|publishing|11|
|Record|11|
|original|11|
|taxon|10|
|observation|9|
|required|9|
|specimen|8|
|Taxonomic|8|
|rank|8|
|verbatim|8|
|Node|8|
|Voting|8|
|Publishing|8|
|trends|8|
|filters|8|
|Event|7|
|interpretation|7|
|Validation|7|
|processed|7|
|processing|6|
|website|6|
|endorsement|6|
|Vernacular|5|
|occurring|5|
|Summary|5|
|Resource|4|
|Classification|4|

**Comment by kcopas** [comment]
Very big +1—tusind tak!

**Comment by MortenHofft** [comment]
I've reduced this and added them to the glossary in Crowdin.

```
backbone
chair
charts
classification
committee
contact
coordinates
data
dataset
download
email
endorsement
event
extension
feedback
filters
governing board
ingestion
interpretation
interpreted
issue
location
metrics
network
nodes
observation
occurrences
occurring
organization
original
parent
participant
password
processed
processing
published
publisher
publishing
rank
record
representative
required
resource
search
species
specimen
summary
taxon
taxonomic
terms
trends
type
unknown
validation
verbatim
vernacular
voting
website
```
