### ISSUE TITLE
Check ingestion status less frequently (health check)

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal16#886]
Calls to /dataset/process/running are very expensive, especially when there are many things in the queue.

Is it possible to check this less frequently, such as every 30s (or even longer, it's monitoring something that's not very interactive).

**Comment by MattBlissett** [comment]
Also, some of the queries don't have the parameter

```
130.225.43.8 - - [09/Jul/2018:20:17:33 +0200] "GET http://api.gbif.org/v1/dataset/process/running?v=%7BSECONDS_AGO%7D HTTP/1.1" 200 232 "-" "-"
130.225.43.8 - - [09/Jul/2018:20:17:33 +0200] "GET http://api.gbif.org/v1/dataset/process/running?v=1531160253120 HTTP/1.1" 200 232 "-" "-"
130.225.43.128 - - [09/Jul/2018:20:17:38 +0200] "GET http://api.gbif.org/v1/dataset/process/running?v=%7BSECONDS_AGO%7D HTTP/1.1" 200 232 "-" "-"
130.225.43.128 - - [09/Jul/2018:20:17:38 +0200] "GET http://api.gbif.org/v1/dataset/process/running?v=1531160258670 HTTP/1.1" 200 232 "-" "-"
```

**Comment by MortenHofft** [comment]
Sure- it is a setting for all endpoints. I've lowered it to only query every 30 seconds. That also means that if it fails it will show for 30 seconds and not just 10 if it is a temporary fluke.

strange that it is missing the timestamp. Are they requests from the portal? I guess they will just be cached, so little harm for performance, but odd.
