### ISSUE TITLE
Drafting: Become a member

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#89]
A page linked from the menu describing how someone becomes a member in GBIF.

Blocked by #82

**Comment by kcopas** [comment]
Precedents:
[How to join](http://www.gbif.org/participation/how-to-join)
[Generic guidance on promoting GBIF participation among African countries_v1.docx](https://github.com/gbif/portal16/files/528038/Generic.guidance.on.promoting.GBIF.participation.among.African.countries_v1.docx)

**Comment by dnoesgaard** [comment]
done. 

https://www.gbif-uat.org/become-member
