### ISSUE TITLE
enum mismatch / translation missing

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#892]
https://www.gbif.org/data-use/5IofY4L9hmQwgWwSCMekg2/neon-30-years-of-ecological-monitoring-across-the-united-states

![neon_-_30_years_of_ecological_monitoring_across_the_united_states](https://user-images.githubusercontent.com/21358085/42503177-4b77fe92-8438-11e8-8a84-40a8d805b507.png)

**Comment by MortenHofft** [comment]
that is because some items have been tagged `DATA_CURATION_&_QUALITY` and other `DATA_CURATION_QUALITY` at some point I looked and saw that `DATA_CURATION_QUALITY` was used therefor thought the other was a mistake. I suggest not to use both.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/2848a77f823d75b05d172eae791e2a7669d42d6c

I've changed it to use above key. Use of any other keys will then result in a similar error. Perhaps Contentful, Mendeley or cms API been changed to remove the `&` . Notice that this means that translations of the old key is lost. If previous translations exists of the old key, then it should be manually transferred to to match the new key.
