### ISSUE TITLE
Data use: Broken links 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#9]
The links to next and previous are hard coded and should link to the associated article.

This requires considered changes to the CMS API, which should be done in a manner that will be suitable should GBIF move to a cloud CMS system.  That is to say, we might want to consider a ```.../news/1.meta``` which returns the extra info so that ```.../news/1``` is managed as a fully RESTful entity if it would allow an easier future migration to Contentful or CloudCMS.  Needs considered design...

**Comment by burkeker** [comment]
Done as
API: https://github.com/gbif/gbif-drupal/commit/65646419ddec2af1965944f6602fa2bf26652125
Web layer: https://github.com/gbif/portal16/commit/2c162615e9c219e176310e16463119a2ed4ec8b3
