### ISSUE TITLE
Drafting: Governance

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#90]
A page linked from the menu describing the GBIF governance.  Likely relates very closely with #88

Blocked by #82

**Comment by kcopas** [comment]
[Precedent](http://www.gbif.org/governance/governing-board) requires major streamlining and editing. While content is nothing if not generic, @MortenHofft + @burkeker, can we discuss implementation strategies at some point soon?

**Comment by kcopas** [comment]
Much of this is already mostly captured by @burkeker's [contact directory](http://demo.gbif.org/directory/contact-us) displaying the different governance groups and the [funding page](http://demo.gbif.org/funders). Need to review soon with TH, AMN and SBJ.

**Comment by kcopas** [comment]
Reviewed with AMN. Combination of contact directory and funders page does cover most content, though some small adjustments are needed (see #157 ). 
-[ ] @dnoesgaard , can you see that brief descriptions get added to each committee section, working from existing text? 

Once completed, 'governance' page per se is complete for 2016 launch target.

**Comment by dnoesgaard** [comment]
I see that these texts are handled as MarkDown documents in GitHub (e.g. portal16/locales/markdown/directory/contactUs/voting_participants/en.md). Can I edit these myself - and if so, could someone (@timrobertson100 or @burkeker) show me how I do that?

**Comment by dnoesgaard** [comment]
Alternatively, please add the follow descriptions to relevant groups:

__Voting participants__
Countries that have signed the GBIF Memorandum of Understanding and agree to make a basic financial contribution to GBIF core funds.

__Associate country participants__
Countries that have signed the GBIF Memorandum of Understanding but do not make a financial contribution to GBIF core funds, and do not have a vote on the GBIF Governing Board.

__Other associate participants__
Intergovernmental organizations, international organizations and other organizations with an international scope, and economies, that have signed the GBIF Memorandum of Understanding.

__Executive committee__
The Executive Committee operates on behalf of the Governing Board when the Board is not in session and within the areas of responsibility delegated to it by the Governing Board. Among its functions are monitoring of the performance of the Secretariat in carrying out the decisions taken by the Governing Board including implementation of the Strategic Plan and the Work Programme, and management of the budget.

__Science committee__
The GBIF Science Committee is an advisory committee that oversees the development and progress of the GBIF work programme and makes recommendations to the Governing Board, the Executive Committee and the Secretariat. You can read its terms of reference [here](/resource/80877).

__Budget committee__
The Budget Committee is an advisory committee dealing with various financial issues relating to the administration of GBIF funds. Among other functions, it oversees the audit of the annual accounts submitted to the Governing Board, and it provides guidance for the selection of GBIF's auditing company. The committee makes recommendations to the Governing Board, the Executive Committee and the Secretariat. Its terms of reference can be found here.

__Nodes steering group__
	The Nodes Steering Group (NSG), established in 2011, consists of the Chair and Vice Chairs of the Participant Node Managers Committee, and regional representatives from each of the six GBIF regions (Africa, Asia, Europe, Latin America, North America and Oceania).  Among its objectives are to formulate specific recommendations to the relevant GBIF bodies based on feedback provided by Participant nodes, and to provide advice on the GBIF Work Programme relevant to nodes.

__Nodes committee__
	The Nodes Committee serves as a forum for sharing information about the status and best practices of GBIF Participant nodes. It also acts as an advisory committee making recommendations to the Governing Board, the Executive Committee, the Science Committee and the Secretariat concerning issues relevant to the nodes.

__GBIF Secretariat__
The GBIF Secretariat, located at the Natural History Museum in Copenhagen, Denmark, is charged with developing, executing and reporting on the GBIF work programme. The tasks of the Secretariat include:
	- operating the GBIF portal and associated informatics products
 	- coordinating  activities of the network related to data mobilization, publishing and management
 	- monitoring data gaps and use of GBIF-mediated data for science, and
 	- operating central communication and collaboration services

**Comment by MortenHofft** [comment]
These need to be added to the[ translation file](https://github.com/gbif/portal16/blob/master/locales/server/en.json#L2013). Looks like it might be neccessary to take that discussion about markdown in the translation file. I say add it and parse all translation as if they contain md.
