### ISSUE TITLE
Metadata updates when dataset republished through IPT

### ISSUE THREAD

**Issue by dshorthouse** [gbif/portal16#908]
What triggers metadata updates on gbif.org for datasets? I updated the metadata for https://www.gbif.org/dataset/7086bdef-e377-4ac5-872f-751b1d614ed2 without any change in underlying data & republished the resource in an IPT. However, the changes I made appear not to bubble up. Must there also be change in data in the republication event for metadata changes to be recognized?

**Comment by MortenHofft** [comment]
Thanks. Crawling has been off lately as we were reindexing everything. Might be related to that. I have moved your question to https://github.com/gbif/portal-feedback/issues/1449 as this project is about the website and this has to do with crawling and the APIs.
