### ISSUE TITLE
Drafting: Citation guidelines

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#92]
A page linked from the menu describing citation guidelines

Blocked by #82

**Comment by kcopas** [comment]
@kbraak @ahahn-gbif and dschigel are very much part of this fun. Don't be shy.

**Comment by ahahn-gbif** [comment]
See https://goo.gl/9oxQJq: rough first draft / material under the header "Citation Guide", from p.5 or thereabouts. To be completed over the next days.

**Comment by kcopas** [comment]
Post-GB23, most likely

**Comment by dnoesgaard** [comment]
Something to consider for citation guidelines. Services such as the CrossCite DOI citation formatter will generate ready-to-use citations for people, but there are inconsistencies that might worth looking into, e.g.

Download DOI:
10.15468/dl.tpm2fm
We tell people to cite as: 

> GBIF.org (4th March 2016) GBIF Occurrence Download http://doi.org/10.15468/dl.tpm2fm

The CrossCite DOI citation formatter tell people to cite as:

> occdownload gbif.org. (2016). GBIF Occurrence Download [Data set]. The Global Biodiversity Information Facility. https://doi.org/10.15468/dl.tpm2fm

Dataset DOI:
10.15468/aiiz3z
We tell people to cite as either 

> 1) National Biodiversity Data Centre: Collated by the National Biodiversity Data Centre from different sources - Ireland's BioBlitz. Dataset/Occurrence.

> 2) National Biodiversity Data Centre: Ireland's BioBlitz. doi:10.15468/aiiz3z Accessed via http://www.gbif.org/dataset/80576d53-992a-41f3-a3e3-dfd0fa0242ee on 2016-11-01

The CrossCite DOI citation formatter tell people to cite as:

> Liam Lysaght. (2016). Ireland’s BioBlitz [Data set]. National Biodiversity Data Centre. https://doi.org/10.15468/aiiz3z

**Comment by kcopas** [comment]
[First draft](http://demo.gbif.org/citation-guidelines) is largely complete, but it needs suggested practices for accessing data via the GBIF API and rgbif. 

Note also the fake email address under custom data exports—not sure where that should point (preferences, @ahahn-gbif?)

No graphics either, as yet—not sure whether/how to illustrate visually.

**Comment by kcopas** [comment]
Can we get this page—[http://drupaledit.gbif.org/citation-guidelines](http://drupaledit.gbif.org/citation-guidelines)—hooked up to the [demo page](http://demo.gbif.org/generic/citation-guidelines)?

**Comment by dnoesgaard** [comment]
Re. @kcopas' comment on "suggested practices for accessing data via the GBIF API and rgbif":

The publisher-provided citation for datasets is offered through the API:

Example: 6633ffa2-dc07-4d6f-a7e4-6f53d9d94dd7

```
<additionalMetadata>
<metadata>
<gbif>
<citation>
National Biodiversity Data Centre: Hugh Feeley - Plecoptera of Ireland. Dataset/Occurrence.
</citation>
```

and through rgbif via gbif_citation():

```
> gbif_citation('6633ffa2-dc07-4d6f-a7e4-6f53d9d94dd7')
<<rgbif citation>>
   Citation: National Biodiversity Data Centre: Hugh Feeley - Plecoptera of
        Ireland. Dataset/Occurrence.. Accessed from R via rgbif
        (https://github.com/ropensci/rgbif) on 2016-11-17
   Rights:
```

Neither of these, however, include DOIs...

Also, if a user uses occurrences from several datasets via e.g. rgbif, they don't necessarily have a download DOI, making citation complicated.
