### ISSUE TITLE
Geographic scope map incorrect for Amphibians of the Former USSR

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal16#948]
The geographic scope map for this dataset page  "Amphibians of the Former USSR" appears to be incorrect. 

https://www.gbif.org/dataset/e1c320f6-370e-4d5e-8253-9b5285a0775f

**Comment by thomasstjerne** [comment]
It seems to be a content issue. The westBoundingCoordinate and eastBoundingCoordinate should be swapped in the EML:

`<westBoundingCoordinate>-178.717</westBoundingCoordinate>
          <eastBoundingCoordinate>19.95</eastBoundingCoordinate>` 

Issue moved to: https://github.com/gbif/portal-feedback/issues/1484
