### ISSUE TITLE
Redirections for multilingual document (pre-translation cleanup)

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#967]
I'm decommissioning some of the old alt.language documents in favor of a single document with alt.versions attached as PDF, as in [this example](http://www.gbif.org/document/80661).

Can you implement the following redirects?

Each of the following:
- [ ] https://www.gbif.org/document/80626
- [ ] https://www.gbif.org/document/80517
- [ ] https://www.gbif.org/document/80924
- [ ] https://www.gbif.org/document/80507
should redirect to https://www.gbif.org/document/80509

Each of the following:
- [ ] https://www.gbif.org/document/80764
- [ ] https://www.gbif.org/document/80750
- [ ] https://www.gbif.org/document/80767
- [ ] https://www.gbif.org/document/80832
should redirect to http://www.gbif.org/document/80661

While you're at it, in the interest of efficiency, you might as well make these changes as well (I'll have them finished within the next couple days):

Each of the following:
- [ ] https://www.gbif.org/document/82249
- [ ] https://www.gbif.org/document/82251
- [ ] https://www.gbif.org/document/80951
- [ ] https://www.gbif.org/document/80947
- [ ] https://www.gbif.org/document/80946
- [ ] https://www.gbif.org/document/82278
should redirect to https://www.gbif.org/document/80813

Redirect 
- [ ] https://www.gbif.org/document/80730
to https://www.gbif.org/document/80575

Redirect each of the following
- [ ] https://www.gbif.org/document/82147
- [ ] https://www.gbif.org/document/82186
- [ ] https://www.gbif.org/document/82231
to https://www.gbif.org/document/80925

Redirect  each of the following
- [ ] https://www.gbif.org/document/82849
- [ ] https://www.gbif.org/document/82848
- [ ] https://www.gbif.org/document/82850
to https://www.gbif.org/document/82847

Will have a second wave of these at some point soon (I believe the above to be the only multi-lingual documents available in Spanish or Japanese).

**Comment by MortenHofft** [comment]
If it isn't to much of a hassle for you when writing these, then it would lower the risk of me forgetting some or mistyping if you wrote them like this:

https://github.com/gbif/gbif-configuration/blob/master/portal16/common/redirects.json

Perhaps we should also look into a simpler service for you to add these. I believe there used to be something running that allowed this. I'll ask around

**Comment by kcopas** [comment]
Happy to. 

Though I don't currently have access to the config repo to see the format ;-)

**Comment by MortenHofft** [comment]
oh - here goes. And if you prefer the other way, I'll rewrite them.
```
    {"incoming": "/document/80946" , "target" : "/document/80813"},
    {"incoming": "/document/82278" , "target" : "/document/80813"},
    {"incoming": "/document/80730" , "target" : "/document/80575"},
    {"incoming": "/document/82147" , "target" : "/document/80925"},
    {"incoming": "/document/82186" , "target" : "/document/80925"},
```

**Comment by kcopas** [comment]
perfect—got it.

Next batch will spring fully form(at)ed...
