### ISSUE TITLE
new field in Contentful to control date shown in GBIF.org

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#973]
@MortenHofft - we talked about this several times. I'm getting sick of writing json, so I'm suggesting we add some additional logic to the date shown on GBIF.org content.

On dev, I've added a date field to dataUse called `gbifDate` that should be used, if populated. It's indexed already for this item: http://cms-search.gbif-dev.org:9200/_search?q=id:82508

```
"gbifDate": "2018-08-20",
```

Metadata in json should still be respected because of old content.

I don't know you need to do this per content type? I've only changed the dataUse model for now.

**Comment by dnoesgaard** [comment]
Oh ok, I thought the logic happened in the front-end.

Yes, I want it as a general field, but wasn't sure if that made sense for you. For testing purposes here and now, I've added it to dataUse only (dev).

**Comment by dnoesgaard** [comment]
Actually, all 3 dates appear to be in the index:
https://www.gbif-dev.org/api/resource/search?q=id:82508

And the logic happens in the front-end, no?

https://github.com/gbif/portal16/blob/8f5e690e43886b6a16d1b3ef84d50626741fb355/app/views/pages/resource/key/dataUse/dataUseStory.nunjucks#L12

**Comment by MortenHofft** [comment]
The individual datause stories, news etc all take their content directly from Contentful. That is why you can do instant previews without waiting for the index. But the creation date in the index is also used. For search results fx.

**Comment by MortenHofft** [comment]
The createdAt field that is computed in the index really isn't a good name for this info. It is a mock firstPublishedDate that we are after it seems to me. And we try to mock it with a combination of creation date, drupal-json and now your new gbifDate field.

**Comment by dnoesgaard** [comment]
Ah, now I get it. Well, if we need to tidy this up a bit, I'm all for it.

**Comment by dnoesgaard** [comment]
(no longer a pressing issue)
