### ISSUE TITLE
Events is not searchable by country

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#99]
The cms API does not allow to searching events by country.
Example:
http://internal.gbif-dev.org/cms/search?category_country=ES has no events listed
But the current site shows there is some
http://www.gbif.org/country/ES/news

This is because the country of the events is not using the country taxonomy, but a special field called venueCountry. To make events searchable by country, which seems like a useful feature, then the content model needs to be updated and existing events tagged

**Comment by burkeker** [comment]
Mapped the venue country field to field_country so it appears on the country facet.
![events by country](https://cloud.githubusercontent.com/assets/637631/21495316/f0937d06-cc16-11e6-9867-863599ee021e.png)

**Comment by MortenHofft** [comment]
choosing the top 3 countries
https://demo.gbif.org/cms/search?type=event&category_country=ZA&category_country=US&category_country=FR
i get odd facets
![screen shot 2016-12-29 at 11 57 10](https://cloud.githubusercontent.com/assets/6759267/21542442/0241f070-cdbe-11e6-8430-52e1cc526f5a.png)
It isn't a union nor an intersection.
